import * as stylex from '@stylexjs/stylex'

/*
 * Chatbot (`/chatbot`) — Lim, the jelly companion. Tokens live on
 * `.chatbot-shadow` / `.chatbot-dark` in chat/chat.css. Fredoka (wdth/wght)
 * for display, Inter for reading. Lim coral is the only accent.
 */
const DESK = '@media (min-width: 1024px)'
const RM = '@media (prefers-reduced-motion: reduce)'
const HOVER = '@media (hover: hover) and (pointer: fine)'
const DISPLAY = '"Fredoka", ui-rounded, "Nunito", system-ui, sans-serif'
const BODY = 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'
const MONO = 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace'
const SPRING = 'cubic-bezier(0.34, 1.56, 0.64, 1)'
const EASE = 'cubic-bezier(0.16, 1, 0.3, 1)'

const popIn = stylex.keyframes({
  '0%': { opacity: 0, transform: 'translateY(10px) scale(0.94)' },
  '60%': { opacity: 1, transform: 'translateY(-2px) scale(1.02)' },
  '100%': { opacity: 1, transform: 'translateY(0) scale(1)' },
})
const riseIn = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(14px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
})
const drift = stylex.keyframes({
  '0%': { transform: 'translate3d(0, 0, 0) scale(1)' },
  '50%': { transform: 'translate3d(4%, -3%, 0) scale(1.06)' },
  '100%': { transform: 'translate3d(-3%, 2%, 0) scale(0.97)' },
})
const bob = stylex.keyframes({
  '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
  '50%': { transform: 'translateY(-10px) rotate(8deg)' },
})
const jellyDot = stylex.keyframes({
  '0%, 70%, 100%': { transform: 'translateY(0) scale(1, 1)' },
  '20%': { transform: 'translateY(1px) scale(1.25, 0.75)' },
  '40%': { transform: 'translateY(-7px) scale(0.85, 1.15)' },
})
const squish = stylex.keyframes({
  '0%': { transform: 'scale(1, 1)' },
  '30%': { transform: 'scale(1.16, 0.84)' },
  '55%': { transform: 'scale(0.94, 1.08)' },
  '80%': { transform: 'scale(1.03, 0.98)' },
  '100%': { transform: 'scale(1, 1)' },
})
// Same squish twice, so alternating sends restart the animation without
// remounting (and de-focusing) the button.
const squishAgain = stylex.keyframes({
  '0%': { transform: 'scale(1, 1)' },
  '30%': { transform: 'scale(1.16, 0.84)' },
  '55%': { transform: 'scale(0.94, 1.08)' },
  '80%': { transform: 'scale(1.03, 0.98)' },
  '100%': { transform: 'scale(1, 1)' },
})
const caret = stylex.keyframes({
  '0%, 100%': { transform: 'translateY(0) scale(1)', opacity: 1 },
  '50%': { transform: 'translateY(-3px) scale(0.8)', opacity: 0.6 },
})

const focusRing = {
  outlineWidth: { default: 0, ':focus-visible': '3px' },
  outlineStyle: { default: 'none', ':focus-visible': 'solid' },
  outlineColor: 'var(--chat-focus)',
  outlineOffset: '2px',
} as const

/** Chatbot layout + chrome (App.tsx). */
export const chatbot = stylex.create({
  root: {
    position: 'relative',
    isolation: 'isolate',
    display: 'grid',
    gridTemplateColumns: { default: 'minmax(0, 1fr)', [DESK]: 'minmax(0, 1fr) clamp(440px, 40vw, 620px)' },
    gridTemplateRows: { default: 'auto clamp(190px, 30dvh, 300px) minmax(0, 1fr)', [DESK]: 'auto minmax(0, 1fr)' },
    gridTemplateAreas: { default: '"top" "stage" "chat"', [DESK]: '"stage top" "stage chat"' },
    columnGap: { default: 0, [DESK]: '20px' },
    paddingTop: { default: 'env(safe-area-inset-top, 0px)', [DESK]: '18px' },
    paddingRight: { default: 0, [DESK]: '18px' },
    paddingBottom: { default: 0, [DESK]: '18px' },
    width: '100%',
    height: '100dvh',
    minHeight: '100svh',
    overflow: 'hidden',
    color: 'var(--chat-text)',
    backgroundColor: 'var(--chat-bg)',
    fontFamily: BODY,
    transitionProperty: 'background-color, color, grid-template-rows',
    transitionDuration: '500ms',
    transitionTimingFunction: EASE,
  },
  /** Mobile, composer focused: shrink the stage so Lim stays in view. */
  rootCompact: {
    gridTemplateRows: { default: 'auto 128px minmax(0, 1fr)', [DESK]: 'auto minmax(0, 1fr)' },
  },
  skip: {
    position: 'absolute',
    zIndex: 50,
    top: '10px',
    left: '10px',
    paddingBlock: '10px',
    paddingInline: '16px',
    borderRadius: '999px',
    backgroundColor: 'var(--chat-user-bg)',
    color: 'var(--chat-user-text)',
    fontFamily: DISPLAY,
    fontWeight: 600,
    transform: { default: 'translateY(-160%)', ':focus': 'translateY(0)' },
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    ...focusRing,
  },

  // ── Backdrop: drifting sorbet blobs + a few doodles ──────────────
  backdrop: {
    position: 'absolute',
    inset: 0,
    zIndex: -1,
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  blob: {
    position: 'absolute',
    width: '70vmax',
    height: '70vmax',
    borderRadius: '50%',
    opacity: 0.9,
    animationName: drift,
    animationDuration: '24s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    animationDirection: 'alternate',
    animationPlayState: { default: 'running', [RM]: 'paused' },
    willChange: 'transform',
  },
  blob1: { top: '-38vmax', left: '-26vmax', backgroundImage: 'radial-gradient(closest-side, var(--chat-blob-1), transparent)' },
  blob2: { bottom: '-40vmax', left: '-8vmax', backgroundImage: 'radial-gradient(closest-side, var(--chat-blob-2), transparent)', animationDuration: '30s', animationDelay: '-8s' },
  blob3: { top: '-34vmax', right: '-30vmax', backgroundImage: 'radial-gradient(closest-side, var(--chat-blob-3), transparent)', animationDuration: '27s', animationDelay: '-14s' },
  blob4: { bottom: '-42vmax', right: '-24vmax', backgroundImage: 'radial-gradient(closest-side, var(--chat-blob-4), transparent)', animationDuration: '33s', animationDelay: '-4s' },
  doodle: {
    position: 'absolute',
    animationName: bob,
    animationDuration: '7s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    animationPlayState: { default: 'running', [RM]: 'paused' },
    opacity: 0.9,
  },
  doodleSparkle: { top: { default: '10%', [DESK]: '12%' }, left: { default: '8%', [DESK]: '9%' }, width: '30px', color: '#FFC94D' },
  doodleRing: { top: { default: '16%', [DESK]: '20%' }, left: { default: '78%', [DESK]: '46%' }, width: '34px', color: '#B9A6FF', animationDuration: '9s', animationDelay: '-3s' },
  doodleSquiggle: { top: { default: '34%', [DESK]: '58%' }, left: { default: '86%', [DESK]: '6%' }, width: '46px', color: '#7FD6B5', animationDuration: '8s', animationDelay: '-5s' },
  doodlePill: { display: { default: 'none', [DESK]: 'block' }, top: '38%', left: '40%', width: '40px', color: '#FF9FC5', animationDuration: '10s', animationDelay: '-2s' },
  doodleDots: { display: { default: 'none', [DESK]: 'block' }, top: '8%', left: '30%', width: '34px', color: '#FFB59E', animationDuration: '11s', animationDelay: '-6s' },

  // ── Header ───────────────────────────────────────────────────────
  top: {
    gridArea: 'top',
    position: 'relative',
    zIndex: 3,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    paddingBlock: { default: '6px', [DESK]: '12px' },
    paddingInline: { default: '10px', [DESK]: '14px' },
    backgroundColor: { default: 'transparent', [DESK]: 'var(--chat-panel)' },
    borderTopLeftRadius: { default: 0, [DESK]: '28px' },
    borderTopRightRadius: { default: 0, [DESK]: '28px' },
    borderBottomWidth: { default: 0, [DESK]: '1px' },
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--chat-card-line)',
    animationName: riseIn,
    animationDuration: '700ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
    animationDelay: '120ms',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minWidth: 0,
    flex: '1 1 auto',
    paddingLeft: '4px',
  },
  brandMark: { width: '34px', height: '34px', flexShrink: 0 },
  brandText: { display: 'flex', flexDirection: 'column', minWidth: 0, lineHeight: 1.05 },
  brandName: {
    margin: 0,
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: '22px',
    fontStretch: '108%',
    letterSpacing: '-0.01em',
    color: 'var(--chat-bright)',
  },
  brandSub: {
    fontSize: '12.5px',
    color: 'var(--chat-mid)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    minWidth: '44px',
    minHeight: '44px',
    paddingInline: '12px',
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: { default: 'transparent', ':hover': { default: null, [HOVER]: 'var(--chat-line)' } },
    backgroundColor: { default: 'transparent', ':hover': { default: null, [HOVER]: 'var(--chat-card)' } },
    color: 'var(--chat-text)',
    fontFamily: DISPLAY,
    fontWeight: 500,
    fontSize: '15px',
    textDecorationLine: 'none',
    cursor: 'pointer',
    transform: { default: null, ':active': 'scale(0.94)' },
    transitionProperty: 'transform, background-color, border-color',
    transitionDuration: '220ms',
    transitionTimingFunction: SPRING,
    ...focusRing,
  },
  iconButtonLabel: {
    display: { default: 'none', '@media (min-width: 560px)': 'inline' },
  },
  homeLink: {
    color: 'var(--chat-mid)',
  },

  // ── Stage ────────────────────────────────────────────────────────
  stageArea: {
    gridArea: 'stage',
    position: 'relative',
    minHeight: 0,
    minWidth: 0,
    // Desktop: bleed past the root padding so the floor meets the viewport.
    marginBlock: { default: 0, [DESK]: '-18px' },
    marginInlineStart: { default: 0, [DESK]: '-18px' },
  },
  stageCaption: {
    position: 'absolute',
    left: '50%',
    bottom: { default: '10px', [DESK]: '26px' },
    transform: 'translateX(-50%)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    paddingBlock: '6px',
    paddingInline: '14px',
    borderRadius: '999px',
    backgroundColor: 'color-mix(in srgb, var(--chat-card) 72%, transparent)',
    color: 'var(--chat-mid)',
    fontFamily: DISPLAY,
    fontWeight: 500,
    fontSize: { default: '13px', [DESK]: '14.5px' },
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    opacity: 1,
    transitionProperty: 'opacity',
    transitionDuration: '300ms',
  },
  stageCaptionHidden: { opacity: 0 },

  // ── Panel ────────────────────────────────────────────────────────
  panel: {
    gridArea: 'chat',
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    backgroundColor: 'var(--chat-panel)',
    borderTopLeftRadius: { default: '28px', [DESK]: 0 },
    borderTopRightRadius: { default: '28px', [DESK]: 0 },
    borderBottomLeftRadius: { default: 0, [DESK]: '28px' },
    borderBottomRightRadius: { default: 0, [DESK]: '28px' },
    boxShadow: { default: '0 -12px 32px -22px rgba(43, 33, 64, 0.35)', [DESK]: 'var(--chat-shadow)' },
    outline: 'none',
    animationName: riseIn,
    animationDuration: '800ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
    animationDelay: '180ms',
  },
  log: {
    flex: '1 1 auto',
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    scrollbarWidth: 'thin',
    paddingTop: { default: '18px', [DESK]: '22px' },
    paddingBottom: '18px',
    paddingInline: { default: '16px', [DESK]: '26px' },
  },
  logInner: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    maxWidth: '680px',
    marginInline: 'auto',
    minHeight: '100%',
  },

  // ── Empty state ──────────────────────────────────────────────────
  empty: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: { default: 'flex-start', [DESK]: 'center' },
    gap: '14px',
    flex: '1 1 auto',
    paddingBottom: { default: '4px', [DESK]: '24px' },
  },
  kicker: {
    alignSelf: 'flex-start',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    paddingBlock: '5px',
    paddingInline: '12px',
    borderRadius: '999px',
    backgroundColor: 'var(--chat-chip-2)',
    color: 'var(--chat-text)',
    fontFamily: DISPLAY,
    fontWeight: 500,
    fontSize: '13px',
    animationName: popIn,
    animationDuration: '600ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
    animationDelay: '260ms',
  },
  kickerDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#3FB58A',
    boxShadow: '0 0 0 3px rgba(63, 181, 138, 0.25)',
  },
  hello: {
    margin: 0,
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontStretch: '112%',
    fontSize: { default: 'clamp(30px, 8vw, 38px)', [DESK]: 'clamp(40px, 3.6vw, 56px)' },
    lineHeight: 1,
    letterSpacing: '-0.02em',
    color: 'var(--chat-bright)',
    animationName: riseIn,
    animationDuration: '700ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
    animationDelay: '320ms',
  },
  helloAccent: {
    color: 'var(--chat-accent-deep)',
  },
  intro: {
    margin: 0,
    maxWidth: '46ch',
    fontSize: { default: '15px', [DESK]: '16.5px' },
    lineHeight: 1.55,
    color: 'var(--chat-mid)',
    textWrap: 'pretty',
    animationName: riseIn,
    animationDuration: '700ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
    animationDelay: '400ms',
  },
  chips: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
    marginTop: '6px',
  },
  chip: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minHeight: '52px',
    paddingBlock: '10px',
    paddingInline: '12px',
    borderRadius: '18px',
    borderWidth: 0,
    textAlign: 'left',
    color: 'var(--chat-text)',
    fontFamily: DISPLAY,
    fontWeight: 500,
    fontSize: { default: '14px', [DESK]: '15px' },
    lineHeight: 1.2,
    cursor: 'pointer',
    boxShadow: {
      default: 'inset 0 -2px 0 rgba(43, 33, 64, 0.06)',
      ':hover': { default: null, [HOVER]: 'inset 0 -2px 0 rgba(43, 33, 64, 0.06), 0 10px 20px -14px rgba(43, 33, 64, 0.5)' },
    },
    transform: {
      default: null,
      ':hover': { default: null, [HOVER]: 'translateY(-3px) rotate(-0.6deg)' },
      ':active': 'scale(0.95)',
    },
    transitionProperty: 'transform, box-shadow',
    transitionDuration: '320ms',
    transitionTimingFunction: SPRING,
    animationName: popIn,
    animationDuration: '620ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
    ...focusRing,
  },
  chip1: { backgroundColor: 'var(--chat-chip-1)' },
  chip2: { backgroundColor: 'var(--chat-chip-2)' },
  chip3: { backgroundColor: 'var(--chat-chip-3)' },
  chip4: { backgroundColor: 'var(--chat-chip-4)' },
  chipIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    backgroundColor: 'color-mix(in srgb, var(--chat-card) 70%, transparent)',
  },

  // ── Messages ─────────────────────────────────────────────────────
  row: {
    display: 'flex',
    gap: '10px',
    minWidth: 0,
    animationName: popIn,
    animationDuration: '520ms',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
  },
  rowUser: { justifyContent: 'flex-end', transformOrigin: 'bottom right' },
  rowAssistant: { justifyContent: 'flex-start', transformOrigin: 'top left' },
  userBubble: {
    maxWidth: '85%',
    paddingBlock: '11px',
    paddingInline: '16px',
    borderRadius: '22px 22px 6px 22px',
    backgroundColor: 'var(--chat-user-bg)',
    color: 'var(--chat-user-text)',
    fontSize: '15px',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    boxShadow: '0 8px 20px -14px rgba(43, 33, 64, 0.6)',
  },
  avatar: {
    flexShrink: 0,
    width: '34px',
    height: '34px',
    marginTop: '2px',
  },
  assistantCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    minWidth: 0,
    flex: '0 1 auto',
    maxWidth: 'calc(100% - 44px)',
  },
  card: {
    minWidth: 0,
    paddingBlock: '13px',
    paddingInline: '17px',
    borderRadius: '6px 22px 22px 22px',
    backgroundColor: 'var(--chat-card)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--chat-card-line)',
    boxShadow: 'var(--chat-shadow)',
    overflowWrap: 'anywhere',
  },
  cardError: {
    backgroundColor: 'var(--chat-error-bg)',
    borderColor: 'var(--chat-error-line)',
    color: 'var(--chat-error-text)',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '2px',
    marginLeft: '-6px',
  },
  action: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minHeight: '44px',
    paddingInline: '10px',
    borderRadius: '999px',
    borderWidth: 0,
    backgroundColor: { default: 'transparent', ':hover': { default: null, [HOVER]: 'var(--chat-chip-1)' } },
    color: 'var(--chat-mid)',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    transform: { default: null, ':active': 'scale(0.94)' },
    transitionProperty: 'transform, background-color',
    transitionDuration: '200ms',
    transitionTimingFunction: SPRING,
    ...focusRing,
  },
  retry: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    minHeight: '44px',
    paddingInline: '16px',
    marginTop: '6px',
    borderRadius: '999px',
    borderWidth: 0,
    backgroundColor: 'var(--chat-accent)',
    color: 'var(--chat-on-accent)',
    fontFamily: DISPLAY,
    fontWeight: 600,
    fontSize: '15px',
    cursor: 'pointer',
    boxShadow: 'inset 0 -3px 0 rgba(0, 0, 0, 0.1), inset 0 2px 0 rgba(255, 255, 255, 0.45)',
    transform: { default: null, ':active': 'scale(0.95)' },
    transitionProperty: 'transform',
    transitionDuration: '220ms',
    transitionTimingFunction: SPRING,
    ...focusRing,
  },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '24px',
    paddingInline: '10px',
    borderRadius: '999px',
    backgroundColor: 'var(--chat-chip-3)',
    color: 'var(--chat-text)',
    fontSize: '12px',
    fontWeight: 500,
    marginRight: '4px',
  },
  thinking: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    paddingBlock: '6px',
  },
  thinkingDot: {
    width: '9px',
    height: '9px',
    borderRadius: '50%',
    animationName: { default: jellyDot, [RM]: 'none' },
    animationDuration: '1.1s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'ease-in-out',
    transformOrigin: 'bottom center',
  },
  caret: {
    display: 'inline-block',
    width: '9px',
    height: '9px',
    marginLeft: '4px',
    borderRadius: '50%',
    backgroundColor: 'var(--chat-accent)',
    verticalAlign: 'middle',
    animationName: { default: caret, [RM]: 'none' },
    animationDuration: '800ms',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'ease-in-out',
  },
  jump: {
    position: 'absolute',
    left: '50%',
    bottom: '100%',
    marginBottom: '10px',
    transform: 'translateX(-50%)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minHeight: '44px',
    paddingInline: '16px',
    borderRadius: '999px',
    borderWidth: 0,
    backgroundColor: 'var(--chat-user-bg)',
    color: 'var(--chat-user-text)',
    fontFamily: DISPLAY,
    fontWeight: 500,
    fontSize: '14px',
    cursor: 'pointer',
    boxShadow: '0 10px 24px -12px rgba(43, 33, 64, 0.6)',
    ...focusRing,
  },

  // ── Composer ─────────────────────────────────────────────────────
  composer: {
    position: 'relative',
    flexShrink: 0,
    paddingTop: '6px',
    paddingInline: { default: '12px', [DESK]: '20px' },
    paddingBottom: { default: 'max(12px, env(safe-area-inset-bottom, 0px))', [DESK]: '16px' },
  },
  composerInner: {
    maxWidth: '680px',
    marginInline: 'auto',
  },
  box: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '8px',
    padding: '6px',
    borderRadius: '28px',
    backgroundColor: 'var(--chat-card)',
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: { default: 'var(--chat-line)', ':focus-within': 'var(--chat-accent-deep)' },
    boxShadow: {
      default: 'var(--chat-shadow)',
      ':focus-within': '0 0 0 4px color-mix(in srgb, var(--chat-accent) 22%, transparent), var(--chat-shadow)',
    },
    transitionProperty: 'border-color, box-shadow',
    transitionDuration: '240ms',
  },
  textarea: {
    flex: '1 1 auto',
    minWidth: 0,
    minHeight: '44px',
    maxHeight: '160px',
    paddingBlock: '11px',
    paddingInline: '12px',
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: 'var(--chat-text)',
    fontFamily: BODY,
    fontSize: '16px',
    lineHeight: 1.4,
    resize: 'none',
    outline: 'none',
    '::placeholder': { color: 'var(--chat-soft)' },
  },
  send: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '46px',
    height: '46px',
    borderRadius: '50%',
    borderWidth: 0,
    color: 'var(--chat-on-accent)',
    backgroundImage: 'radial-gradient(circle at 34% 28%, var(--chat-accent-hi), var(--chat-accent) 52%, var(--chat-accent-deep))',
    boxShadow: 'inset 0 -3px 0 rgba(0, 0, 0, 0.1), inset 0 2px 1px rgba(255, 255, 255, 0.55), 0 8px 16px -8px rgba(224, 82, 106, 0.8)',
    cursor: 'pointer',
    transform: { default: null, ':hover': { default: null, [HOVER]: 'scale(1.06)' } },
    transitionProperty: 'transform, opacity, filter',
    transitionDuration: '260ms',
    transitionTimingFunction: SPRING,
    ...focusRing,
  },
  sendSquish: {
    animationName: { default: squish, [RM]: 'none' },
    animationDuration: '520ms',
    animationTimingFunction: 'ease-out',
  },
  sendSquishAgain: {
    animationName: { default: squishAgain, [RM]: 'none' },
    animationDuration: '520ms',
    animationTimingFunction: 'ease-out',
  },
  sendIdle: {
    opacity: 0.5,
    filter: 'saturate(0.6)',
    boxShadow: 'none',
    cursor: 'default',
    transform: 'none',
  },
  hint: {
    display: { default: 'none', '@media (hover: hover) and (pointer: fine)': 'flex' },
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '4px 12px',
    marginTop: '8px',
    fontSize: '12px',
    color: 'var(--chat-soft)',
  },
  kbd: {
    display: 'inline-block',
    minWidth: '20px',
    paddingInline: '5px',
    marginInline: '2px',
    borderRadius: '6px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--chat-line)',
    borderBottomWidth: '2px',
    backgroundColor: 'var(--chat-card)',
    fontFamily: MONO,
    fontSize: '11px',
    lineHeight: '18px',
    textAlign: 'center',
    color: 'var(--chat-mid)',
  },
})

const heheRise = stylex.keyframes({
  '0%': { opacity: 0, transform: 'translate(-50%, 0) scale(0.5) rotate(-8deg)' },
  '25%': { opacity: 1, transform: 'translate(-50%, -12px) scale(1.12) rotate(4deg)' },
  '100%': { opacity: 0, transform: 'translate(-50%, -64px) scale(1) rotate(-4deg)' },
})
const breathe = stylex.keyframes({
  '0%, 100%': { transform: 'translateX(-50%) scale(1, 1)' },
  '50%': { transform: 'translateX(-50%) scale(1.025, 0.975)' },
})
const hop = stylex.keyframes({
  '0%': { transform: 'translateX(-50%) translateY(0) scale(1, 1)' },
  '15%': { transform: 'translateX(-50%) translateY(0) scale(1.14, 0.86)' },
  '45%': { transform: 'translateX(-50%) translateY(-28%) scale(0.92, 1.1)' },
  '75%': { transform: 'translateX(-50%) translateY(0) scale(1.12, 0.88)' },
  '100%': { transform: 'translateX(-50%) translateY(0) scale(1, 1)' },
})
const poke = stylex.keyframes({
  '0%': { transform: 'translateX(-50%) scale(1, 1)' },
  '20%': { transform: 'translateX(-50%) scale(1.12, 0.86)' },
  '45%': { transform: 'translateX(-50%) scale(0.95, 1.06) rotate(2deg)' },
  '70%': { transform: 'translateX(-50%) scale(1.03, 0.98) rotate(-2deg)' },
  '100%': { transform: 'translateX(-50%) scale(1, 1)' },
})
const thoughtFloat = stylex.keyframes({
  '0%, 100%': { transform: 'translateY(0)' },
  '50%': { transform: 'translateY(-5px)' },
})

/** Lim's stage (LimStage.tsx): canvas, vector stand-in, head-anchored bubbles. */
export const stage = stylex.create({
  host: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
    touchAction: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
  },
  fallback: {
    position: 'absolute',
    inset: 0,
    opacity: 1,
    transitionProperty: 'opacity',
    transitionDuration: '450ms',
  },
  hidden: { opacity: 0, pointerEvents: 'none' },
  floorBand: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '24%',
    backgroundImage: 'linear-gradient(to bottom, transparent, var(--chat-floor) 45%)',
  },
  rug: {
    position: 'absolute',
    left: '50%',
    top: '80%',
    width: { default: 'min(76%, 300px)', [DESK]: 'min(62%, 520px)' },
    aspectRatio: '6 / 1',
    transform: 'translate(-50%, -50%)',
    borderRadius: '50%',
    backgroundColor: 'var(--chat-rug)',
  },
  art: {
    position: 'absolute',
    left: '50%',
    bottom: '20%',
    height: { default: '55%', [DESK]: '38%' },
    transform: 'translateX(-50%)',
    transformOrigin: '50% 100%',
    overflow: 'visible',
    cursor: 'pointer',
  },
  artBreathe: {
    animationName: breathe,
    animationDuration: '3.4s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
  },
  artHop: { animationName: hop, animationDuration: '700ms', animationIterationCount: 1, animationTimingFunction: 'ease-out' },
  artPoke: { animationName: poke, animationDuration: '600ms', animationIterationCount: 1, animationTimingFunction: 'ease-out' },
  live: {
    position: 'absolute',
    inset: 0,
    opacity: 0,
    transitionProperty: 'opacity',
    transitionDuration: '450ms',
  },
  liveShown: { opacity: 1 },
  anchor: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    pointerEvents: 'none',
    willChange: 'transform',
  },
  anchorStatic: {
    left: '50%',
    top: { default: '27%', [DESK]: '44%' },
  },
  thought: {
    position: 'absolute',
    left: 'calc(var(--u, 120px) * 0.55)',
    bottom: 'calc(var(--u, 120px) * 0.12)',
    animationName: { default: thoughtFloat, [RM]: 'none' },
    animationDuration: '2.4s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'ease-in-out',
  },
  thoughtCloud: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    paddingBlock: { default: '9px', [DESK]: '12px' },
    paddingInline: { default: '14px', [DESK]: '18px' },
    borderRadius: '999px',
    backgroundColor: 'var(--chat-card)',
    boxShadow: '0 10px 24px -14px rgba(43, 33, 64, 0.55), inset 0 -2px 0 rgba(43, 33, 64, 0.05)',
    animationName: popIn,
    animationDuration: '420ms',
    animationTimingFunction: SPRING,
    transformOrigin: 'bottom left',
  },
  thoughtPuff: {
    position: 'absolute',
    borderRadius: '50%',
    backgroundColor: 'var(--chat-card)',
    boxShadow: '0 6px 14px -8px rgba(43, 33, 64, 0.5)',
  },
  puffBig: { width: '14px', height: '14px', left: '-6px', bottom: '-12px' },
  puffSmall: { width: '8px', height: '8px', left: '-16px', bottom: '-22px' },
  hehe: {
    position: 'absolute',
    left: 0,
    bottom: '6px',
    fontFamily: DISPLAY,
    fontWeight: 700,
    fontStretch: '115%',
    fontSize: { default: '20px', [DESK]: '28px' },
    color: 'var(--chat-accent-deep)',
    WebkitTextStroke: '5px var(--chat-card)',
    paintOrder: 'stroke fill',
    whiteSpace: 'nowrap',
    animationName: heheRise,
    animationDuration: '1.1s',
    animationTimingFunction: EASE,
    animationFillMode: 'both',
  },
})

/** Route shell fallbacks (AppRoutes.tsx). */
export const routeFallback = stylex.create({
  shell: {
    display: 'flex',
    minHeight: '100dvh',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fafaf9',
    color: '#78716c',
    ':is(.dark *)': {
      backgroundColor: '#0c0a09',
      color: '#a8a29e',
    },
  },
  breathworkShell: {
    backgroundColor: 'var(--bw-canvas)',
  },
  label: {
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
  },
})

/** Site 404 page. */
export const siteNotFound = stylex.create({
  root: {
    display: 'flex',
    minHeight: '100dvh',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    backgroundColor: 'var(--chat-bg)',
    color: 'var(--chat-text)',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingTop: '4rem',
    paddingBottom: '4rem',
  },
  code: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    color: 'var(--chat-mid)',
  },
  title: {
    marginTop: '0.75rem',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '1.25rem',
    fontWeight: 500,
    letterSpacing: '-0.025em',
    '@media (min-width: 640px)': {
      fontSize: '1.5rem',
    },
  },
  body: {
    marginTop: '0.75rem',
    maxWidth: '24rem',
    fontSize: '0.875rem',
    lineHeight: 1.625,
    color: 'var(--chat-mid)',
  },
  actions: {
    marginTop: '1.5rem',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  primaryLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    borderRadius: '0.375rem',
    backgroundColor: 'var(--chat-accent)',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: 'var(--chat-bg)',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineOffset: '2px',
      outlineColor: 'var(--chat-accent)',
    },
  },
  secondaryLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    borderRadius: '0.375rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--chat-line)',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    fontSize: '0.875rem',
    color: 'var(--chat-text)',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineOffset: '2px',
      outlineColor: 'var(--chat-accent)',
    },
  },
})

/** Route error boundary recovery surface. */
export const routeError = stylex.create({
  root: {
    display: 'flex',
    minHeight: '100dvh',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    backgroundColor: '#fafaf9',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingTop: '2.5rem',
    paddingBottom: '2.5rem',
    textAlign: 'center',
    color: '#1c1917',
    ':is(.dark *)': {
      backgroundColor: '#0c0a09',
      color: '#f5f5f4',
    },
  },
  heading: {
    maxWidth: '28rem',
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: '1.5rem',
    '@media (min-width: 640px)': {
      fontSize: '1.875rem',
    },
  },
  headingChatbot: {
    color: '#1c1917',
    ':is(.dark *)': {
      color: '#f5f5f4',
    },
  },
  headingBreathwork: {
    color: '#92400e',
    ':is(.dark *)': {
      color: '#fcd34d',
    },
  },
  headingKorea: {
    color: '#9f1239',
    ':is(.dark *)': {
      color: '#fda4af',
    },
  },
  headingTrips: {
    color: '#92400e',
    ':is(.dark *)': {
      color: '#fcd34d',
    },
  },
  body: {
    maxWidth: '28rem',
    fontSize: '0.875rem',
    color: '#57534e',
    ':is(.dark *)': {
      color: '#a8a29e',
    },
  },
  reloadBtn: {
    marginTop: '0.5rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    backgroundColor: '#1c1917',
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#fafaf9',
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px #a8a29e',
    },
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: '#44403c',
      },
    },
    ':is(.dark *)': {
      backgroundColor: '#f5f5f4',
      color: '#1c1917',
      '@media (hover: hover) and (pointer: fine)': {
        ':hover': {
          backgroundColor: '#d6d3d1',
        },
      },
    },
  },
})
