import * as stylex from '@stylexjs/stylex'
const grainBg = `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E")`

/** Chatbot homepage layout + chrome (App.tsx). */
export const chatbot = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100dvh',
    minHeight: '100svh',
    overflow: 'hidden',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 0%',
    minHeight: 0,
    position: 'relative',
    zIndex: 10,
    maxWidth: '42rem',
    marginLeft: 'auto',
    marginRight: 'auto',
    width: '100%',
    paddingTop: 'env(safe-area-inset-top, 0px)',
  },
  scrollArea: {
    flex: '1 1 0%',
    minHeight: 0,
    overflowY: 'auto',
    overflowX: 'hidden',
    overscrollBehavior: 'contain',
    WebkitOverflowScrolling: 'touch',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    outline: 'none',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineOffset: '2px',
      outlineColor: 'var(--chat-accent)',
    },
  },
  headerFooter: {
    flexShrink: 0,
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    pointerEvents: 'none',
    zIndex: 1,
  },
  grainOverlay: {
    opacity: 0.04,
    zIndex: 2,
  },
  grain: {
    width: '100%',
    height: '100%',
    backgroundImage: grainBg,
    backgroundRepeat: 'repeat',
    backgroundSize: '256px 256px',
  },
  skipLink: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
    ':focus': {
      position: 'absolute',
      width: 'auto',
      height: 'auto',
      padding: '0 1rem',
      margin: 0,
      overflow: 'visible',
      clipPath: 'none',
      whiteSpace: 'normal',
      left: '1rem',
      top: '1rem',
      zIndex: 50,
      display: 'inline-flex',
      minHeight: '44px',
      alignItems: 'center',
      borderRadius: '0.375rem',
      backgroundColor: 'var(--chat-accent)',
      fontSize: '0.875rem',
      fontWeight: 500,
      color: 'var(--chat-bg)',
      ':focus-visible': {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineOffset: '2px',
        outlineColor: 'var(--chat-accent)',
      },
    },
  },
  header: {
    textAlign: 'left',
    transitionProperty: 'all',
    transitionDuration: '700ms',
    transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
  },
  headerCompact: {
    paddingTop: '1rem',
    paddingBottom: '1rem',
  },
  headerExpanded: {
    paddingTop: '2rem',
    paddingBottom: '2rem',
    '@media (min-width: 640px)': {
      paddingTop: '3.5rem',
      paddingBottom: '3.5rem',
    },
  },
  title: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 500,
    letterSpacing: '0.07em',
    textTransform: 'uppercase',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    fontSize: '10px',
    '@media (min-width: 640px)': {
      fontSize: '11px',
    },
  },
  titleCompact: {
    fontSize: '10px',
  },
  subtitle: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    marginTop: '0.25rem',
    fontSize: '10px',
    '@media (min-width: 640px)': {
      fontSize: '11px',
    },
  },
  subtitleCompact: {
    fontSize: '10px',
  },
  headerRule: {
    transitionProperty: 'all',
    transitionDuration: '700ms',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
  },
  headerRuleCompact: {
    marginTop: '0.75rem',
  },
  headerRuleExpanded: {
    marginTop: '1.25rem',
  },
  messageList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
  },
  messageRowEnd: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  userBubble: {
    maxWidth: '85%',
    fontSize: '14px',
    lineHeight: 1.7,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    borderRadius: '0.5rem',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    '@media (min-width: 640px)': {
      maxWidth: '75%',
    },
  },
  assistantBubble: {
    maxWidth: '92%',
    '@media (min-width: 640px)': {
      maxWidth: '85%',
    },
  },
  scrollAnchor: {
    height: '1rem',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    height: '100%',
    paddingTop: '1rem',
    paddingBottom: '1rem',
    '@media (min-width: 640px)': {
      paddingTop: '2.5rem',
      paddingBottom: '2.5rem',
    },
  },
  emptyHeading: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 400,
    lineHeight: 1.5,
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    fontSize: '1rem',
    '@media (min-width: 640px)': {
      fontSize: '1.125rem',
    },
  },
  scrollFabWrap: {
    position: 'relative',
    zIndex: 20,
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
  },
  scrollFab: {
    position: 'absolute',
    bottom: '0.5rem',
    right: '1.5rem',
    display: 'inline-flex',
    minHeight: '44px',
    minWidth: '44px',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.5rem',
    transitionProperty: 'all',
    transitionDuration: '300ms',
  },
  footer: {
    flexShrink: 0,
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingTop: '1rem',
    paddingBottom: 'max(1rem, env(safe-area-inset-bottom))',
  },
  suggestionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '0.5rem',
    marginBottom: '1.25rem',
  },
  suggestionBtn: {
    minHeight: '44px',
    textAlign: 'left',
    fontSize: '12px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    lineHeight: 1.6,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    transitionProperty: 'all',
    transitionDuration: '300ms',
    ':disabled': {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
  },
  suggestionsRowWrap: {
    marginBottom: '0.75rem',
    marginLeft: '-1.5rem',
    marginRight: '-1.5rem',
  },
  suggestionsRow: {
    display: 'flex',
    gap: '0.5rem',
    overflowX: 'auto',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingBottom: '0.25rem',
    scrollSnapType: 'x proximity',
    msOverflowStyle: 'none',
    scrollbarWidth: 'none',
    '::-webkit-scrollbar': {
      display: 'none',
    },
  },
  suggestionChip: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    fontSize: '11px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    transitionProperty: 'all',
    transitionDuration: '300ms',
    flexShrink: 0,
    scrollSnapAlign: 'start',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    ':disabled': {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
  },
  inputBox: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '0.75rem',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    transitionProperty: 'all',
    transitionDuration: '700ms',
  },
  textarea: {
    flex: '1 1 0%',
    backgroundColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    resize: 'none',
    fontSize: '14px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    lineHeight: 1.7,
    paddingLeft: '0.25rem',
    paddingRight: '0.25rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    maxHeight: '120px',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    borderRadius: '0.125rem',
  },
  textareaDisabled: {
    opacity: 0.5,
  },
  textareaFocus: {
    outline: 'none',
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 1px var(--bw-accent)',
      outlineOffset: '1px',
    },
  },
  sendBtn: {
    flexShrink: 0,
    transitionProperty: 'all',
    transitionDuration: '300ms',
    ':disabled': {
      opacity: 0.2,
      cursor: 'not-allowed',
    },
  },
  sendIconPulse: {
    animationName: 'pulse',
    animationDuration: '2s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
  },
  footerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '0.75rem',
  },
  footerNote: {
    fontSize: '10px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    letterSpacing: '0.04em',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
  },
  themeToggle: {
    display: 'inline-flex',
    minHeight: '44px',
    minWidth: '44px',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '300ms',
    opacity: 0.5,
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        opacity: 1,
      },
    },
  },
  typingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    paddingLeft: '0.25rem',
  },
  typingDot: {
    width: '0.375rem',
    height: '0.375rem',
    borderRadius: '9999px',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
  },
  typingDotDelay1: {
    animationDelay: '0.15s',
  },
  typingDotDelay2: {
    animationDelay: '0.3s',
  },
  skeleton: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    animationName: 'pulse',
    animationDuration: '2s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
  },
  skeletonLineWide: {
    height: '0.625rem',
    borderRadius: '0.25rem',
    width: '75%',
  },
  skeletonLineNarrow: {
    height: '0.625rem',
    borderRadius: '0.25rem',
    width: '50%',
  },
  iconSm: {
    width: '1rem',
    height: '1rem',
  },
  leavesHidden: {
    opacity: 0,
  },
  leavesVisible: {
    opacity: 1,
  },
})

/** Route shell fallbacks (AppRoutes.tsx). */
export const routeFallback = stylex.create({
  shell: {
    display: 'flex',
    minHeight: '100dvh',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fafaf9',
    color: '#78716c',
    ':is(.dark *)': {
      backgroundColor: '#0c0a09',
      color: '#a8a29e',
    },
  },
  breathworkShell: {
    backgroundColor: 'var(--bw-canvas)',
  },
  label: {
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
  },
})

/** Site 404 page. */
export const siteNotFound = stylex.create({
  root: {
    display: 'flex',
    minHeight: '100dvh',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    backgroundColor: 'var(--chat-bg)',
    color: 'var(--chat-text)',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingTop: '4rem',
    paddingBottom: '4rem',
  },
  code: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    color: 'var(--chat-mid)',
  },
  title: {
    marginTop: '0.75rem',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '1.25rem',
    fontWeight: 500,
    letterSpacing: '-0.025em',
    '@media (min-width: 640px)': {
      fontSize: '1.5rem',
    },
  },
  body: {
    marginTop: '0.75rem',
    maxWidth: '24rem',
    fontSize: '0.875rem',
    lineHeight: 1.625,
    color: 'var(--chat-mid)',
  },
  actions: {
    marginTop: '1.5rem',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  primaryLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    borderRadius: '0.375rem',
    backgroundColor: 'var(--chat-accent)',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: 'var(--chat-bg)',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineOffset: '2px',
      outlineColor: 'var(--chat-accent)',
    },
  },
  secondaryLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    borderRadius: '0.375rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--chat-line)',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    fontSize: '0.875rem',
    color: 'var(--chat-text)',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineOffset: '2px',
      outlineColor: 'var(--chat-accent)',
    },
  },
})

/** Route error boundary recovery surface. */
export const routeError = stylex.create({
  root: {
    display: 'flex',
    minHeight: '100dvh',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    backgroundColor: '#fafaf9',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingTop: '2.5rem',
    paddingBottom: '2.5rem',
    textAlign: 'center',
    color: '#1c1917',
    ':is(.dark *)': {
      backgroundColor: '#0c0a09',
      color: '#f5f5f4',
    },
  },
  heading: {
    maxWidth: '28rem',
    fontFamily: "'Cormorant Garamond', serif",
    fontSize: '1.5rem',
    '@media (min-width: 640px)': {
      fontSize: '1.875rem',
    },
  },
  headingChatbot: {
    color: '#1c1917',
    ':is(.dark *)': {
      color: '#f5f5f4',
    },
  },
  headingBreathwork: {
    color: '#92400e',
    ':is(.dark *)': {
      color: '#fcd34d',
    },
  },
  headingKorea: {
    color: '#9f1239',
    ':is(.dark *)': {
      color: '#fda4af',
    },
  },
  headingTrips: {
    color: '#92400e',
    ':is(.dark *)': {
      color: '#fcd34d',
    },
  },
  body: {
    maxWidth: '28rem',
    fontSize: '0.875rem',
    color: '#57534e',
    ':is(.dark *)': {
      color: '#a8a29e',
    },
  },
  reloadBtn: {
    marginTop: '0.5rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    backgroundColor: '#1c1917',
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#fafaf9',
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px #a8a29e',
    },
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: '#44403c',
      },
    },
    ':is(.dark *)': {
      backgroundColor: '#f5f5f4',
      color: '#1c1917',
      '@media (hover: hover) and (pointer: fine)': {
        ':hover': {
          backgroundColor: '#d6d3d1',
        },
      },
    },
  },
})
