import * as stylex from '@stylexjs/stylex'
import { chat } from './tokens.stylex'

/** Markdown body inside assistant chat bubbles. */
export const messageContent = stylex.create({
  root: {},
  thinkBlock: {
    fontSize: '12px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    marginBottom: '0.75rem',
    paddingBottom: '0.75rem',
    fontStyle: 'italic',
    lineHeight: 1.7,
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.mid,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: chat.line,
  },
  body: {
    maxWidth: 'none',
  },
  paragraph: {
    marginBottom: '0.75rem',
    fontSize: '14px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    lineHeight: 1.7,
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.text,
    ':last-child': {
      marginBottom: 0,
    },
  },
  link: {
    textDecorationLine: 'underline',
    textUnderlineOffset: '2px',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '300ms',
    color: chat.bright,
    textDecorationColor: chat.line,
  },
  strong: {
    fontWeight: 500,
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.bright,
  },
  em: {
    fontStyle: 'italic',
    color: chat.text,
  },
  inlineCode: {
    paddingLeft: '0.25rem',
    paddingRight: '0.25rem',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    backgroundColor: 'var(--chat-code-bg)',
    color: 'var(--chat-code-text)',
  },
  blockCode: {
    fontSize: '13px',
  },
  pre: {
    marginTop: '0.75rem',
    marginBottom: '0.75rem',
    padding: '1rem',
    overflowX: 'auto',
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    backgroundColor: 'var(--chat-code-bg)',
    color: 'var(--chat-code-text)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: chat.line,
  },
  ul: {
    marginTop: '0.75rem',
    marginBottom: '0.75rem',
    listStyleType: 'none',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    color: chat.text,
  },
  ol: {
    marginTop: '0.75rem',
    marginBottom: '0.75rem',
    listStyleType: 'decimal',
    listStylePosition: 'inside',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    color: chat.mid,
  },
  li: {
    fontSize: '14px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    lineHeight: 1.7,
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    paddingLeft: '0.75rem',
    color: chat.text,
  },
  dashPrefix: {
    color: chat.mid,
    marginRight: '8px',
  },
  blockquote: {
    marginTop: '0.75rem',
    marginBottom: '0.75rem',
    paddingLeft: '1rem',
    fontStyle: 'italic',
    fontSize: '14px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    lineHeight: 1.7,
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    borderLeftWidth: '2px',
    borderLeftStyle: 'solid',
    borderLeftColor: chat.line,
    color: chat.mid,
  },
  h1: {
    fontSize: '16px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 500,
    marginBottom: '1rem',
    marginTop: '1.5rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.bright,
    ':first-child': {
      marginTop: 0,
    },
  },
  h2: {
    fontSize: '14px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 500,
    marginBottom: '0.75rem',
    marginTop: '1.25rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.bright,
    ':first-child': {
      marginTop: 0,
    },
  },
  h3: {
    fontSize: '14px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 500,
    marginBottom: '0.5rem',
    marginTop: '1rem',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.bright,
    ':first-child': {
      marginTop: 0,
    },
  },
  h4: {
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 500,
    marginBottom: '0.5rem',
    marginTop: '0.75rem',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.bright,
    ':first-child': {
      marginTop: 0,
    },
  },
  tableWrap: {
    marginTop: '0.75rem',
    marginBottom: '0.75rem',
    overflowX: 'auto',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: chat.line,
  },
  table: {
    minWidth: '100%',
    fontSize: '13px',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  thead: {
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    backgroundColor: 'var(--chat-code-bg)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: chat.line,
  },
  th: {
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    textAlign: 'left',
    fontWeight: 500,
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.bright,
  },
  td: {
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    color: chat.text,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: chat.line,
  },
  hr: {
    marginTop: '1.5rem',
    marginBottom: '1.5rem',
    borderWidth: 0,
    height: '1px',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    backgroundColor: chat.line,
  },
  img: {
    marginTop: '0.75rem',
    marginBottom: '0.75rem',
    maxWidth: '100%',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: chat.line,
  },
  cursor: {
    display: 'inline-block',
    width: '1px',
    height: '14px',
    marginLeft: '0.125rem',
    verticalAlign: 'middle',
    transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionDuration: '700ms',
    backgroundColor: chat.mid,
  },
})
