import * as stylex from '@stylexjs/stylex'

const DISPLAY = '"Fredoka", ui-rounded, "Nunito", system-ui, sans-serif'
const MONO = 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace'
const HOVER = '@media (hover: hover) and (pointer: fine)'

/** Markdown body inside Lim's reply cards (vars from chat/chat.css). */
export const messageContent = stylex.create({
  thinkBlock: {
    marginBottom: '0.75rem',
    paddingBottom: '0.75rem',
    fontSize: '13px',
    fontStyle: 'italic',
    lineHeight: 1.6,
    color: 'var(--chat-mid)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'dashed',
    borderBottomColor: 'var(--chat-line)',
  },
  body: {
    fontSize: '15px',
    lineHeight: 1.62,
    color: 'inherit',
  },
  paragraph: {
    marginTop: 0,
    marginBottom: { default: '0.7rem', ':last-of-type': 0 },
  },
  link: {
    color: 'var(--chat-bright)',
    fontWeight: 500,
    textDecorationLine: 'underline',
    textDecorationThickness: '2px',
    textUnderlineOffset: '3px',
    textDecorationColor: { default: 'var(--chat-accent)', ':hover': 'var(--chat-accent-deep)' },
  },
  strong: { fontWeight: 600, color: 'var(--chat-bright)' },
  em: { fontStyle: 'italic' },
  inlineCode: {
    paddingInline: '0.4em',
    paddingBlock: '0.12em',
    borderRadius: '6px',
    fontFamily: MONO,
    fontSize: '0.86em',
    backgroundColor: 'var(--chat-inline-code-bg)',
    color: 'var(--chat-inline-code-text)',
  },
  blockCode: {
    fontFamily: MONO,
    fontSize: '13px',
    lineHeight: 1.65,
  },
  codeWrap: {
    position: 'relative',
    marginBlock: '0.85rem',
    borderRadius: '16px',
    overflow: 'hidden',
    backgroundColor: 'var(--chat-code-bg)',
    boxShadow: 'inset 0 -3px 0 rgba(0, 0, 0, 0.18), 0 10px 22px -16px rgba(43, 33, 64, 0.7)',
  },
  codeBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    paddingLeft: '14px',
    paddingRight: '4px',
    minHeight: '36px',
    color: 'var(--chat-code-chrome)',
    fontFamily: DISPLAY,
    fontWeight: 500,
    fontSize: '12.5px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(243, 237, 255, 0.08)',
  },
  codeDot: { width: '9px', height: '9px', borderRadius: '50%' },
  codeLang: { marginLeft: '6px', flex: '1 1 auto', textTransform: 'lowercase' },
  codeCopy: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minHeight: '36px',
    paddingInline: '10px',
    borderRadius: '999px',
    borderWidth: 0,
    backgroundColor: { default: 'transparent', ':hover': { default: null, [HOVER]: 'rgba(243, 237, 255, 0.08)' } },
    color: 'var(--chat-code-chrome)',
    fontFamily: DISPLAY,
    fontSize: '12.5px',
    cursor: 'pointer',
    outlineWidth: { default: 0, ':focus-visible': '2px' },
    outlineStyle: { default: 'none', ':focus-visible': 'solid' },
    outlineColor: 'var(--chat-accent-hi)',
  },
  pre: {
    margin: 0,
    paddingBlock: '12px 14px',
    paddingInline: '16px',
    overflowX: 'auto',
    color: 'var(--chat-code-text)',
  },
  ul: { marginBlock: '0.5rem 0.8rem', paddingLeft: '1.3rem', listStyleType: 'disc' },
  ol: { marginBlock: '0.5rem 0.8rem', paddingLeft: '1.4rem', listStyleType: 'decimal' },
  li: {
    marginBottom: '0.3rem',
    paddingLeft: '0.15rem',
    '::marker': { color: 'var(--chat-accent-deep)', fontWeight: 600 },
  },
  blockquote: {
    marginBlock: '0.8rem',
    marginInline: 0,
    paddingBlock: '0.5rem',
    paddingInline: '1rem',
    borderRadius: '12px',
    backgroundColor: 'var(--chat-chip-1)',
    color: 'var(--chat-text)',
  },
  h1: { marginBlock: '0.4rem 0.6rem', fontFamily: DISPLAY, fontWeight: 600, fontSize: '22px', lineHeight: 1.2, color: 'var(--chat-bright)' },
  h2: { marginBlock: '0.9rem 0.5rem', fontFamily: DISPLAY, fontWeight: 600, fontSize: '19px', lineHeight: 1.25, color: 'var(--chat-bright)' },
  h3: { marginBlock: '0.8rem 0.4rem', fontFamily: DISPLAY, fontWeight: 600, fontSize: '17px', lineHeight: 1.3, color: 'var(--chat-bright)' },
  h4: { marginBlock: '0.7rem 0.3rem', fontFamily: DISPLAY, fontWeight: 600, fontSize: '15.5px', color: 'var(--chat-bright)' },
  tableWrap: {
    marginBlock: '0.8rem',
    overflowX: 'auto',
    borderRadius: '12px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--chat-line)',
  },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '14px' },
  thead: { backgroundColor: 'var(--chat-chip-1)' },
  th: { paddingBlock: '8px', paddingInline: '12px', textAlign: 'left', fontWeight: 600 },
  td: {
    paddingBlock: '8px',
    paddingInline: '12px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--chat-line)',
  },
  hr: {
    marginBlock: '1rem',
    borderWidth: 0,
    height: '2px',
    borderRadius: '2px',
    backgroundColor: 'var(--chat-line)',
  },
  img: { maxWidth: '100%', borderRadius: '12px' },
})
