import * as stylex from '@stylexjs/stylex'
const DARK = ':is(.dark) &'

/** Auto-migrated from Tailwind — Ingest */
export const ingest = stylex.create({
  s60c3905b: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#a8a29e",
    "fontVariantNumeric": "tabular-nums",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s5e2dcc92: {
    "marginTop": "0.375rem",
    "color": "#a8a29e",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s45b2f91: {
    "marginTop": "0.375rem",
    "color": "#059669",
    [DARK]: {
      "color": "#34d399",
    },
  },
  sd27c2def: {
    "marginTop": "0.375rem",
    "color": "#e11d48",
    [DARK]: {
      "color": "#fb7185",
    },
  },
  s7b6e21f: {
    "position": "relative",
    "display": "grid",
    "alignItems": "flex-start",
    "gap": "0rem",
  },
  s3dbb69e2: {
    "position": "relative",
    "display": "flex",
    "minWidth": 0,
    "flexDirection": "column",
    "alignItems": "center",
  },
  s601d5945: {
    "position": "relative",
    "zIndex": 10,
  },
  s925ca98e: {
    "display": "flex",
    "flexDirection": "column",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "0.5rem",
    "paddingLeft": "0.25rem",
    "paddingRight": "0.25rem",
    "cursor": "pointer",
    "borderRadius": "0.5rem",
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "rgba(251, 113, 133, 0.5)",
    },
  },
  s54507fff: {
    "pointerEvents": "none",
    "position": "absolute",
    "height": "1px",
  },
  s67a428ff: {
    "display": "block",
    "width": "100%",
  },
  sb5442fec: {
    "position": "relative",
    "display": "inline-flex",
    "height": "2.25rem",
    "flexShrink": 0,
    "alignItems": "center",
    "justifyContent": "center",
  },
  sff280fff: {
    "height": "2.25rem",
  },
  s3c9c4fb0: {
    "position": "relative",
    "height": "1rem",
    "width": "1rem",
  },
  s316e3563: {
    "position": "relative",
    "display": "inline-flex",
    "height": "2.25rem",
    "flexShrink": 0,
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "9999px",
  },
  s2f8a34ed: {
    "height": "1rem",
    "width": "1rem",
    "color": "#b45309",
    [DARK]: {
      "color": "#fcd34d",
    },
  },
  s65702fd3: {
    "position": "relative",
    "display": "inline-flex",
    "height": "2.25rem",
    "flexShrink": 0,
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "9999px",
    "borderWidth": "1px",
    "borderStyle": "dashed",
    "borderColor": "#d6d3d1",
    [DARK]: {
      "borderColor": "#44403c",
      "backgroundColor": "rgba(28, 25, 23, 0.4)",
    },
  },
  sc9b47330: {
    "height": "1rem",
    "width": "1rem",
    "color": "#d6d3d1",
    [DARK]: {
      "color": "#57534e",
    },
  },
  sbbe27b4f: {
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "space-between",
    "gap": "0.5rem",
  },
  s7d1c8b7c: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#78716c",
    "fontVariantNumeric": "tabular-nums",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s4845fba1: {
    "marginTop": "0.5rem",
    "overflowY": "auto",
    "borderRadius": "0.375rem",
    "backgroundColor": "#fafaf9",
    "paddingLeft": "0.5rem",
    "paddingRight": "0.5rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    [DARK]: {
      "backgroundColor": "rgba(12, 10, 9, 0.5)",
    },
  },
  s66529f26: {
    "display": "flex",
    "gap": "0.5rem",
    "color": "11px",
    "lineHeight": 1.375,
  },
  s8d0bd648: {
    "flexShrink": 0,
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#a8a29e",
    "fontVariantNumeric": "tabular-nums",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s21c6c9b2: {
    "marginTop": "0.5rem",
    "color": "#78716c",
    "fontStyle": "italic",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  sbe90b7b4: {
    "color": "#a8a29e",
    "fontWeight": 500,
    "textTransform": "uppercase",
    "letterSpacing": "0.05em",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s56c52d31: {
    "marginTop": "0.25rem",
    "color": "#57534e",
    "lineHeight": 1.625,
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  sddff2b20: {
    "marginTop": "0.5rem",
    "color": "#a8a29e",
    "fontWeight": 500,
    "textTransform": "uppercase",
    "letterSpacing": "0.05em",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s41be442a: {
    "marginTop": "0.25rem",
    "color": "#57534e",
    "lineHeight": 1.375,
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  sb2ddf91a: {
    "display": "flex",
    "gap": "0.375rem",
  },
  s8c22b5ab: {
    "marginTop": "0.25rem",
    "flexShrink": 0,
    "borderRadius": "9999px",
    "backgroundColor": "#f59e0b",
  },
  s619ce5a0: {
    "backgroundColor": "#f5f5f4",
    "paddingLeft": "0.25rem",
    "paddingRight": "0.25rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "color": "#78716c",
    "fontWeight": 500,
    [DARK]: {
      "backgroundColor": "#292524",
      "color": "#a8a29e",
    },
  },
  sd28b0f1b: {
    "marginTop": "0.75rem",
    "borderTopWidth": "1px",
    "borderTopStyle": "solid",
    "borderColor": "#f5f5f4",
    "paddingTop": "0.75rem",
    [DARK]: {
      "borderColor": "#292524",
    },
  },
  s957a7ae7: {
    "display": "flex",
    "width": "100%",
    "alignItems": "center",
    "gap": "0.375rem",
    "textAlign": "left",
    "color": "#44403c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#d6d3d1",
    },
    ":hover": {
      "color": "#f5f5f4",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "rgba(251, 113, 133, 0.4)",
    },
  },
  sfdf42904: {
    "marginTop": "0.5rem",
    
    "display": "flex",
    "flexDirection": "column",
    "gap": "0.75rem",
  },
  se28e8787: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "baseline",
    "columnGap": "0.5rem",
    "rowGap": "0.25rem",
  },
  s129e46b3: {
    "fontWeight": 500,
  },
  s5e96a87d: {
    "color": "#a8a29e",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s1fa2d8e5: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
    "gap": "0.25rem",
  },
  scdb07eaf: {
    "backgroundColor": "#fff1f2",
    "paddingLeft": "0.25rem",
    "paddingRight": "0.25rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "color": "#e11d48",
    "fontWeight": 500,
    [DARK]: {
      "backgroundColor": "rgba(76, 5, 25, 0.3)",
      "color": "#fb7185",
    },
  },
  se5cdcc4: {
    "color": "#78716c",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s9a71eef: {
    "paddingLeft": "0.375rem",
    "paddingRight": "0.375rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "color": "10px",
    "fontWeight": 500,
  },
  s8d4ad146: {
    "color": "#78716c",
    "fontStyle": "italic",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s383450e8: {
    "marginTop": "1rem",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(253, 230, 138, 0.7)",
    "backgroundColor": "rgba(255, 251, 235, 0.6)",
    "padding": "1rem",
  },
  se99caec9: {
    "display": "flex",
    "alignItems": "flex-start",
    "gap": "0.5rem",
  },
  s3e844809: {
    "marginTop": "0.125rem",
    "flexShrink": 0,
    "color": "#f59e0b",
  },
  se30fd43e: {
    "minWidth": 0,
    "flex": "1 1 0%",
  },
  sdc6c05d2: {
    "color": "13px",
    "fontWeight": 600,
    [DARK]: {
      "color": "#fcd34d",
    },
  },
  s1a9a112b: {
    "marginTop": "0.125rem",
    "color": "#57534e",
    "lineHeight": 1.625,
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  s7fb1db58: {
    "marginTop": "0.5rem",
    "color": "#57534e",
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  s8e209a8a: {
    "fontWeight": 500,
    "color": "#78716c",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s64ff6eb: {
    "marginTop": "0.5rem",
  },
  s1512038a: {
    "cursor": "pointer",
    "color": "#78716c",
    "fontWeight": 500,
    "textTransform": "uppercase",
    "letterSpacing": "0.025em",
    [DARK]: {
      "color": "#a8a29e",
    },
    ":hover": {
      "color": "#e7e5e4",
    },
  },
  s8131c145: {
    "marginTop": "0.375rem",
    "overflowWrap": "anywhere",
    "wordBreak": "break-word",
    "borderRadius": "0.375rem",
    "paddingLeft": "0.625rem",
    "paddingRight": "0.625rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "color": "#44403c",
    "lineHeight": 1.625,
    [DARK]: {
      "backgroundColor": "rgba(28, 25, 23, 0.4)",
      "color": "#e7e5e4",
    },
  },
  se4f7be31: {
    "marginTop": "0.75rem",
    "borderRadius": "0.75rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(231, 229, 228, 0.6)",
    [DARK]: {
      "borderColor": "rgba(41, 37, 36, 0.6)",
    },
  },
  sb4069d98: {
    "cursor": "pointer",
    "userSelect": "none",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "color": "#57534e",
    "fontWeight": 500,
    [DARK]: {
      "color": "#a8a29e",
    },
    ":hover": {
      "color": "#e7e5e4",
    },
  },
  sd788321b: {
    "overflowY": "auto",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "11px",
  },
  s9109cdbf: {
    "display": "flex",
    "gap": "0.5rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
  },
  sa8e02460: {
    "flexShrink": 0,
    "color": "#a8a29e",
  },
  sf5facc2b: {
    "color": "#44403c",
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  s28353d49: {
    "position": "relative",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(231, 229, 228, 0.8)",
    "padding": "1.25rem",
    [DARK]: {
      "borderColor": "rgba(41, 37, 36, 0.8)",
      "backgroundColor": "rgba(28, 25, 23, 0.6)",
    },
  },
  s17bea155: {
    "position": "absolute",
    "left": 0,
    "right": 0,
    "top": 0,
    "overflow": "hidden",
  },
  s71b5dc26: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "flex-start",
    "justifyContent": "space-between",
    "rowGap": "0.5rem",
  },
  se164d5a4: {
    "minWidth": 0,
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#57534e",
    "textUnderlineOffset": "2px",
    [DARK]: {
      "color": "#a8a29e",
    },
    ":hover": {
      "color": "#fb7185",
      "textDecorationLine": "underline",
    },
  },
  s33458e: {
    "marginTop": "1rem",
  },
  s91675395: {
    "marginTop": "0.75rem",
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#a8a29e",
    [DARK]: {
      "color": "#78716c",
    },
  },
  sc0b07296: {
    "marginLeft": "0.375rem",
    "marginRight": "0.375rem",
  },
  s72e92e25: {
    "marginTop": "0.5rem",
    "overflowWrap": "anywhere",
    "wordBreak": "break-word",
    "borderRadius": "0.5rem",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "color": "12px",
  },
  sc5c56bbb: {
    "fontWeight": 600,
    "textTransform": "capitalize",
  },
  sb3307e52: {
    "marginTop": "0.75rem",
    "display": "flex",
    "alignItems": "center",
    "gap": "0.75rem",
  },
  s69cd3a8a: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.375rem",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#fecdd3",
    "backgroundColor": "#fff1f2",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#be123c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "rgba(136, 19, 55, 0.4)",
      "backgroundColor": "rgba(76, 5, 25, 0.4)",
      "color": "#fda4af",
    },
    ":hover": {
      "backgroundColor": "rgba(136, 19, 55, 0.4)",
    },
  },
  s70ee951d: {
    "color": "11px",
  },
  sab856c4d: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.375rem",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#e7e5e4",
    "backgroundColor": "#fafaf9",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#44403c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "#44403c",
      "backgroundColor": "#1c1917",
      "color": "#d6d3d1",
    },
    ":hover": {
      "backgroundColor": "#292524",
    },
  },
  s102510f7: {
    "marginLeft": "auto",
    "marginRight": "auto",
    "paddingLeft": "1.25rem",
    "paddingRight": "1.25rem",
    "paddingTop": "4rem",
    "paddingBottom": "4rem",
  },
  s37f7dc96: {
    "fontFamily": "\"Cormorant Garamond\", Georgia, serif",
    "fontSize": "1.875rem",
    "color": "#1c1917",
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  sb5cebbd6: {
    "marginTop": "1.5rem",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "padding": "1.25rem",
    "color": "#292524",
    [DARK]: {
      "color": "#e7e5e4",
    },
  },
  sb09a9ba6: {
    "fontWeight": 600,
  },
  s3f2691cc: {
    "marginTop": "0.5rem",
    "color": "13px",
    "lineHeight": 1.625,
  },
  sd81d42ba: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "12px",
  },
  s6876764d: {
    "marginTop": "0.75rem",
    "color": "13px",
    "lineHeight": 1.625,
  },
  s62c182b1: {
    "fontWeight": 600,
  },
  sc0a5fd9d: {
    "marginLeft": "auto",
    "marginRight": "auto",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "paddingTop": "3rem",
    "paddingBottom": "3rem",
    "@media (min-width: 640px)": {
      "paddingTop": "4rem",
      "paddingBottom": "4rem",
    },
  },
  s9a3eba28: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "flex-start",
    "justifyContent": "space-between",
    "rowGap": "0.5rem",
  },
  s3ac16245: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#78716c",
    "textTransform": "uppercase",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s8cb1089a: {
    "color": "#e11d48",
    [DARK]: {
      "color": "#fb7185",
    },
  },
  s887d0ab: {
    "marginLeft": "0.5rem",
    "marginRight": "0.5rem",
    "height": "1px",
    "width": "2rem",
    "backgroundColor": "#d6d3d1",
    [DARK]: {
      "backgroundColor": "#44403c",
    },
  },
  sc2eed480: {
    "marginTop": "0.5rem",
    "fontFamily": "\"Cormorant Garamond\", Georgia, serif",
    "color": "#1c1917",
    "fontWeight": 500,
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  sc3862c91: {
    "marginTop": "0.5rem",
    "fontSize": "0.875rem",
    "color": "#57534e",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s86ff3e6: {
    "display": "flex",
    "alignItems": "center",
    "gap": "1rem",
  },
  sa06248c6: {
    "color": "#a8a29e",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#78716c",
    },
    ":hover": {
      "color": "#fb7185",
    },
  },
  sca78bd76: {
    "marginTop": "0.75rem",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "color": "12px",
  },
  s15d69e19: {
    "marginTop": "0.125rem",
    "lineHeight": 1.625,
  },
  sf8d576c5: {
    "marginTop": "0.5rem",
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.5rem",
    "borderRadius": "0.375rem",
    "backgroundColor": "#fffbeb",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#b45309",
    [DARK]: {
      "color": "#fcd34d",
    },
  },
  s30736863: {
    "height": "0.75rem",
    "width": "0.75rem",
  },
  sa377ca47: {
    "marginTop": "2rem",
    "borderBottomWidth": "1px",
    "borderBottomStyle": "solid",
    "borderColor": "rgba(231, 229, 228, 0.8)",
    [DARK]: {
      "borderColor": "rgba(41, 37, 36, 0.8)",
    },
  },
  s334592: {
    "marginTop": "2rem",
  },
  s720eeac6: {
    "display": "block",
    "color": "#44403c",
    "fontWeight": 500,
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  s8b950f29: {
    "marginTop": "0.5rem",
    "display": "flex",
    "gap": "0.75rem",
  },
  se37e4925: {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "0.5rem",
    "borderRadius": "0.75rem",
    "backgroundColor": "#f43f5e",
    "paddingLeft": "1.25rem",
    "paddingRight": "1.25rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "color": "13px",
    "fontWeight": 500,
    "outlineStyle": "none",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "backgroundColor": "#f43f5e",
    },
    ":hover": {
      "backgroundColor": "#fb7185",
    },
    ":focus-visible": {
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "rgba(244, 63, 94, 0.4)",
    },
  },
  sd6e31421: {
    "height": "1rem",
    "width": "1rem",
  },
  sbaf3bbab: {
    "marginTop": "0.375rem",
    "color": "12px",
  },
  s5b3b4528: {
    "marginTop": "0.75rem",
    "display": "inline-flex",
    "cursor": "pointer",
    "alignItems": "center",
    "gap": "0.5rem",
    "color": "#57534e",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  sc985d42d: {
    "height": "1rem",
    "width": "1rem",
    "flexShrink": 0,
    "borderColor": "#d6d3d1",
    [DARK]: {
      "borderColor": "#44403c",
    },
    ":focus-visible": {
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "rgba(251, 113, 133, 0.4)",
    },
  },
  sfcabccd8: {
    "marginTop": "0.375rem",
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
    "gap": "0.5rem",
  },
  sbe9cad21: {
    "color": "#e11d48",
    [DARK]: {
      "color": "#fb7185",
    },
  },
  se4d80143: {
    "color": "#059669",
    [DARK]: {
      "color": "#34d399",
    },
  },
  s9f3aba83: {
    "display": "inline-flex",
    "alignItems": "center",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#e7e5e4",
    "backgroundColor": "#fafaf9",
    "paddingLeft": "0.625rem",
    "paddingRight": "0.625rem",
    "paddingTop": "0.25rem",
    "paddingBottom": "0.25rem",
    "color": "#44403c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "#44403c",
      "backgroundColor": "#1c1917",
      "color": "#d6d3d1",
    },
    ":hover": {
      "backgroundColor": "#292524",
    },
  },
  s803c2c94: {
    "display": "inline-flex",
    "alignItems": "center",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#fecdd3",
    "backgroundColor": "#fff1f2",
    "paddingLeft": "0.625rem",
    "paddingRight": "0.625rem",
    "paddingTop": "0.25rem",
    "paddingBottom": "0.25rem",
    "color": "#be123c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "rgba(136, 19, 55, 0.4)",
      "backgroundColor": "rgba(76, 5, 25, 0.4)",
      "color": "#fda4af",
    },
    ":hover": {
      "backgroundColor": "rgba(136, 19, 55, 0.4)",
    },
  },
  s6356c07: {
    "marginTop": "3rem",
  },
  s84bb96bf: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#78716c",
    "textTransform": "uppercase",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s4c78f04e: {
    "marginLeft": "0.5rem",
    "marginRight": "0.5rem",
    "color": "#d6d3d1",
    [DARK]: {
      "color": "#44403c",
    },
  },
  s27bd8e87: {
    "marginTop": "1rem",
    
    "display": "flex",
    "flexDirection": "column",
    "gap": "1rem",
  },
  s71e7957: {
    "display": "flex",
    "flexDirection": "column",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "0.5rem",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "dashed",
    "borderColor": "#e7e5e4",
    "backgroundColor": "rgba(250, 250, 249, 0.6)",
    "paddingLeft": "1.5rem",
    "paddingRight": "1.5rem",
    "paddingTop": "2.5rem",
    "paddingBottom": "2.5rem",
    "textAlign": "center",
    [DARK]: {
      "borderColor": "#292524",
      "backgroundColor": "rgba(28, 25, 23, 0.3)",
    },
  },
  sa05ecb46: {
    "color": "#78716c",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  sc42b4b05: {
    "color": "#a8a29e",
    [DARK]: {
      "color": "#57534e",
    },
  },
  s6356c05: {
    "marginTop": "2.5rem",
  },
  s3a8a013f: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#a8a29e",
    "textTransform": "uppercase",
    [DARK]: {
      "color": "#57534e",
    },
  },
  s6021228b: {
    "color": "#a8a29e",
    [DARK]: {
      "color": "#57534e",
    },
  },
  statusPillBase: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: '9999px',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '11px',
    fontWeight: 500,
  },
  statusPending: { backgroundColor: '#f5f5f4', color: '#57534e', [DARK]: { backgroundColor: '#292524', color: '#a8a29e' } },
  statusRunning: { backgroundColor: '#fff1f2', color: '#be123c', [DARK]: { backgroundColor: 'rgba(76, 5, 25, 0.4)', color: '#fda4af' } },
  statusDone: { backgroundColor: '#ecfdf5', color: '#047857', [DARK]: { backgroundColor: 'rgba(2, 44, 34, 0.4)', color: '#34d399' } },
  statusFailed: { backgroundColor: '#fffbeb', color: '#b45309', [DARK]: { backgroundColor: 'rgba(69, 26, 3, 0.4)', color: '#fcd34d' } },
  statusDead: { backgroundColor: '#fef2f2', color: '#b91c1c', [DARK]: { backgroundColor: 'rgba(69, 10, 10, 0.4)', color: '#fca5a5' } },
  stepLabelPast: { whiteSpace: 'nowrap', fontSize: '10px', lineHeight: 1, letterSpacing: '0.025em', fontWeight: 500, color: '#b45309', [DARK]: { color: '#fcd34d' } },
  stepLabelCurrent: { whiteSpace: 'nowrap', fontSize: '10px', lineHeight: 1, letterSpacing: '0.025em', fontWeight: 600, color: '#e11d48', [DARK]: { color: '#fb7185' } },
  stepLabelErrored: { whiteSpace: 'nowrap', fontSize: '10px', lineHeight: 1, letterSpacing: '0.025em', fontWeight: 600, color: '#dc2626', [DARK]: { color: '#f87171' } },
  stepLabelFuture: { whiteSpace: 'nowrap', fontSize: '10px', lineHeight: 1, letterSpacing: '0.025em', fontWeight: 500, color: '#78716c', [DARK]: { color: '#a8a29e' } },
  stepPopover: {
    position: 'absolute',
    left: '50%',
    top: 'calc(100% + 10px)',
    zIndex: 30,
    width: '18rem',
    transform: 'translateX(-50%)',
    borderRadius: '0.75rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(231, 229, 228, 0.8)',
    backgroundColor: '#ffffff',
    padding: '0.75rem',
    textAlign: 'left',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    transitionProperty: 'opacity',
    transitionDuration: '150ms',
    [DARK]: { borderColor: 'rgba(68, 64, 60, 0.8)', backgroundColor: '#1c1917' },
  },
  stepPopoverOpen: { opacity: 1, pointerEvents: 'auto' },
  stepPopoverClosed: { opacity: 0, pointerEvents: 'none' },
  pipelineRim: { position: 'absolute', inset: 0, borderRadius: '9999px', backgroundColor: 'rgba(244, 63, 94, 0.3)' },
  pipelineBreath: { position: 'absolute', inset: '3px', borderRadius: '9999px' },
  stateLabelCurrent: { fontSize: '10px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#be123c', [DARK]: { color: '#fda4af' } },
  stateLabelPast: { fontSize: '10px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#047857', [DARK]: { color: '#34d399' } },
  stateLabelErrored: { fontSize: '10px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#b91c1c', [DARK]: { color: '#f87171' } },
  stateLabelFuture: { fontSize: '10px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#78716c', [DARK]: { color: '#a8a29e' } },
  logMsgError: { overflowWrap: 'anywhere', wordBreak: 'break-word', color: '#b91c1c', [DARK]: { color: '#f87171' } },
  logMsgWarn: { overflowWrap: 'anywhere', wordBreak: 'break-word', color: '#b45309', [DARK]: { color: '#fcd34d' } },
  logMsgInfo: { overflowWrap: 'anywhere', wordBreak: 'break-word', color: '#44403c', [DARK]: { color: '#e7e5e4' } },
  stepInfoDivider: { marginTop: '0.5rem', borderTopWidth: '1px', borderTopStyle: 'solid', borderColor: 'rgba(231, 229, 228, 0.6)', paddingTop: '0.5rem', [DARK]: { borderColor: 'rgba(68, 64, 60, 0.6)' } },
  stepInfoPlain: { marginTop: '0.5rem' },
  confHigh: { borderRadius: '0.25rem', paddingLeft: '0.25rem', paddingRight: '0.25rem', paddingTop: '0.125rem', paddingBottom: '0.125rem', fontSize: '10px', fontWeight: 500, backgroundColor: '#ecfdf5', color: '#047857', [DARK]: { backgroundColor: 'rgba(2, 44, 34, 0.3)', color: '#34d399' } },
  confMedium: { borderRadius: '0.25rem', paddingLeft: '0.25rem', paddingRight: '0.25rem', paddingTop: '0.125rem', paddingBottom: '0.125rem', fontSize: '10px', fontWeight: 500, backgroundColor: '#fffbeb', color: '#b45309', [DARK]: { backgroundColor: 'rgba(69, 26, 3, 0.3)', color: '#fbbf24' } },
  confLow: { borderRadius: '0.25rem', paddingLeft: '0.25rem', paddingRight: '0.25rem', paddingTop: '0.125rem', paddingBottom: '0.125rem', fontSize: '10px', fontWeight: 500, backgroundColor: '#f5f5f4', color: '#78716c', [DARK]: { backgroundColor: '#292524', color: '#a8a29e' } },
  chevron: { height: '0.875rem', width: '0.875rem', flexShrink: 0, color: '#a8a29e', transitionProperty: 'transform', transitionDuration: '200ms' },
  chevronOpen: { transform: 'rotate(90deg)' },
  placeRow: { position: 'relative', display: 'flex', flexDirection: 'column', gap: '0.25rem', fontSize: '13px', color: '#44403c', [DARK]: { color: '#d6d3d1' } },
  placeRowEmerge: { borderRadius: '0.5rem', paddingLeft: '0.5rem', paddingRight: '0.5rem', paddingTop: '0.375rem', paddingBottom: '0.375rem', borderWidth: '1px', borderStyle: 'solid', borderColor: 'rgba(253, 164, 175, 0.7)', [DARK]: { borderColor: 'rgba(244, 63, 94, 0.4)' } },
  logStepError: { flexShrink: 0, textTransform: 'uppercase', letterSpacing: '0.025em', color: '#dc2626', [DARK]: { color: '#f87171' } },
  logStepWarn: { flexShrink: 0, textTransform: 'uppercase', letterSpacing: '0.025em', color: '#d97706', [DARK]: { color: '#fbbf24' } },
  logStepInfo: { flexShrink: 0, textTransform: 'uppercase', letterSpacing: '0.025em', color: '#be123c', [DARK]: { color: '#fb7185' } },
  sweepBar: { height: '100%', width: '33.333333%', backgroundImage: 'linear-gradient(to right, transparent, #f43f5e, transparent)' },
  etaDone: { marginLeft: '0.5rem', borderRadius: '9999px', paddingLeft: '0.5rem', paddingRight: '0.5rem', paddingTop: '0.125rem', paddingBottom: '0.125rem', fontSize: '11px', fontWeight: 500, backgroundColor: '#ecfdf5', color: '#047857', [DARK]: { backgroundColor: 'rgba(2, 44, 34, 0.3)', color: '#34d399' } },
  etaSlow: { marginLeft: '0.5rem', borderRadius: '9999px', paddingLeft: '0.5rem', paddingRight: '0.5rem', paddingTop: '0.125rem', paddingBottom: '0.125rem', fontSize: '11px', fontWeight: 500, backgroundColor: '#fffbeb', color: '#b45309', [DARK]: { backgroundColor: 'rgba(69, 26, 3, 0.3)', color: '#fcd34d' } },
  etaDefault: { marginLeft: '0.5rem', borderRadius: '9999px', paddingLeft: '0.5rem', paddingRight: '0.5rem', paddingTop: '0.125rem', paddingBottom: '0.125rem', fontSize: '11px', fontWeight: 500, backgroundColor: '#fff1f2', color: '#be123c', [DARK]: { backgroundColor: 'rgba(76, 5, 25, 0.3)', color: '#fb7185' } },
  urlInputBase: {
    minHeight: '44px',
    flex: '1 1 0%',
    borderRadius: '0.75rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    backgroundColor: '#ffffff',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '13px',
    color: '#1c1917',
    outline: 'none',
    transitionProperty: 'border-color, box-shadow, opacity',
    transitionDuration: '150ms',
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid' },
    ':disabled': { opacity: 0.6 },
    '::placeholder': { color: '#a8a29e' },
    [DARK]: {
      backgroundColor: '#1c1917',
      color: '#f5f5f4',
      '::placeholder': { color: '#57534e' },
    },
  },
  urlInputValid: {
    borderColor: '#d6d3d1',
    ':focus-visible': { borderColor: '#fb7185', boxShadow: '0 0 0 2px rgba(251, 113, 133, 0.2)' },
    [DARK]: {
      borderColor: '#44403c',
      ':focus-visible': { borderColor: '#f43f5e', boxShadow: '0 0 0 2px rgba(244, 63, 94, 0.2)' },
    },
  },
  urlInputInvalid: {
    borderColor: '#fb7185',
    ':focus-visible': { borderColor: '#f43f5e', boxShadow: '0 0 0 2px rgba(251, 113, 133, 0.3)' },
    [DARK]: {
      borderColor: 'rgba(244, 63, 94, 0.7)',
      ':focus-visible': { borderColor: '#f43f5e', boxShadow: '0 0 0 2px rgba(244, 63, 94, 0.3)' },
    },
  },

})
