import * as stylex from '@stylexjs/stylex'
const DARK = ':is(.dark) &'

/** Auto-migrated from Tailwind — MapModeOverlay */
export const mapModeOverlay = stylex.create({
  s345db97d: {
    "position": "fixed",
    "inset": 0,
    "zIndex": 50,
    "backgroundColor": "#F5F2ED",
    [DARK]: {
      "backgroundColor": "#171613",
    },
  },
  se24793b7: {
    "position": "absolute",
    "left": 0,
    "right": 0,
    "top": 0,
    "zIndex": 30,
    "display": "flex",
    "alignItems": "center",
    "gap": "0.5rem",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "@media (min-width: 640px)": {
      "paddingLeft": "1rem",
      "paddingRight": "1rem",
    },
  },
  sd4c00337: {
    "display": "flex",
    "minWidth": 0,
    "flex": "1 1 0%",
    "alignItems": "center",
    "gap": "0.5rem",
    "borderRadius": "9999px",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(28,25,23,0.08)",
    "backgroundColor": "rgba(255,254,250,0.88)",
    "paddingLeft": "0.375rem",
    "paddingRight": "0.375rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "boxShadow": "0_8px_28px_rgba(28,25,23,0.08)",
    "backdropFilter": "blur(24px)",
    [DARK]: {
      "borderColor": "rgba(255,252,245,0.06)",
      "backgroundColor": "rgba(28,25,23,0.78)",
    },
  },
  s4ea8f36a: {
    "display": "inline-flex",
    "height": "2.5rem",
    "width": "2.5rem",
    "flexShrink": 0,
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "9999px",
    "color": "#44403c",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#d6d3d1",
    },
    ":hover": {
      "backgroundColor": "rgba(41, 37, 36, 0.8)",
      "color": "#fecdd3",
    },
    ":focus-visible": {

    },
  },
  scd3f3ccd: {
    "height": "1rem",
    "width": "1rem",
  },
  s2adb611: {
    "minWidth": 0,
    "flex": "1 1 0%",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "paddingRight": "0.25rem",
  },
  saf8611dc: {
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "whiteSpace": "nowrap",
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#78716c",
    "textTransform": "uppercase",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  sbeb68a49: {
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "whiteSpace": "nowrap",
    "fontSize": "0.875rem",
    "fontWeight": 500,
    "letterSpacing": "-0.025em",
    "color": "#1c1917",
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  s3cfc74a5: {
    "display": "inline-flex",
    "height": "2.5rem",
    "width": "2.5rem",
    "flexShrink": 0,
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "9999px",
    "color": "#44403c",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#d6d3d1",
    },
    ":hover": {
      "backgroundColor": "rgba(41, 37, 36, 0.8)",
      "color": "#fecdd3",
    },
    ":focus-visible": {

    },
  },
  sd6e31421: {
    "height": "1rem",
    "width": "1rem",
  },
  s46cef117: {
    "marginRight": "0.125rem",
    "display": "inline-flex",
    "height": "2.5rem",
    "flexShrink": 0,
    "overflow": "hidden",
    "borderRadius": "9999px",
    "backgroundColor": "rgba(245, 245, 244, 0.9)",
    "padding": "0.125rem",
    "fontSize": "0.75rem",
    "fontWeight": 500,
    [DARK]: {
      "backgroundColor": "rgba(41, 37, 36, 0.9)",
    },
  },
  sd2d12d59: {

  },
  sfbd03cc3: {
    "display": "none",
    "@media (min-width: 640px)": {

    },
  },
  s561318c: {
    "position": "absolute",
    "inset": 0,
    "overflow": "hidden",
  },
  sb443287f: {
    "position": "absolute",
    "inset": 0,
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
    "paddingLeft": "1.5rem",
    "paddingRight": "1.5rem",
  },
  s19572226: {
    "maxWidth": "24rem",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(28,25,23,0.08)",
    "backgroundColor": "rgba(255,254,250,0.94)",
    "padding": "1.25rem",
    "textAlign": "center",
    "boxShadow": "0_16px_40px_rgba(28,25,23,0.12)",
    "backdropFilter": "blur(24px)",
    [DARK]: {
      "borderColor": "rgba(255,252,245,0.06)",
      "backgroundColor": "rgba(28,25,23,0.9)",
    },
  },
  sec444a31: {
    "fontSize": "0.875rem",
    "fontWeight": 500,
    "color": "#1c1917",
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  s7aed520f: {
    "marginTop": "0.25rem",
    "fontSize": "0.75rem",
    "lineHeight": 1.625,
    "color": "#78716c",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s3482676e: {
    "marginTop": "1rem",
    "display": "inline-flex",
    "height": "2.5rem",
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "9999px",
    "backgroundColor": "#e11d48",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "fontSize": "0.75rem",
    "fontWeight": 600,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    ":hover": {
      "backgroundColor": "#f43f5e",
    },
    ":focus-visible": {

    },
  },
  sad3ffd66: {
    "position": "absolute",
    "left": 0,
    "right": 0,
    "zIndex": 20,
    "display": "flex",
    "justifyContent": "center",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
  },
  sa542e252: {
    "borderRadius": "9999px",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(28,25,23,0.08)",
    "backgroundColor": "rgba(255,254,250,0.92)",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#57534e",
    "fontWeight": 500,
    "boxShadow": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    [DARK]: {
      "borderColor": "rgba(255,252,245,0.06)",
      "backgroundColor": "rgba(28,25,23,0.85)",
      "color": "#d6d3d1",
    },
  },
  sac40d5d7: {
    "position": "absolute",
    "inset": 0,
  },
  s12455b86: {
    "position": "absolute",
    "zIndex": 20,
    "display": "flex",
    "flexDirection": "column",
    "gap": "0.5rem",
  },
  sf5aad4e: {
    "pointerEvents": "none",
    "position": "absolute",
    "inset": 0,
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
  },
  sa824fab5: {
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(28,25,23,0.08)",
    "backgroundColor": "rgba(255,254,250,0.92)",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "paddingTop": "0.75rem",
    "paddingBottom": "0.75rem",
    "textAlign": "center",
    "fontSize": "0.875rem",
    "color": "#44403c",
    "boxShadow": "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
    [DARK]: {
      "borderColor": "rgba(255,252,245,0.06)",
      "backgroundColor": "rgba(28,25,23,0.9)",
      "color": "#d6d3d1",
    },
  },
  sda62083a: {
    "pointerEvents": "auto",
    "marginLeft": "0.5rem",
    "color": "#be123c",
    "textDecorationLine": "underline",
    "textDecorationColor": "rgba(244, 63, 94, 0.4)",
    [DARK]: {
      "color": "#fda4af",
    },
    ":hover": {
      "textDecorationColor": "#f43f5e",
    },
  },
  s1f14f665: {
    "position": "absolute",
    "inset": 0,
    "overflowY": "auto",
  },
  sfec139cc: {
    "display": "flex",
    "alignItems": "center",
    "gap": "0.5rem",
    "color": "#44403c",
    "fontWeight": 500,
    [DARK]: {
      "color": "#e7e5e4",
    },
  },
  s69759352: {
    "flexShrink": 0,
    "color": "#78716c",
  },
  s9d0eb0d6: {
    "position": "relative",
    "display": "flex",
    "flexShrink": 0,
  },
  se3364330: {
    "display": "none",
    "height": "0.75rem",
    "width": "0.75rem",
    "flexShrink": 0,
    "@media (min-width: 640px)": {

    },
  },
  s6e724d66: {
    "overflow": "hidden",
    "textOverflow": "ellipsis",
    "whiteSpace": "nowrap",
  },
  s9433f1dd: {
    "position": "absolute",
    "inset": 0,
    "display": "flex",
    "alignItems": "center",
    "justifyContent": "center",
  },
  s908b93a5: {
    "position": "relative",
    "display": "flex",
    "alignItems": "center",
    "gap": "0.5rem",
    "borderRadius": "9999px",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(28,25,23,0.08)",
    "backgroundColor": "rgba(255,254,250,0.92)",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "paddingTop": "0.625rem",
    "paddingBottom": "0.625rem",
    "fontSize": "0.75rem",
    "fontWeight": 500,
    "color": "#44403c",
    "boxShadow": "0_8px_28px_rgba(28,25,23,0.1)",
    "backdropFilter": "blur(24px)",
    [DARK]: {
      "borderColor": "rgba(255,252,245,0.06)",
      "backgroundColor": "rgba(28,25,23,0.88)",
      "color": "#d6d3d1",
    },
  },
  sd8ed5a0d: {
    "color": "#e11d48",
  },
  controlBtn: {
    display: 'inline-flex',
    height: '2.75rem',
    width: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(28, 25, 23, 0.08)',
    backgroundColor: 'rgba(255, 254, 250, 0.88)',
    color: '#44403c',
    boxShadow: '0 8px 24px rgba(28, 25, 23, 0.1)',
    backdropFilter: 'blur(24px)',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '150ms',
    ':hover': { color: '#be123c' },
    [DARK]: { ':hover': { color: '#fecdd3' } },
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid', outlineOffset: '2px', outlineColor: 'rgba(244, 63, 94, 0.6)' },
    [DARK]: { borderColor: 'rgba(255, 252, 245, 0.06)', backgroundColor: 'rgba(28, 25, 23, 0.78)', color: '#d6d3d1' },
  },
  birdsEyeActive: {
    display: 'inline-flex',
    height: '2.75rem',
    width: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    backgroundColor: '#e11d48',
    color: '#ffffff',
    boxShadow: '0 8px 24px rgba(244, 63, 94, 0.35)',
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
    ':hover': { backgroundColor: '#f43f5e' },
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid', outlineOffset: '2px', outlineColor: 'rgba(244, 63, 94, 0.6)' },
  },
  viewModeBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    borderRadius: '9999px',
    paddingLeft: '0.625rem',
    paddingRight: '0.625rem',
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid', outlineOffset: '2px', outlineColor: 'rgba(244, 63, 94, 0.6)' },
  },
  viewModeActive: { backgroundColor: '#e11d48', color: '#ffffff', boxShadow: '0 1px 2px rgba(28, 25, 23, 0.05)' },
  viewModeInactive: { color: '#57534e', ':hover': { color: '#1c1917' },
    [DARK]: { ':hover': { color: '#f5f5f4' } }, [DARK]: { color: '#a8a29e' } },
  locPill: {
    pointerEvents: 'auto',
    position: 'absolute',
    left: '50%',
    zIndex: 10,
    maxWidth: 'min(20rem, 70vw)',
    transform: 'translateX(-50%)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(28, 25, 23, 0.08)',
    backgroundColor: 'rgba(255, 254, 250, 0.9)',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    textAlign: 'left',
    boxShadow: '0 8px 24px rgba(28, 25, 23, 0.1)',
    backdropFilter: 'blur(24px)',
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
    ':hover': { backgroundColor: 'rgba(255, 254, 250, 0.98)' },
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid', outlineOffset: '2px', outlineColor: 'rgba(244, 63, 94, 0.6)' },
    [DARK]: { borderColor: 'rgba(255, 252, 245, 0.06)', backgroundColor: 'rgba(28, 25, 23, 0.82)' },
    [DARK]: { ':hover': { backgroundColor: 'rgba(28, 25, 23, 0.92)' } },
  },
  locPillRound: { borderRadius: '9999px' },
  locPillCard: { borderRadius: '1rem' },
  locPing: { position: 'absolute', display: 'inline-flex', height: '100%', width: '100%', borderRadius: '9999px', opacity: 0.6 },
  locPingRose: { backgroundColor: '#f43f5e' },
  locPingAmber: { backgroundColor: '#f59e0b' },
  locDot: { position: 'relative', display: 'inline-flex', height: '0.5rem', width: '0.5rem', borderRadius: '9999px' },
  locDotRose: { backgroundColor: '#e11d48' },
  locDotAmber: { backgroundColor: '#f59e0b' },

})
