import * as stylex from '@stylexjs/stylex'
const DARK = ':is(.dark) &'

/** Auto-migrated from Tailwind — MapModeFilterBar */
export const mapModeFilterBar = stylex.create({
  se7e9cd2a: {
    "pointerEvents": "none",
    "position": "absolute",
    "left": 0,
    "right": 0,
    "zIndex": 20,
    "display": "flex",
    "justifyContent": "center",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
  },
  s3c9fde5a: {
    "pointerEvents": "auto",
    "display": "flex",
    "alignItems": "center",
    "gap": "0.375rem",
    "overflowX": "auto",
    "touchAction": "pan-x",
    "borderRadius": "9999px",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(28,25,23,0.08)",
    "backgroundColor": "rgba(255,254,250,0.88)",
    "paddingLeft": "0.5rem",
    "paddingRight": "0.5rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "boxShadow": "0_8px_28px_rgba(28,25,23,0.08)",
    "backdropFilter": "blur(24px)",
    [DARK]: {
      "borderColor": "rgba(255,252,245,0.06)",
      "backgroundColor": "rgba(28,25,23,0.78)",
    },
    "@media (min-width: 640px)": {

    },
  },
  se5124f8: {
    "height": "0.75rem",
    "width": "0.75rem",
    "flexShrink": 0,
    "opacity": 0.9,
  },
  se2d7d07e: {
    "fontVariantNumeric": "tabular-nums",
    "opacity": 0.7,
  },
  sfc1c62a2: {
    "marginLeft": "0.125rem",
    "marginRight": "0.125rem",
    "height": "1.25rem",
    "width": "1px",
    "flexShrink": 0,
    "backgroundColor": "rgba(214, 211, 209, 0.8)",
    [DARK]: {
      "backgroundColor": "#44403c",
    },
  },
  s96c27eec: {
    "textTransform": "capitalize",
  },
  sbaaf3ae1: {
    "marginLeft": "0.25rem",
    "fontVariantNumeric": "tabular-nums",
    "opacity": 0.7,
  },
  chipFocus: {},
  resetChip: {
    flexShrink: 0,
    borderRadius: '9999px',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    fontSize: '11px',
    fontWeight: 600,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid', outlineOffset: '2px', outlineColor: 'rgba(244, 63, 94, 0.6)' },
  },
  resetActive: { backgroundColor: '#e11d48', color: '#ffffff', boxShadow: '0 1px 2px rgba(28, 25, 23, 0.05)' },
  resetInactive: {
    backgroundColor: 'rgba(245, 245, 244, 0.9)',
    color: '#44403c',
    ':hover': { backgroundColor: 'rgba(231, 229, 228, 0.9)' },
    [DARK]: {
      backgroundColor: '#292524',
      color: '#d6d3d1',
      ':hover': { backgroundColor: '#44403c' },
    },
  },
  filterChip: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.25rem',
    borderRadius: '9999px',
    paddingLeft: '0.625rem',
    paddingRight: '0.625rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    fontSize: '11px',
    fontWeight: 500,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    ':focus-visible': { outlineWidth: '2px', outlineStyle: 'solid', outlineOffset: '2px', outlineColor: 'rgba(244, 63, 94, 0.6)' },
  },
  filterChipOn: { color: '#ffffff', boxShadow: '0 1px 2px rgba(28, 25, 23, 0.05)' },
  filterChipOff: {
    backgroundColor: 'rgba(245, 245, 244, 0.9)',
    color: '#78716c',
    ':hover': { backgroundColor: 'rgba(231, 229, 228, 0.9)' },
    [DARK]: {
      backgroundColor: '#292524',
      color: '#a8a29e',
      ':hover': { backgroundColor: '#44403c' },
    },
  },
  busynessTransparent: { backgroundColor: 'transparent', color: 'inherit' },
  categoryChipOn: {
    backgroundColor: '#1c1917',
    color: '#ffffff',
    [DARK]: { backgroundColor: '#f5f5f4', color: '#1c1917' },
  },
})
