import * as stylex from '@stylexjs/stylex'
const DARK = ':is(.dark) &'

/** Auto-migrated from Tailwind — Places */
export const places = stylex.create({
  sdef3facc: {
    "position": "relative",
  },
  s177a9453: {
    "flexShrink": 0,
  },
  s850a9bdc: {
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#e7e5e4",
    "padding": "0.75rem",
    "boxShadow": "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
    "outlineWidth": "1px",
    "outlineStyle": "solid",
    "outlineColor": "rgba(231, 229, 228, 0.6)",
    [DARK]: {
      "borderColor": "#292524",
      "backgroundColor": "#0c0a09",
      "outlineColor": "#292524",
    },
  },
  s8cf27964: {
    "marginBottom": "0.5rem",
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "color": "#78716c",
    "textTransform": "uppercase",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s88a3565a: {

  },
  sb8f84d6a: {
    "overflowY": "auto",
    "paddingRight": "0.25rem",
  },
  s44c27f6a: {
    "display": "flex",
    "cursor": "pointer",
    "alignItems": "center",
    "gap": "0.5rem",
    "borderRadius": "0.5rem",
    "paddingLeft": "0.5rem",
    "paddingRight": "0.5rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    ":hover": {
      "backgroundColor": "#1c1917",
    },
  },
  s68e9c50b: {
    "height": "1rem",
    "width": "1rem",
    "flexShrink": 0,
  },
  secf1a105: {
    "color": "#292524",
    [DARK]: {
      "color": "#e7e5e4",
    },
  },
  s9f2373f6: {
    "height": "0.75rem",
    "width": "0.75rem",
    "flexShrink": 0,
    "color": "var(--trips-accent)",
    [DARK]: {
      "color": "var(--ta-strong, #fb7185)",
    },
  },
  s847a05d: {
    "marginTop": "0.5rem",
    "borderRadius": "0.375rem",
    "paddingLeft": "0.5rem",
    "paddingRight": "0.5rem",
    "paddingTop": "0.25rem",
    "paddingBottom": "0.25rem",
    "fontSize": "11px",
    "color": "#b91c1c",
    [DARK]: {
      "color": "#f87171",
    },
  },
  s9346b487: {
    "marginTop": "0.75rem",
    "display": "flex",
    "gap": "0.5rem",
  },
  s1c7a5493: {
    "display": "inline-flex",
    "flex": "1 1 0%",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "0.375rem",
    "borderRadius": "0.5rem",
    "backgroundColor": "var(--trips-accent)",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "fontSize": "12px",
    "color": "#ffffff",
    "fontWeight": 600,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "backgroundColor": "var(--trips-accent)",
    },
    ":hover": {
      "backgroundColor": "var(--ta-strong, #fb7185)",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  s97416715: {
    height: '0.875rem',
    width: '0.875rem',
  },
  sbadbc294: {
    "display": "inline-flex",
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#e7e5e4",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#57534e",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "#44403c",
      "color": "#a8a29e",
    },
    ":hover": {
      "backgroundColor": "#1c1917",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  s29685e07: {
    "position": "relative",
    "borderRadius": "var(--trips-radius, 0.25rem)",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "var(--trips-border, rgba(231, 229, 228, 0.8))",
    "backgroundColor": "var(--trips-surface, #fffcf5)",
    "padding": "1.25rem",
    "transitionProperty": "color, background-color, border-color",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "rgba(41, 37, 36, 0.8)",
      "backgroundColor": "rgba(28, 25, 23, 0.6)",
    },
  },
  s274cec2d: {
    "marginBottom": "0.75rem",
    "display": "flex",
    "alignItems": "center",
    "gap": "0.5rem",
    "borderRadius": "0.5rem",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "fontSize": "12px",
    "color": "#b91c1c",
    [DARK]: {
      "color": "#f87171",
    },
  },
  see6c9312: {
    "display": "flex",
    "flexDirection": "column",
    "rowGap": "0.5rem",
    "@media (min-width: 640px)": {

    },
  },
  s6094affc: {
    "minWidth": 0,
    "@media (min-width: 640px)": {
      "flex": "1 1 0%",
    },
  },
  sd2b6fe48: {
    "display": "inline-flex",
    "flexWrap": "wrap",
    "alignItems": "baseline",
    "color": "#1c1917",
    "fontWeight": 600,
    "lineHeight": 1.375,
    "overflowWrap": "anywhere",
    "wordBreak": "break-word",
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  s26d3e39b: {
    "display": "inline-flex",
    "height": "1.5rem",
    "width": "1.5rem",
    "alignItems": "center",
    "justifyContent": "center",
    "color": "#a8a29e",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#78716c",
    },
    ":hover": {
      "color": "var(--ta-strong, #fb7185)",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  scd3f3ccd: {
    "height": "1rem",
    "width": "1rem",
  },
  s437416ed: {
    "marginTop": "0.125rem",
    "color": "#78716c",
    "lineHeight": 1.375,
    "overflowWrap": "anywhere",
    "wordBreak": "break-word",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s5e96a87d: {
    "color": "#a8a29e",
    [DARK]: {
      "color": "#78716c",
    },
  },
  s35851db4: {
    "marginTop": "0.125rem",
    "color": "#a8a29e",
    [DARK]: {
      "color": "#78716c",
    },
  },
  sf9f3add8: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
    "gap": "0.375rem",
    "@media (min-width: 640px)": {
      "flexShrink": 0,
    },
  },
  s59e27272: {
    "borderRadius": "var(--trips-radius, 0.25rem)",
    "backgroundColor": "var(--ta-soft, #fff1f2)",
    "paddingLeft": "0.5rem",
    "paddingRight": "0.5rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "color": "var(--ta, #be123c)",
    "fontWeight": 600,
    "textTransform": "uppercase",
    "letterSpacing": "0.025em",
    "outlineWidth": "1px",
    "outlineStyle": "solid",
    "boxShadow": "inset 0 0 0 1px currentColor",
    "outlineColor": "#fecdd3",
    [DARK]: {
      "backgroundColor": "rgba(76, 5, 25, 0.3)",
      "color": "var(--ta-strong, #fb7185)",
      "outlineColor": "rgba(136, 19, 55, 0.4)",
    },
  },
  s1a56b4a3: {
    "borderRadius": "var(--trips-radius, 0.25rem)",
    "backgroundColor": "#f5f5f4",
    "paddingLeft": "0.5rem",
    "paddingRight": "0.5rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "color": "#78716c",
    "fontWeight": 500,
    [DARK]: {
      "backgroundColor": "#292524",
      "color": "#a8a29e",
    },
  },
  sf0cf4743: {
    "marginTop": "0.75rem",
    
    "display": "flex",
    "flexDirection": "column",
    "gap": "0.25rem",
    "color": "#57534e",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  sf52c228f: {
    "display": "flex",
    "alignItems": "flex-start",
    "gap": "0.375rem",
  },
  s40d1baca: {
    "marginTop": "0.125rem",
    "flexShrink": 0,
    "color": "#a8a29e",
  },
  sf99a5dc8: {
    "minWidth": 0,
    "overflowWrap": "anywhere",
    "wordBreak": "break-word",
  },
  s69a3f0df: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
  },
  sd730516b: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.25rem",
    "paddingLeft": "0.25rem",
    "paddingRight": "0.25rem",
    "paddingTop": "0.125rem",
    "paddingBottom": "0.125rem",
    "color": "#57534e",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#a8a29e",
    },
    ":hover": {
      "color": "var(--ta-strong, #fb7185)",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  s218d6ca1: {
    "height": "0.75rem",
    "width": "0.75rem",
    "flexShrink": 0,
  },
  s8ae36097: {
    "display": "flex",
    "alignItems": "center",
    "gap": "0.25rem",
    "color": "#d97706",
    [DARK]: {
      "color": "#fbbf24",
    },
  },
  s3daf144e: {
    "height": "0.75rem",
    "width": "0.75rem",
    "flexShrink": 0,
  },
  s402d4c91: {
    "marginTop": "0.75rem",
    "borderTopWidth": "1px",
    "borderTopStyle": "solid",
    "borderColor": "rgba(231, 229, 228, 0.8)",
    "paddingTop": "0.75rem",
    "color": "#57534e",
    "fontStyle": "italic",
    "lineHeight": 1.625,
    [DARK]: {
      "borderColor": "#292524",
      "color": "#a8a29e",
    },
  },
  s224db917: {
    "marginTop": "0.5rem",
    "color": "#a8a29e",
    [DARK]: {
      "color": "#78716c",
    },
  },
  sfd83f352: {
    "paddingLeft": "0.125rem",
    "paddingRight": "0.125rem",
    "fontWeight": 500,
    "color": "#57534e",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#a8a29e",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
    },
  },
  s6ef7bed4: {
    "marginTop": "1rem",
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
    "gap": "0.5rem",
  },
  sf168e15a: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.375rem",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#e7e5e4",
    "backgroundColor": "#fafaf9",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#44403c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "#44403c",
      "backgroundColor": "rgba(41, 37, 36, 0.6)",
      "color": "#d6d3d1",
    },
    ":hover": {
      "borderColor": "#d6d3d1",
      "backgroundColor": "#292524",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  sd2d12d59: {

  },
  s102510f7: {
    "marginLeft": "auto",
    "marginRight": "auto",
    "paddingLeft": "1.25rem",
    "paddingRight": "1.25rem",
    "paddingTop": "4rem",
    "paddingBottom": "4rem",
  },
  s48778e8d: {
    "fontSize": "1.5rem",
    "fontWeight": 600,
    "letterSpacing": "-0.025em",
    "color": "#1c1917",
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  sad760a96: {
    "marginTop": "1.5rem",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "padding": "1.25rem",
    "color": "#292524",
    "lineHeight": 1.625,
    [DARK]: {
      "color": "#e7e5e4",
    },
  },
  sb09a9ba6: {
    "fontWeight": 600,
  },
  s33458c: {
    "marginTop": "0.5rem",
  },
  sd81d42ba: {
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "fontSize": "12px",
  },
  s33458d: {
    "marginTop": "0.75rem",
  },
  sc0a5fd9d: {
    "marginLeft": "auto",
    "marginRight": "auto",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "paddingTop": "3rem",
    "paddingBottom": "3rem",
    "@media (min-width: 640px)": {
      "paddingTop": "4rem",
      "paddingBottom": "4rem",
    },
  },
  s9a3eba29: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "flex-start",
    "justifyContent": "space-between",
  },
  s94efdd3: {
    "color": "#57534e",
    "fontWeight": 500,
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s1cf029cf: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.25rem",
    "paddingLeft": "0.125rem",
    "paddingRight": "0.125rem",
    "color": "#a8a29e",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#78716c",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
    },
  },
  scd31254b: {
    "height": "0.75rem",
    "width": "0.75rem",
  },
  s371c7b55: {
    "marginLeft": "0.5rem",
    "marginRight": "0.5rem",
    "height": "1px",
    "width": "1.5rem",
    "backgroundColor": "#d6d3d1",
    [DARK]: {
      "backgroundColor": "#44403c",
    },
  },
  sc7db521f: {
    "color": "var(--ta, #be123c)",
  },
  sb40f06a1: {
    "marginTop": "0.5rem",
    "fontFamily": '"Archivo Narrow", "Arial Narrow", sans-serif',
    "fontSize": "1.5rem",
    "fontWeight": 600,
    "letterSpacing": "-0.02em",
    "color": "var(--trips-ink, #1c1917)",
    [DARK]: {
      "color": "#f5f5f4",
    },
  },
  s71605953: {
    "marginTop": "0.375rem",
    "color": "#78716c",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  s28b04eb6: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.375rem",
  },
  s30736863: {
    "height": "0.75rem",
    "width": "0.75rem",
  },
  s3c022c12: {
    "fontWeight": 500,
    "color": "#44403c",
    "fontVariantNumeric": "tabular-nums",
    [DARK]: {
      "color": "#d6d3d1",
    },
  },
  s34f26488: {
    "marginLeft": "0.375rem",
    "marginRight": "0.375rem",
    "color": "#d6d3d1",
    [DARK]: {
      "color": "#44403c",
    },
  },
  s30093f3a: {
    "color": "#d97706",
    [DARK]: {
      "color": "#fbbf24",
    },
  },
  s8c466dcd: {
    "position": "relative",
    "width": "100%",
    "@media (min-width: 640px)": {

    },
  },
  s73fe5241: {
    "width": "100%",
    "minHeight": "2.75rem",
    "borderRadius": "var(--trips-field-radius, 1rem)",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "var(--trips-border, #d6d3d1)",
    "backgroundColor": "var(--trips-rail, #f5f5f4)",
    "paddingLeft": "1rem",
    "paddingRight": "2.5rem",
    "paddingTop": "0.5rem",
    "paddingBottom": "0.5rem",
    "color": "var(--trips-ink, #1c1917)",
    "outlineStyle": "none",
    "boxShadow": "inset 0 1px 2px color-mix(in oklch, var(--trips-ink, #1c1917) 12%, transparent)",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    ":focus": {
      "borderColor": "var(--trips-accent)",
      "boxShadow": "0 0 0 2px var(--trips-focus)",
    },
    [DARK]: {
      "borderColor": "var(--trips-border)",
      "backgroundColor": "var(--trips-rail)",
      "color": "var(--trips-ink)",
    },
  },
  s151ef8ff: {
    "position": "absolute",
    "display": "inline-flex",
    "height": "2.75rem",
    "width": "2.75rem",
    "alignItems": "center",
    "justifyContent": "center",
    "borderRadius": "0.5rem",
    "color": "#a8a29e",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "#78716c",
    },
    ":hover": {
      "backgroundColor": "#292524",
      "color": "#e7e5e4",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  s50cf1fc5: {
    "marginTop": "1.5rem",
    "borderBottomWidth": "1px",
    "borderBottomStyle": "solid",
    "borderColor": "rgba(231, 229, 228, 0.8)",
    [DARK]: {
      "borderColor": "rgba(41, 37, 36, 0.8)",
    },
  },
  s1d170d8d: {
    "marginTop": "1.25rem",
  },
  s14482158: {
    "display": "flex",
    "flexWrap": "wrap",
    "gap": "0.375rem",
  },
  s334592: {
    "marginTop": "2rem",
  },
  s531851e2: {
    "display": "flex",
    "flexWrap": "wrap",
    "alignItems": "center",
    "justifyContent": "space-between",
    "gap": "0.75rem",
    "borderRadius": "var(--trips-radius, 0.25rem)",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#fecaca",
    "backgroundColor": "#fef2f2",
    "paddingLeft": "1rem",
    "paddingRight": "1rem",
    "paddingTop": "0.75rem",
    "paddingBottom": "0.75rem",
    "fontSize": "13px",
    "color": "#b91c1c",
    [DARK]: {
      "borderColor": "rgba(127, 29, 29, 0.4)",
      "backgroundColor": "rgba(69, 10, 10, 0.3)",
      "color": "#f87171",
    },
  },
  s13588c5b: {
    "overflowWrap": "anywhere",
    "wordBreak": "break-word",
  },
  se2aea60b: {
    "display": "inline-flex",
    "minHeight": "2.75rem",
    "alignItems": "center",
    "borderRadius": "var(--trips-radius, 0.25rem)",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "rgba(252, 165, 165, 0.7)",
    "backgroundColor": "rgba(255, 255, 255, 0.6)",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.25rem",
    "paddingBottom": "0.25rem",
    "fontSize": "12px",
    "color": "#b91c1c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    ":hover": {
      "backgroundColor": "#ffffff",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px rgba(248, 113, 113, 0.5)",
    },
    [DARK]: {
      "borderColor": "rgba(127, 29, 29, 0.5)",
      "backgroundColor": "rgba(69, 10, 10, 0.4)",
      "color": "#fca5a5",
      ":hover": {
        "backgroundColor": "rgba(69, 10, 10, 0.6)",
      },
    },
  },
  sc7133e98: {
    
    "display": "flex",
    "flexDirection": "column",
    "gap": "0.75rem",
  },
  s405de234: {
    "display": "flex",
    "flexDirection": "column",
    "alignItems": "center",
    "justifyContent": "center",
    "gap": "0.75rem",
    "borderRadius": "1rem",
    "borderWidth": "1px",
    "borderStyle": "dashed",
    "borderColor": "#e7e5e4",
    "backgroundColor": "rgba(250, 250, 249, 0.6)",
    "paddingLeft": "1.5rem",
    "paddingRight": "1.5rem",
    "paddingTop": "2.5rem",
    "paddingBottom": "2.5rem",
    "textAlign": "center",
    [DARK]: {
      "borderColor": "#292524",
      "backgroundColor": "rgba(28, 25, 23, 0.3)",
    },
  },
  sa05ecb46: {
    "color": "#78716c",
    [DARK]: {
      "color": "#a8a29e",
    },
  },
  sc4e2d838: {
    "display": "inline-flex",
    "alignItems": "center",
    "borderRadius": "0.5rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#d6d3d1",
    "paddingLeft": "0.75rem",
    "paddingRight": "0.75rem",
    "paddingTop": "0.375rem",
    "paddingBottom": "0.375rem",
    "color": "#44403c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "#44403c",
      "backgroundColor": "#1c1917",
      "color": "#d6d3d1",
    },
    ":hover": {
      "borderColor": "#a8a29e",
      "backgroundColor": "#292524",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  sc0508a9f: {
    "color": "var(--trips-accent)",
    "textUnderlineOffset": "2px",
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "color": "var(--ta-strong, #fb7185)",
    },
    ":hover": {
      "textDecorationLine": "underline",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  sc7133e99: {
    
    "display": "flex",
    "flexDirection": "column",
    "gap": "1rem",
  },
  sbeb895ab: {
    "marginTop": "2rem",
    "display": "flex",
    "justifyContent": "center",
  },
  s82ccd023: {
    "display": "inline-flex",
    "alignItems": "center",
    "gap": "0.5rem",
    "borderRadius": "0.75rem",
    "borderWidth": "1px",
    "borderStyle": "solid",
    "borderColor": "#d6d3d1",
    "paddingLeft": "1.5rem",
    "paddingRight": "1.5rem",
    "paddingTop": "0.625rem",
    "paddingBottom": "0.625rem",
    "color": "#44403c",
    "fontWeight": 500,
    "transitionProperty": "color, background-color, border-color, opacity, transform",
    "transitionDuration": "150ms",
    [DARK]: {
      "borderColor": "#44403c",
      "backgroundColor": "#1c1917",
      "color": "#d6d3d1",
    },
    ":hover": {
      "borderColor": "#a8a29e",
      "backgroundColor": "#292524",
    },
    ":focus-visible": {
      "outlineStyle": "none",
      "boxShadow": "0 0 0 2px currentColor",
      "outlineColor": "var(--trips-focus)",
    },
  },
  badgeBase: {
    display: 'inline-flex',
    alignItems: 'center',
    borderRadius: 'var(--trips-radius, 0.25rem)',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '10px',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.025em',
  },
  catRestaurant: { backgroundColor: 'var(--ta-soft, #fff1f2)', color: 'var(--ta, #be123c)', [DARK]: { backgroundColor: 'rgba(76, 5, 25, 0.3)', color: 'var(--ta-strong, #fb7185)' } },
  catCafe: { backgroundColor: '#fffbeb', color: '#b45309', [DARK]: { backgroundColor: 'rgba(69, 26, 3, 0.3)', color: '#fbbf24' } },
  catBar: { backgroundColor: '#faf5ff', color: '#7e22ce', [DARK]: { backgroundColor: 'rgba(59, 7, 100, 0.3)', color: '#c084fc' } },
  catShopping: { backgroundColor: '#eff6ff', color: '#1d4ed8', [DARK]: { backgroundColor: 'rgba(30, 58, 138, 0.3)', color: '#60a5fa' } },
  catActivity: { backgroundColor: '#ecfdf5', color: '#047857', [DARK]: { backgroundColor: 'rgba(2, 44, 34, 0.3)', color: '#34d399' } },
  catHotel: { backgroundColor: '#eef2ff', color: '#4338ca', [DARK]: { backgroundColor: 'rgba(49, 46, 129, 0.3)', color: '#818cf8' } },
  catLandmark: { backgroundColor: '#f5f5f4', color: '#57534e', [DARK]: { backgroundColor: '#292524', color: '#a8a29e' } },
  catOther: { backgroundColor: '#f5f5f4', color: '#78716c', [DARK]: { backgroundColor: '#292524', color: '#78716c' } },
  bandHigh: { backgroundColor: '#ecfdf5', color: '#047857', [DARK]: { backgroundColor: 'rgba(2, 44, 34, 0.3)', color: '#34d399' } },
  bandMedium: { backgroundColor: '#fffbeb', color: '#b45309', [DARK]: { backgroundColor: 'rgba(69, 26, 3, 0.3)', color: '#fbbf24' } },
  bandLow: { backgroundColor: '#f5f5f4', color: '#78716c', [DARK]: { backgroundColor: '#292524', color: '#a8a29e' } },
  bandGap: { gap: '0.25rem' },
  dayBtnBase: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    gap: '0.375rem',
    borderRadius: 'var(--trips-radius, 0.25rem)',
    borderWidth: '1px',
    borderStyle: 'solid',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    fontSize: '12px',
    fontWeight: 500,
    transitionProperty: 'transform, color, background-color, border-color',
    transitionDuration: '150ms',
    ':active': { transform: 'scale(0.98)' },
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px var(--trips-focus)',
      outlineOffset: '1px',
    },
  },
  dayBtnAssigned: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--ta-ring, #fda4af)',
    backgroundColor: 'var(--ta-soft, #fff1f2)',
    color: 'var(--ta, #be123c)',
    ':hover': { borderColor: 'var(--ta-strong, #fb7185)', backgroundColor: 'var(--ta-soft, #ffe4e6)' },
    [DARK]: {
      borderColor: 'rgba(190, 18, 60, 0.6)',
      backgroundColor: 'rgba(76, 5, 25, 0.4)',
      color: 'var(--ta-strong, #fb7185)',
      ':hover': { backgroundColor: 'rgba(76, 5, 25, 0.6)' },
    },
  },
  dayBtnDefault: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e7e5e4',
    backgroundColor: '#fafaf9',
    color: '#57534e',
    ':hover': { borderColor: '#d6d3d1', backgroundColor: '#f5f5f4' },
    [DARK]: {
      borderColor: '#44403c',
      backgroundColor: 'rgba(41, 37, 36, 0.6)',
      color: '#d6d3d1',
      ':hover': { backgroundColor: '#292524' },
    },
  },
  filterChipBase: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    alignItems: 'center',
    borderRadius: 'var(--trips-radius, 0.25rem)',
    borderWidth: '1px',
    borderStyle: 'solid',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    fontSize: '12px',
    fontWeight: 500,
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '200ms',
    transitionTimingFunction: 'ease-out',
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px rgba(244, 63, 94, 0.5)',
    },
  },
  filterChipActive: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--ta-ring, #fda4af)',
    backgroundColor: 'var(--ta-soft, #fff1f2)',
    color: 'var(--ta, #be123c)',
    ':hover': { borderColor: 'var(--ta, #be123c)' },
    [DARK]: { color: 'var(--ta-strong, #fb7185)' },
  },
  filterChipInactive: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#e7e5e4',
    backgroundColor: '#ffffff',
    color: '#57534e',
    ':hover': { borderColor: '#d6d3d1', backgroundColor: '#fafaf9' },
    [DARK]: {
      borderColor: '#44403c',
      backgroundColor: '#1c1917',
      color: '#a8a29e',
      ':hover': { backgroundColor: '#292524' },
    },
  },

})
