import { stylex } from '@/styles/merge'

/** Shared BreathFlow layout, type, and interaction primitives. */
export const bf = stylex.create({
  // ── Focus & links ──────────────────────────────────────────────
  citationLink: {
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    color: 'var(--bw-text-secondary)',
    textDecorationLine: 'underline',
    textDecorationColor: 'var(--bw-border)',
    textUnderlineOffset: '2px',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        color: 'var(--bw-accent)',
      },
    },
  },

  // ── Typography ─────────────────────────────────────────────────
  textBw: { color: 'var(--bw-text)' },
  textSecondary: { color: 'var(--bw-text-secondary)' },
  textTertiary: { color: 'var(--bw-text-tertiary)' },
  textDestructive: { color: 'var(--bw-destructive)' },
  textXs: { fontSize: '0.75rem', lineHeight: '1rem' },
  textSm: { fontSize: '0.875rem', lineHeight: '1.25rem' },
  text11px: { fontSize: '11px' },
  text12px: { fontSize: '12px' },
  fontMedium: { fontWeight: 500 },
  fontSemibold: { fontWeight: 600 },
  fontNormal: { fontWeight: 400 },
  leadingSnug: { lineHeight: 1.375 },
  leadingRelaxed: { lineHeight: 1.625 },
  capitalize: { textTransform: 'capitalize' },
  truncate: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  breakWords: {
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  tabularNums: {
    fontVariantNumeric: 'tabular-nums',
    fontFeatureSettings: '"tnum"',
  },

  // ── Surfaces & borders ─────────────────────────────────────────
  bgCanvas: { backgroundColor: 'var(--bw-canvas)' },
  bgAccentSubtle: { backgroundColor: 'var(--bw-accent-subtle)' },

  // ── Layout helpers ───────────────────────────────────────────────
  spaceY1: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  spaceY15: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.375rem',
  },
  flex1: { flex: '1 1 0%' },
  shrink0: { flexShrink: 0 },
  minW0: { minWidth: 0 },
  w9: { width: '2.25rem' },
  w10: { width: '2.5rem' },
  wFull: { width: '100%' },
  h10: { height: '2.5rem' },
  mt05: { marginTop: '0.125rem' },
  mt1: { marginTop: '0.25rem' },
  mt15: { marginTop: '0.375rem' },
  mt2: { marginTop: '0.5rem' },
  mt3: { marginTop: '0.75rem' },
  mt4: { marginTop: '1rem' },
  mt5: { marginTop: '1.25rem' },
  mt6: { marginTop: '1.5rem' },
  mt8: { marginTop: '2rem' },
  mb3: { marginBottom: '0.75rem' },
  ml2: { marginLeft: '0.5rem' },
  px4: { paddingLeft: '1rem', paddingRight: '1rem' },
  py3: { paddingTop: '0.75rem', paddingBottom: '0.75rem' },
  p3: { padding: '0.75rem' },
  inset0: { inset: 0 },
  roundedFull: { borderRadius: '9999px' },
  rounded2xl: { borderRadius: '1rem' },
  pointerEventsNone: { pointerEvents: 'none' },
  antialiased: {
    WebkitFontSmoothing: 'antialiased',
    MozOsxFontSmoothing: 'grayscale',
  },
  fontSans: {
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  minH100svh: { minHeight: '100svh' },
  textCenter: { textAlign: 'center' },
  block: { display: 'block' },
  inlineFlex: { display: 'inline-flex' },
  overflowHidden: { overflow: 'hidden' },
  absolute: { position: 'absolute' },
  relative: { position: 'relative' },
  ring1BwBorder: {
    boxShadow: `0 0 0 1px ${'var(--bw-border)'}`,
  },

  // ── Responsive (sm: 640px) ───────────────────────────────────────

  // ── Dark mode image swap ─────────────────────────────────────────

  // ── Skip link (sr-only until focus) ──────────────────────────────
  skipLink: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
    ':focus': {
      position: 'absolute',
      width: 'auto',
      height: 'auto',
      padding: '0.5rem 0.75rem',
      margin: 0,
      overflow: 'visible',
      clipPath: 'none',
      whiteSpace: 'normal',
      left: '1.25rem',
      top: '0.75rem',
      zIndex: 50,
      backgroundColor: 'var(--bw-canvas)',
      fontSize: '0.875rem',
      color: 'var(--bw-text)',
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
  },

  // ── Orb / viz sizes ──────────────────────────────────────────────

  // ── Heatmap intensity ────────────────────────────────────────────

  // ── Motion-reduce helpers ─────────────────────────────────────────
  groupOpenRotate180: {
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
    ':is(.group[open] &)': {
      transform: 'rotate(180deg)',
    },
  },

  // ── Peer checkbox patterns ───────────────────────────────────────
  checkboxBox: {
    display: 'flex',
    height: '1.25rem',
    width: '1.25rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '0.25rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '150ms',
    ':is(.peer:focus-visible ~ &)': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
  },
  checkboxBoxChecked: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--bw-accent)',
    backgroundColor: 'var(--bw-accent)',
    color: 'var(--bw-accent-foreground)',
  },
  checkboxBoxUnchecked: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--bw-border)',
    backgroundColor: 'var(--bw-surface)',
  },
  toggleTrack: {
    position: 'relative',
    height: '1.75rem',
    width: '3rem',
    flexShrink: 0,
    borderRadius: '9999px',
    transitionProperty: 'background-color',
    transitionDuration: '200ms',
    transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
    ':is(.peer:focus-visible ~ &)': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
  },
  toggleThumb: {
    position: 'absolute',
    top: '0.25rem',
    left: 0,
    height: '1.25rem',
    width: '1.25rem',
    borderRadius: '9999px',
    backgroundColor: 'var(--bw-surface)',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
  },
  detailsSummary: {
    display: 'flex',
    minHeight: '44px',
    cursor: 'pointer',
    listStyle: 'none',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '0.875rem',
    color: 'var(--bw-text)',
    '::-webkit-details-marker': {
      display: 'none',
    },
  },
  detailsSummaryTertiary: {
    display: 'flex',
    minHeight: '44px',
    cursor: 'pointer',
    listStyle: 'none',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBlock: '0.5rem',
    fontSize: '0.75rem',
    color: 'var(--bw-text-tertiary)',
    '::-webkit-details-marker': {
      display: 'none',
    },
  },
  safeAreaTop: {
    paddingTop: 'max(1.5rem, env(safe-area-inset-top))',
  },
  safeAreaBottom: {
    paddingBottom: 'max(1.5rem, env(safe-area-inset-bottom))',
  },
  groupOpenHidden: {
    ':is(.group[open] &)': {
      display: 'none',
    },
  },
  detailsGroup: {
    marginTop: '0.5rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--bw-border-subtle)',
    paddingTop: '0.5rem',
  },
  detailsGroupFlush: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--bw-border-subtle)',
    paddingTop: '0.5rem',
  },
  showMoreBtn: {
    marginTop: '0.5rem',
    minHeight: '44px',
    width: '100%',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    color: 'var(--bw-text-secondary)',
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: 'var(--bw-hover)',
      },
    },
  },
  safetyLabel: {
    display: 'flex',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    gap: '0.75rem',
    borderRadius: '0.5rem',
    paddingLeft: '0.375rem',
    paddingRight: '0.375rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        backgroundColor: 'var(--bw-hover)',
      },
    },
  },
  inkChip: {
    position: 'relative',
    isolation: 'isolate',
    minHeight: '44px',
    minWidth: '44px',
    paddingLeft: '0.95rem',
    paddingRight: '0.95rem',
    fontSize: '0.875rem',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--bw-border)',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    transitionProperty: 'color, border-color',
    transitionDuration: '200ms',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
  },
  inkChipActive: {
    fontWeight: 500,
    color: 'var(--bw-text)',
    borderColor: 'transparent',
  },
  inkChipInactive: {
    color: 'var(--bw-text-secondary)',
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        color: 'var(--bw-text)',
        borderColor: 'color-mix(in srgb, var(--bw-text) 28%, transparent)',
      },
    },
  },
  inkChipXs: {
    fontSize: '0.75rem',
  },
  /** A wash of ink laid behind the active label (chips, nav). */
  selectionInk: {
    position: 'absolute',
    inset: 0,
    zIndex: -1,
    borderRadius: '999px',
    backgroundColor: 'color-mix(in srgb, var(--bf-ink, var(--bw-accent)) 16%, transparent)',
    boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--bf-ink, var(--bw-accent)) 30%, transparent)',
  },
  noticeAccent: {
    backgroundColor: 'var(--bw-accent-subtle)',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
  },
  noticeDanger: {
    backgroundColor: 'var(--bw-destructive-subtle)',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
  },
  rangeInput: {
    marginTop: '0.5rem',
    height: '44px',
    width: '100%',
    accentColor: 'var(--bw-accent)',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
    ':disabled': {
      opacity: 0.4,
    },
  },
  repeatLink: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    fontSize: '0.75rem',
    color: 'var(--bw-text-secondary)',
    transitionProperty: 'color',
    transitionDuration: '150ms',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: 'var(--bw-accent)',
      outlineOffset: '2px',
    },
    '@media (hover: hover) and (pointer: fine)': {
      ':hover': {
        color: 'var(--bw-accent)',
      },
    },
  },
  bulletDot: {
    marginTop: '0.375rem',
    height: '0.25rem',
    width: '0.25rem',
    flexShrink: 0,
    borderRadius: '9999px',
    backgroundColor: 'var(--bw-text-tertiary)',
  },
  phaseCue: {
    marginTop: '0.5rem',
    maxWidth: '20rem',
    fontSize: '0.875rem',
    lineHeight: 1.625,
    color: 'var(--bw-text-secondary)',
  },
  recoveryCue: {
    marginTop: '0.375rem',
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '20rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    fontSize: '0.75rem',
    lineHeight: 1.375,
    color: 'var(--bw-text-tertiary)',
  },
  cadenceRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--bw-border-subtle)',
    ':first-child': {
      borderTopWidth: 0,
    },
  },
  historyRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--bw-border-subtle)',
    ':first-child': {
      borderTopWidth: 0,
    },
  },
  flexWrapGap2: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  flexWrapGap15: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.375rem',
  },
  flexBetween: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flexBaselineBetween: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '0.5rem',
  },
  flexItemsCenterGap3: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  flexItemsCenterGap1: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
  },
  flexItemsCenterGap2: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  flexColGap2SmRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
      alignItems: 'center',
    },
  },
  toggleLabel: {
    display: 'flex',
    minHeight: '44px',
    cursor: 'pointer',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
  },
  volumeLabel: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    fontSize: '0.875rem',
    color: 'var(--bw-text)',
  },
  figcaptionRow: {
    marginTop: '0.25rem',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '10px',
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--bw-text-tertiary)',
  },
  contraindicationRow: {
    display: 'flex',
    gap: '0.5rem',
    fontSize: '0.75rem',
    lineHeight: 1.625,
    color: 'var(--bw-text-secondary)',
  },
  legendMb2: {
    marginBottom: '0.5rem',
    fontSize: '0.875rem',
    color: 'var(--bw-text-secondary)',
  },
  scienceBody: {
    paddingBottom: '0.5rem',
    paddingTop: '0.25rem',
  },
  startBlock: {
    marginTop: '1.75rem',
  },
  startCue: {
    marginBottom: '0.625rem',
    textAlign: 'center',
    fontSize: '0.875rem',
    color: 'var(--bw-text-secondary)',
  },
  disclosureList: {
    marginTop: '0.25rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.375rem',
  },
})
