import * as stylex from '@stylexjs/stylex'

/*
 * Landing (`/`) — anthonyl.im lab. Tokens live on `.landing` in index.css.
 * Grammar: bone paper, ink sections, one ultramarine field (Safety).
 * Archivo (variable width) for everything typographic; Fragment Mono for data.
 */

const rise = stylex.keyframes({
  from: { transform: 'translateY(6px)', opacity: 0 },
  to: { transform: 'translateY(0)', opacity: 1 },
})
const marquee = stylex.keyframes({
  from: { transform: 'translateX(0)' },
  to: { transform: 'translateX(-50%)' },
})
const pulse = stylex.keyframes({
  '0%': { boxShadow: '0 0 0 0 rgba(44, 148, 102, 0.55)' },
  '70%': { boxShadow: '0 0 0 7px rgba(44, 148, 102, 0)' },
  '100%': { boxShadow: '0 0 0 0 rgba(44, 148, 102, 0)' },
})
const scan = stylex.keyframes({
  from: { transform: 'translateX(-100%)' },
  to: { transform: 'translateX(100%)' },
})
const blink = stylex.keyframes({
  '0%, 49%': { opacity: 1 },
  '50%, 100%': { opacity: 0 },
})
const typingDot = stylex.keyframes({
  '0%, 60%, 100%': { transform: 'translateY(0)', opacity: 0.35 },
  '30%': { transform: 'translateY(-3px)', opacity: 1 },
})
const bubbleIn = stylex.keyframes({
  '0%, 8%': { opacity: 0, transform: 'translateY(8px) scale(0.97)' },
  '16%, 88%': { opacity: 1, transform: 'translateY(0) scale(1)' },
  '96%, 100%': { opacity: 0, transform: 'translateY(-4px) scale(1)' },
})
const dash = stylex.keyframes({
  from: { strokeDashoffset: 260 },
  to: { strokeDashoffset: 0 },
})
const breathe = stylex.keyframes({
  '0%, 100%': { transform: 'scale(0.62)' },
  '45%, 55%': { transform: 'scale(1)' },
})
const halo = stylex.keyframes({
  '0%, 100%': { transform: 'scale(0.7)', opacity: 0.25 },
  '50%': { transform: 'scale(1.12)', opacity: 0.6 },
})
const packet = stylex.keyframes({
  '0%': { transform: 'translateX(0)', opacity: 0 },
  '15%': { opacity: 1 },
  '85%': { opacity: 1 },
  '100%': { transform: 'translateX(150px)', opacity: 0 },
})
const termType = stylex.keyframes({
  '0%, 10%': { clipPath: 'inset(0 100% 0 0)' },
  '40%, 100%': { clipPath: 'inset(0 0 0 0)' },
})

const focusRing = {
  outlineWidth: '2px',
  outlineStyle: 'solid',
  outlineColor: 'var(--lim-ultra)',
  outlineOffset: '3px',
} as const

export const page = stylex.create({
  root: {
    backgroundColor: 'var(--lim-bone)',
    color: 'var(--lim-text)',
    fontFamily: 'var(--lim-display)',
    fontSize: '1rem',
    lineHeight: 1.6,
    WebkitFontSmoothing: 'antialiased',
    MozOsxFontSmoothing: 'grayscale',
    textRendering: 'optimizeLegibility',
    minHeight: '100dvh',
    overflowX: 'clip',
  },
  container: {
    width: '100%',
    maxWidth: '1320px',
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingLeft: 'clamp(20px, 4.2vw, 56px)',
    paddingRight: 'clamp(20px, 4.2vw, 56px)',
  },
  srOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
  skip: {
    position: 'absolute',
    left: '16px',
    top: '-60px',
    zIndex: 100,
    paddingTop: '10px',
    paddingBottom: '10px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: '8px',
    backgroundColor: 'var(--lim-ink)',
    color: 'var(--lim-on-ink)',
    textDecoration: 'none',
    ':focus-visible': { top: '12px', ...focusRing },
  },
})

export const brand = stylex.create({
  mark: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '9px',
    fontFamily: 'var(--lim-display)',
    fontStretch: '112%',
    fontWeight: 620,
    fontSize: '1.0625rem',
    letterSpacing: '-0.03em',
    color: 'var(--lim-text)',
  },
  onInk: { color: 'var(--lim-on-ink)' },
  glyph: { width: '22px', height: '22px', flexShrink: 0 },
  drop: { fill: 'var(--lim-ultra)' },
  shine: { fill: 'none', stroke: 'rgba(237, 232, 223, 0.85)', strokeWidth: 1.6, strokeLinecap: 'round' },
  dot: { color: 'var(--lim-ultra)' },
  dotOnInk: { color: 'var(--lim-ultra-pale)' },
})

export const btn = stylex.create({
  base: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    minHeight: '48px',
    paddingLeft: '22px',
    paddingRight: '22px',
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    fontFamily: 'var(--lim-display)',
    fontSize: '0.96875rem',
    fontWeight: 560,
    letterSpacing: '-0.005em',
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    transitionProperty: 'background-color, color, border-color, transform',
    transitionDuration: '220ms',
    transitionTimingFunction: 'var(--lim-ease)',
    ':focus-visible': focusRing,
    ':active': { transform: 'translateY(1px)' },
  },
  small: { minHeight: '40px', paddingLeft: '16px', paddingRight: '16px', fontSize: '0.875rem' },
  primary: {
    backgroundColor: 'var(--lim-ultra)',
    color: '#F7F4EE',
    '@media (hover: hover)': { ':hover': { backgroundColor: 'var(--lim-ultra-deep)' } },
  },
  ghost: {
    color: 'var(--lim-text)',
    borderColor: 'var(--lim-line)',
    backgroundColor: 'transparent',
    '@media (hover: hover)': { ':hover': { borderColor: 'var(--lim-text)' } },
  },
  ghostOnInk: {
    color: 'var(--lim-on-ink)',
    borderColor: 'var(--lim-ink-line)',
    '@media (hover: hover)': { ':hover': { borderColor: 'var(--lim-on-ink)' } },
    ':focus-visible': { ...focusRing, outlineColor: 'var(--lim-ultra-pale)' },
  },
  onUltra: {
    backgroundColor: 'var(--lim-bone)',
    color: 'var(--lim-ultra-deep)',
    '@media (hover: hover)': { ':hover': { backgroundColor: '#FFFFFF' } },
    ':focus-visible': { ...focusRing, outlineColor: 'var(--lim-bone)' },
  },
  arrow: {
    transitionProperty: 'transform',
    transitionDuration: '260ms',
    transitionTimingFunction: 'var(--lim-ease)',
    ':is(a:hover > *)': { transform: 'translateX(3px)' },
  },
})

export const nav = stylex.create({
  bar: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    transitionProperty: 'background-color, border-color',
    transitionDuration: '300ms',
  },
  barSolid: {
    backgroundColor: 'rgba(237, 232, 223, 0.94)',
    backdropFilter: 'saturate(1.2) blur(12px)',
    borderBottomColor: 'var(--lim-line)',
  },
  inner: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
    maxWidth: '1320px',
    height: '68px',
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingLeft: 'clamp(20px, 4.2vw, 56px)',
    paddingRight: 'clamp(20px, 4.2vw, 56px)',
  },
  home: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    textDecoration: 'none',
    borderRadius: '6px',
    ':focus-visible': focusRing,
  },
  links: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: '24px',
    '@media (max-width: 1023px)': { display: 'none' },
  },
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '44px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: '8px',
    fontSize: '0.90625rem',
    fontWeight: 500,
    color: 'var(--lim-text-2)',
    textDecoration: 'none',
    transitionProperty: 'color',
    transitionDuration: '160ms',
    ':hover': { color: 'var(--lim-text)' },
    ':focus-visible': focusRing,
  },
  secondary: { '@media (max-width: 639px)': { display: 'none' } },
  actions: { display: 'flex', alignItems: 'center', gap: '8px', marginLeft: 'auto' },
  menuBtn: {
    display: 'none',
    alignItems: 'center',
    justifyContent: 'center',
    width: '44px',
    height: '44px',
    borderRadius: '10px',
    color: 'var(--lim-text)',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    ':focus-visible': focusRing,
    '@media (max-width: 1023px)': { display: 'inline-flex' },
  },
  sheet: {
    display: 'none',
    flexDirection: 'column',
    paddingTop: '8px',
    paddingBottom: '20px',
    paddingLeft: 'clamp(20px, 4.2vw, 56px)',
    paddingRight: 'clamp(20px, 4.2vw, 56px)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
    '@media (max-width: 1023px)': { display: 'flex' },
  },
  sheetLink: {
    display: 'flex',
    alignItems: 'center',
    minHeight: '52px',
    fontSize: '1.375rem',
    fontStretch: '108%',
    fontWeight: 520,
    letterSpacing: '-0.02em',
    color: 'var(--lim-text)',
    textDecoration: 'none',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-line)',
    animationName: rise,
    animationDuration: '420ms',
    animationTimingFunction: 'var(--lim-ease)',
    animationFillMode: 'both',
    ':focus-visible': focusRing,
  },
})

export const hero = stylex.create({
  section: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 'max(100svh, 680px)',
    paddingTop: '68px',
    backgroundColor: 'var(--lim-bone)',
    overflow: 'hidden',
    isolation: 'isolate',
    '@media (max-width: 819px)': { minHeight: 'max(100svh, 760px)' },
  },
  stage: { position: 'absolute', inset: 0, zIndex: -1, pointerEvents: 'none' },
  still: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    opacity: 0,
    transform: 'scale(1.14)',
    transitionProperty: 'opacity',
    transitionDuration: '900ms',
  },
  stillShown: { opacity: 1 },
  live: {
    position: 'absolute',
    inset: 0,
    opacity: 0,
    transitionProperty: 'opacity',
    transitionDuration: '1200ms',
    transitionTimingFunction: 'var(--lim-ease)',
  },
  liveShown: { opacity: 1 },
  content: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    flexGrow: 1,
    paddingTop: '6vh',
    paddingBottom: '14vh',
    pointerEvents: 'none',
    '@media (max-width: 819px)': { justifyContent: 'flex-start', paddingTop: '6vh', paddingBottom: '0' },
  },
  announce: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    minHeight: '40px',
    paddingLeft: '6px',
    paddingRight: '14px',
    marginBottom: '28px',
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    backgroundColor: 'rgba(247, 244, 238, 0.7)',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: 'var(--lim-text)',
    textDecoration: 'none',
    pointerEvents: 'auto',
    transitionProperty: 'border-color',
    transitionDuration: '200ms',
    ':hover': { borderColor: 'var(--lim-ultra)' },
    ':focus-visible': focusRing,
  },
  announceTag: {
    paddingTop: '3px',
    paddingBottom: '3px',
    paddingLeft: '9px',
    paddingRight: '9px',
    borderRadius: '999px',
    backgroundColor: 'var(--lim-ultra)',
    color: '#F7F4EE',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.6875rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  title: {
    margin: 0,
    maxWidth: '11.5em',
    fontFamily: 'var(--lim-display)',
    fontStretch: '110%',
    fontWeight: 560,
    fontSize: 'clamp(2.25rem, 5.4vw, 5.6rem)',
    lineHeight: 0.93,
    letterSpacing: '-0.045em',
    color: 'var(--lim-text)',
    '@media (min-width: 820px)': { maxWidth: '9.6em' },
  },
  lineMask: { display: 'block', overflow: 'hidden', paddingBottom: '0.06em', marginBottom: '-0.06em' },
  line: { display: 'block' },
  lede: {
    maxWidth: '34rem',
    marginTop: '28px',
    marginBottom: 0,
    fontSize: 'clamp(1.0625rem, 1.35vw, 1.25rem)',
    lineHeight: 1.5,
    color: 'var(--lim-text-2)',
    textWrap: 'pretty',
  },
  ctas: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    marginTop: '34px',
    pointerEvents: 'auto',
  },
  foot: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    paddingBottom: 'calc(9vh + 12px)',
    pointerEvents: 'none',
    '@media (max-width: 819px)': { paddingBottom: '7vh' },
  },
  status: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '10px',
    margin: 0,
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
    letterSpacing: '0.02em',
    color: 'var(--lim-text)',
  },
  statusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: 'var(--lim-ok)',
    animationName: pulse,
    animationDuration: '2.4s',
    animationIterationCount: 'infinite',
    '@media (prefers-reduced-motion: reduce)': { animationName: 'none' },
  },
  statusSep: { color: 'var(--lim-text-3)' },
  statusDim: { color: 'var(--lim-text-2)', '@media (max-width: 539px)': { display: 'none' } },
  hint: {
    margin: 0,
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
    color: 'var(--lim-text-2)',
    '@media (max-width: 819px)': { display: 'none' },
    '@media (prefers-reduced-motion: reduce)': { display: 'none' },
  },
})

export const sec = stylex.create({
  bone: { backgroundColor: 'var(--lim-bone)', color: 'var(--lim-text)' },
  boneDeep: { backgroundColor: 'var(--lim-bone-deep)', color: 'var(--lim-text)' },
  paperBg: { backgroundColor: 'var(--lim-paper)', color: 'var(--lim-text)' },
  ink: { backgroundColor: 'var(--lim-ink)', color: 'var(--lim-on-ink)' },
  ultra: { backgroundColor: 'var(--lim-ultra)', color: 'var(--lim-bone)' },
  pad: { paddingTop: 'clamp(88px, 12vw, 168px)', paddingBottom: 'clamp(88px, 12vw, 168px)' },
  padBottom: { paddingBottom: 'clamp(88px, 12vw, 168px)' },

  kicker: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    margin: 0,
    marginBottom: '22px',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: 'var(--lim-text-2)',
    '::before': {
      content: '""',
      width: '7px',
      height: '7px',
      backgroundColor: 'var(--lim-ultra)',
    },
  },
  kickerOnInk: {
    color: 'var(--lim-on-ink-2)',
    '::before': { content: '""', width: '7px', height: '7px', backgroundColor: 'var(--lim-ultra-pale)' },
  },
  h2: {
    margin: 0,
    maxWidth: '14em',
    fontFamily: 'var(--lim-display)',
    fontStretch: '108%',
    fontWeight: 540,
    fontSize: 'clamp(2.25rem, 4.6vw, 4.25rem)',
    lineHeight: 1,
    letterSpacing: '-0.038em',
    textWrap: 'balance',
  },
  h2OnInk: { color: 'var(--lim-on-ink)' },
  h2Wide: { maxWidth: '18em' },
  h3: {
    margin: 0,
    fontFamily: 'var(--lim-display)',
    fontStretch: '106%',
    fontWeight: 540,
    fontSize: 'clamp(1.375rem, 2vw, 1.75rem)',
    lineHeight: 1.15,
    letterSpacing: '-0.025em',
  },
  h3OnInk: { color: 'var(--lim-on-ink)' },
  lede: {
    maxWidth: '30rem',
    margin: 0,
    fontSize: '1.125rem',
    lineHeight: 1.55,
    color: 'var(--lim-text-2)',
    textWrap: 'pretty',
  },
  ledeOnInk: { color: 'var(--lim-on-ink-2)' },
  ledeBelow: { marginTop: '24px' },
  body: { margin: 0, fontSize: '1.0625rem', lineHeight: 1.65, color: 'var(--lim-text-2)', textWrap: 'pretty' },
  bodyLarge: { maxWidth: '32rem', marginTop: '28px', fontSize: '1.1875rem' },
  small: { margin: 0, fontSize: '0.875rem', lineHeight: 1.5, color: 'var(--lim-text-3)' },
  meta: {
    margin: 0,
    marginBottom: '14px',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--lim-ultra)',
  },
  inlineLink: {
    color: 'var(--lim-ultra)',
    textDecorationLine: 'underline',
    textUnderlineOffset: '3px',
    textDecorationThickness: '1px',
    ':focus-visible': focusRing,
  },
  splitHead: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.25fr) minmax(0, 1fr)',
    alignItems: 'end',
    gap: '32px',
    marginBottom: 'clamp(48px, 6vw, 80px)',
    '@media (max-width: 819px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },

  /* Customers */
  customers: {
    paddingTop: '28px',
    paddingBottom: '36px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-ink-line)',
  },
  customersLabel: {
    margin: 0,
    marginBottom: '22px',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'var(--lim-on-ink-2)',
  },
  marquee: {
    overflow: 'hidden',
    maskImage: 'linear-gradient(90deg, transparent, #000 8%, #000 92%, transparent)',
  },
  marqueeTrack: {
    display: 'flex',
    width: 'max-content',
    gap: 'clamp(40px, 6vw, 88px)',
    margin: 0,
    padding: 0,
    listStyle: 'none',
    animationName: marquee,
    animationDuration: '46s',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
    ':hover': { animationPlayState: 'paused' },
    '@media (prefers-reduced-motion: reduce)': { animationName: 'none', flexWrap: 'wrap', width: 'auto' },
  },
  logo: {
    flexShrink: 0,
    fontSize: '1.375rem',
    lineHeight: 1,
    whiteSpace: 'nowrap',
    color: 'rgba(237, 232, 223, 0.72)',
    paddingLeft: '4px',
  },
  logoHeavy: { fontWeight: 800, fontStretch: '88%', letterSpacing: '-0.04em' },
  logoSpaced: { fontWeight: 500, fontSize: '1rem', letterSpacing: '0.32em' },
  logoLower: { fontWeight: 400, fontStretch: '118%', letterSpacing: '-0.02em' },
  logoItalic: { fontWeight: 600, fontStyle: 'italic', fontStretch: '75%', letterSpacing: '-0.01em', fontSize: '1.5rem' },
  logoWide: { fontWeight: 700, fontStretch: '125%', fontSize: '1.0625rem', letterSpacing: '0.04em' },

  /* Approach */
  thesis: {
    maxWidth: '22em',
    margin: 0,
    fontFamily: 'var(--lim-display)',
    fontStretch: '106%',
    fontWeight: 480,
    fontSize: 'clamp(1.875rem, 4.1vw, 3.75rem)',
    lineHeight: 1.12,
    letterSpacing: '-0.03em',
    color: 'var(--lim-on-ink)',
  },
  pillars: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 'clamp(24px, 3vw, 48px)',
    marginTop: 'clamp(64px, 8vw, 112px)',
    marginBottom: 'clamp(88px, 10vw, 140px)',
    padding: 0,
    listStyle: 'none',
    '@media (max-width: 819px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  pillar: {
    paddingTop: '22px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ink-line)',
  },
  pillarN: { fontFamily: 'var(--lim-mono)', fontSize: '0.75rem', color: 'var(--lim-ultra-pale)' },
  pillarTitle: {
    margin: 0,
    marginTop: '16px',
    fontStretch: '110%',
    fontWeight: 560,
    fontSize: '1.75rem',
    letterSpacing: '-0.03em',
    color: 'var(--lim-on-ink)',
  },
  pillarBody: { margin: 0, marginTop: '10px', fontSize: '1.0625rem', lineHeight: 1.6, color: 'var(--lim-on-ink-2)' },

  /* Models */
  models: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '16px',
    margin: 0,
    padding: 0,
    listStyle: 'none',
    '@media (max-width: 1023px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  model: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: '420px',
    padding: 'clamp(24px, 2.6vw, 36px)',
    borderRadius: '18px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    backgroundColor: 'var(--lim-paper)',
    '@media (max-width: 1023px)': { minHeight: 0 },
  },
  modelLead: { backgroundColor: 'var(--lim-ink)', borderColor: 'var(--lim-ink)', color: 'var(--lim-on-ink)' },
  modelHead: { display: 'flex', flexDirection: 'column', gap: '14px' },
  modelTier: {
    alignSelf: 'flex-start',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.6875rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'var(--lim-ultra)',
  },
  modelTierLead: { color: 'var(--lim-ultra-pale)' },
  modelName: {
    margin: 0,
    fontStretch: '110%',
    fontWeight: 560,
    fontSize: 'clamp(1.75rem, 2.4vw, 2.25rem)',
    letterSpacing: '-0.035em',
    lineHeight: 1,
  },
  modelBlurb: { margin: 0, marginTop: '18px', fontSize: '1rem', lineHeight: 1.55, color: 'var(--lim-text-2)' },
  modelBlurbLead: { color: 'var(--lim-on-ink-2)' },
  specs: { margin: 0, marginTop: 'auto', paddingTop: '32px' },
  spec: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '16px',
    paddingTop: '11px',
    paddingBottom: '11px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
    fontSize: '0.9375rem',
  },
  specLead: { borderTopColor: 'var(--lim-ink-line)' },
  specK: { color: 'var(--lim-text-3)' },
  specKLead: { color: 'var(--lim-on-ink-2)' },
  specV: { margin: 0, fontWeight: 560, fontVariantNumeric: 'tabular-nums' },
  price: {
    margin: 0,
    marginTop: '18px',
    paddingTop: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.8125rem',
    color: 'var(--lim-text-2)',
  },
  priceLead: { borderTopColor: 'var(--lim-ink-line)', color: 'var(--lim-on-ink)' },
  benchHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '12px 32px',
    marginTop: 'clamp(80px, 9vw, 128px)',
    marginBottom: '32px',
    paddingTop: '28px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
  },

  /* Products */
  products: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, minmax(0, 1fr))',
    gap: '16px',
    margin: 0,
    padding: 0,
    listStyle: 'none',
    // StyleX doesn't order overlapping media queries; keep the ranges disjoint.
    '@media (min-width: 640px) and (max-width: 1023px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    '@media (max-width: 639px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  product: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    padding: '14px',
    paddingBottom: '24px',
    borderRadius: '18px',
    backgroundColor: 'var(--lim-paper)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    transitionProperty: 'border-color, transform',
    transitionDuration: '320ms',
    transitionTimingFunction: 'var(--lim-ease)',
    ':hover': { borderColor: 'rgba(36, 51, 224, 0.45)' },
    ':focus-within': { borderColor: 'var(--lim-ultra)' },
  },
  productThird: { gridColumn: 'span 2', '@media (max-width: 1023px)': { gridColumn: 'auto' } },
  productHalf: { gridColumn: 'span 3', '@media (max-width: 1023px)': { gridColumn: 'auto' } },
  productLast: {
    gridColumn: 'span 3',
    '@media (min-width: 640px) and (max-width: 1023px)': { gridColumn: '1 / -1' },
    '@media (max-width: 639px)': { gridColumn: 'auto' },
  },
  productMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginTop: '22px',
    paddingLeft: '10px',
    paddingRight: '10px',
  },
  productName: { margin: 0, fontStretch: '110%', fontWeight: 580, fontSize: '1.5rem', letterSpacing: '-0.03em' },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.6875rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--lim-text-2)',
  },
  pillLive: { borderColor: 'rgba(44, 148, 102, 0.35)', color: '#1F6E4B' },
  pillDot: { width: '6px', height: '6px', borderRadius: '50%', backgroundColor: 'var(--lim-ok)' },
  productBlurb: {
    margin: 0,
    marginTop: '10px',
    paddingLeft: '10px',
    paddingRight: '10px',
    fontSize: '1rem',
    lineHeight: 1.55,
    color: 'var(--lim-text-2)',
    flexGrow: 1,
  },
  productCta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    alignSelf: 'flex-start',
    minHeight: '44px',
    marginTop: '14px',
    marginLeft: '10px',
    fontWeight: 580,
    fontSize: '0.96875rem',
    color: 'var(--lim-ultra)',
    textDecoration: 'none',
    borderRadius: '6px',
    ':focus-visible': focusRing,
    // Whole card is the hit area; the link keeps the accessible name short.
    '::after': { content: '""', position: 'absolute', inset: 0, borderRadius: '18px' },
  },

  /* Platform */
  platformGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 0.9fr) minmax(0, 1.1fr)',
    gap: 'clamp(40px, 6vw, 96px)',
    alignItems: 'start',
    '@media (max-width: 1023px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  features: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '28px 32px',
    marginTop: '48px',
    marginBottom: 0,
    padding: 0,
    listStyle: 'none',
    '@media (max-width: 539px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  feature: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    paddingTop: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ink-line)',
  },
  featureTitle: { fontWeight: 580, fontSize: '1.0625rem', color: 'var(--lim-on-ink)' },
  featureBody: { fontSize: '0.9375rem', lineHeight: 1.55, color: 'var(--lim-on-ink-2)' },
  pricing: { marginTop: 'clamp(72px, 8vw, 112px)' },
  table: {
    width: '100%',
    marginTop: '24px',
    borderCollapse: 'collapse',
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--lim-on-ink)',
  },
  th: {
    paddingTop: '12px',
    paddingBottom: '12px',
    textAlign: 'left',
    fontFamily: 'var(--lim-mono)',
    fontWeight: 400,
    fontSize: '0.75rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--lim-on-ink-2)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-ink-line)',
  },
  td: {
    paddingTop: '18px',
    paddingBottom: '18px',
    fontSize: '1.0625rem',
    '@media (max-width: 539px)': { fontSize: '0.9375rem' },
    textAlign: 'left',
    fontWeight: 400,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-ink-line)',
  },
  tdModel: { fontWeight: 560 },
  num: { textAlign: 'right', paddingLeft: '16px' },

  /* Research */
  featured: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.1fr)',
    gap: 'clamp(32px, 5vw, 80px)',
    alignItems: 'center',
    marginTop: 'clamp(48px, 6vw, 80px)',
    padding: 'clamp(24px, 3.4vw, 48px)',
    borderRadius: '20px',
    backgroundColor: 'var(--lim-paper)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    '@media (max-width: 1023px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  featuredText: { display: 'flex', flexDirection: 'column' },
  featuredTitle: {
    margin: 0,
    marginBottom: '18px',
    fontStretch: '106%',
    fontWeight: 560,
    fontSize: 'clamp(1.5rem, 2.4vw, 2.125rem)',
    lineHeight: 1.1,
    letterSpacing: '-0.03em',
    textWrap: 'balance',
  },
  featuredFig: { margin: 0, display: 'flex', flexDirection: 'column', gap: '10px' },
  legendRow: { display: 'flex', gap: '24px', marginTop: '28px', fontSize: '0.875rem', color: 'var(--lim-text-2)' },
  legendKey: { display: 'inline-flex', alignItems: 'center', gap: '10px' },
  legendLine: {
    display: 'inline-block',
    width: '22px',
    borderTopWidth: '2px',
    borderTopStyle: 'dashed',
    borderTopColor: 'var(--lim-text-3)',
  },
  legendLineUltra: { borderTopStyle: 'solid', borderTopColor: 'var(--lim-ultra)', borderTopWidth: '3px' },
  papers: { margin: 0, marginTop: 'clamp(48px, 6vw, 72px)', padding: 0, listStyle: 'none' },
  paperItem: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
    ':last-child': { borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'var(--lim-line)' },
  },
  paper: {},
  paperSummary: {
    display: 'grid',
    gridTemplateColumns: '96px 150px minmax(0, 1fr) 28px',
    alignItems: 'center',
    gap: '20px',
    minHeight: '72px',
    paddingTop: '18px',
    paddingBottom: '18px',
    cursor: 'pointer',
    listStyle: 'none',
    borderRadius: '6px',
    '::-webkit-details-marker': { display: 'none' },
    ':focus-visible': focusRing,
    '@media (max-width: 819px)': { gridTemplateColumns: 'minmax(0, 1fr) 28px', gap: '6px 16px' },
  },
  paperDate: {
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.8125rem',
    color: 'var(--lim-text-3)',
    '@media (max-width: 819px)': { display: 'none' },
  },
  paperArea: {
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--lim-ultra)',
    '@media (max-width: 819px)': { gridColumn: '1 / 2', gridRow: '1' },
  },
  paperTitle: {
    fontStretch: '104%',
    fontWeight: 520,
    fontSize: 'clamp(1.0625rem, 1.5vw, 1.3125rem)',
    letterSpacing: '-0.02em',
    lineHeight: 1.3,
    color: 'var(--lim-text)',
    transitionProperty: 'color',
    transitionDuration: '160ms',
    ':is(summary:hover > *)': { color: 'var(--lim-ultra)' },
    '@media (max-width: 819px)': { gridColumn: '1 / 2', gridRow: '2' },
  },
  paperToggle: {
    position: 'relative',
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    '@media (max-width: 819px)': { gridColumn: '2', gridRow: '1 / 3' },
  },
  paperBar: {
    position: 'absolute',
    left: '8px',
    right: '8px',
    top: '12.5px',
    height: '1.5px',
    backgroundColor: 'var(--lim-text)',
    transitionProperty: 'transform',
    transitionDuration: '260ms',
    transitionTimingFunction: 'var(--lim-ease)',
  },
  paperBarV: {
    transform: 'rotate(90deg)',
    ':is(details[open] *)': { transform: 'rotate(0deg)' },
  },
  paperAbstract: {
    maxWidth: '44rem',
    margin: 0,
    marginLeft: 'calc(96px + 150px + 40px)',
    paddingBottom: '26px',
    fontSize: '1rem',
    lineHeight: 1.65,
    color: 'var(--lim-text-2)',
    animationName: rise,
    animationDuration: '400ms',
    animationTimingFunction: 'var(--lim-ease)',
    '@media (max-width: 819px)': { marginLeft: 0 },
  },

  /* Safety */
  safetyStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 'clamp(24px, 3vw, 48px)',
    margin: 0,
    marginTop: 'clamp(56px, 7vw, 96px)',
    '@media (max-width: 819px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  safetyStat: {
    paddingTop: '22px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(237, 232, 223, 0.35)',
  },
  safetyValue: {
    margin: 0,
    fontStretch: '112%',
    fontWeight: 520,
    fontSize: 'clamp(3.25rem, 6.4vw, 6rem)',
    lineHeight: 1,
    letterSpacing: '-0.05em',
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--lim-bone)',
  },
  safetyLabel: { margin: 0, marginTop: '14px', maxWidth: '18rem', fontSize: '1.0625rem', lineHeight: 1.5, color: '#E0E3FF' },
  safetyFoot: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: '40px',
    marginTop: 'clamp(56px, 7vw, 96px)',
  },
  safetyPoints: { display: 'grid', gap: '12px', margin: 0, padding: 0, listStyle: 'none', maxWidth: '38rem' },
  safetyPoint: {
    display: 'flex',
    gap: '14px',
    fontSize: '1.0625rem',
    lineHeight: 1.5,
    color: 'var(--lim-bone)',
    '::before': { content: '"—"', color: '#C9CEFF' },
  },

  /* Voices */
  quotes: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 'clamp(24px, 3vw, 48px)',
    margin: 0,
    marginTop: 'clamp(48px, 6vw, 80px)',
    padding: 0,
    listStyle: 'none',
    '@media (max-width: 1023px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  quote: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '32px',
    height: '100%',
    margin: 0,
    paddingTop: '24px',
    borderTopWidth: '2px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ultra)',
  },
  quoteText: {
    margin: 0,
    fontStretch: '104%',
    fontWeight: 460,
    fontSize: 'clamp(1.25rem, 1.8vw, 1.5rem)',
    lineHeight: 1.35,
    letterSpacing: '-0.02em',
    color: 'var(--lim-text)',
    textWrap: 'pretty',
  },
  quoteBy: { display: 'flex', flexDirection: 'column', gap: '2px' },
  quoteName: { fontWeight: 600, fontSize: '0.96875rem' },
  quoteRole: { fontSize: '0.9375rem', color: 'var(--lim-text-3)' },

  /* Company */
  companyGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    gap: 'clamp(48px, 7vw, 120px)',
    '@media (max-width: 1023px)': { gridTemplateColumns: 'minmax(0, 1fr)' },
  },
  clocks: { display: 'flex', flexWrap: 'wrap', gap: '28px 40px', marginTop: '48px' },
  roles: { margin: 0, marginTop: '24px', padding: 0, listStyle: 'none' },
  role: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '4px 24px',
    paddingTop: '18px',
    paddingBottom: '18px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
    '@media (max-width: 539px)': { flexDirection: 'column' },
  },
  roleTitle: { fontWeight: 560, fontSize: '1.0625rem', letterSpacing: '-0.01em' },
  roleMeta: { fontSize: '0.9375rem', color: 'var(--lim-text-3)' },
  rolesCta: { marginTop: '28px' },

  /* Closing */
  closing: { paddingTop: 'clamp(120px, 16vw, 220px)', paddingBottom: 'clamp(96px, 12vw, 160px)' },
  closingInner: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start' },
  closingTitle: {
    margin: 0,
    fontStretch: '112%',
    fontWeight: 540,
    fontSize: 'clamp(3rem, 8.6vw, 8.5rem)',
    lineHeight: 0.95,
    letterSpacing: '-0.05em',
    color: 'var(--lim-on-ink)',
  },
  closingMark: { position: 'relative', display: 'inline-block', whiteSpace: 'nowrap' },
  closingStroke: {
    position: 'absolute',
    left: '-2%',
    bottom: '-0.12em',
    width: '104%',
    height: '0.22em',
    overflow: 'visible',
  },
  closingPath: { fill: 'none', stroke: 'var(--lim-ultra)', strokeWidth: 9, strokeLinecap: 'round' },
  closingCtas: { marginTop: '56px' },
})

export const foot = stylex.create({
  wrap: {
    backgroundColor: 'var(--lim-ink)',
    color: 'var(--lim-on-ink-2)',
    paddingTop: '64px',
    paddingBottom: '48px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ink-line)',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.4fr) repeat(3, minmax(0, 1fr))',
    gap: '40px',
    '@media (max-width: 819px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  },
  brandCol: { '@media (max-width: 819px)': { gridColumn: '1 / -1' } },
  tag: { margin: 0, marginTop: '16px', maxWidth: '18rem', fontSize: '0.9375rem', lineHeight: 1.55 },
  col: {},
  colTitle: {
    margin: 0,
    marginBottom: '12px',
    fontFamily: 'var(--lim-mono)',
    fontWeight: 400,
    fontSize: '0.75rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'rgba(237, 232, 223, 0.55)',
  },
  list: { display: 'grid', margin: 0, padding: 0, listStyle: 'none' },
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '36px',
    fontSize: '0.9375rem',
    color: 'var(--lim-on-ink)',
    textDecoration: 'none',
    borderRadius: '4px',
    ':hover': { color: 'var(--lim-ultra-pale)' },
    ':focus-visible': { ...focusRing, outlineColor: 'var(--lim-ultra-pale)' },
  },
  legal: {
    display: 'grid',
    gap: '10px',
    marginTop: '64px',
    paddingTop: '24px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ink-line)',
    fontSize: '0.8125rem',
    lineHeight: 1.6,
  },
  legalNote: { margin: 0, maxWidth: '60rem', overflowWrap: 'anywhere' },
  inlineLink: {
    color: 'var(--lim-on-ink)',
    textDecorationLine: 'underline',
    textDecorationColor: 'rgba(237, 232, 223, 0.35)',
    textUnderlineOffset: '3px',
    borderRadius: '2px',
    ':hover': { color: 'var(--lim-ultra-pale)' },
    ':focus-visible': { ...focusRing, outlineColor: 'var(--lim-ultra-pale)' },
  },
})

/* ── Agent trace window ─────────────────────────────────────────── */
export const trace = stylex.create({
  window: {
    borderRadius: '20px',
    backgroundColor: 'var(--lim-ink-raised)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-ink-line)',
    overflow: 'hidden',
    fontFamily: 'var(--lim-mono)',
    color: 'var(--lim-on-ink)',
  },
  bar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    paddingTop: '14px',
    paddingBottom: '14px',
    paddingLeft: '20px',
    paddingRight: '16px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-ink-line)',
  },
  barTitle: {
    fontSize: '0.75rem',
    color: 'var(--lim-on-ink-2)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  status: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
    paddingTop: '5px',
    paddingBottom: '5px',
    paddingLeft: '10px',
    paddingRight: '12px',
    borderRadius: '999px',
    backgroundColor: 'rgba(163, 172, 255, 0.12)',
    color: 'var(--lim-ultra-pale)',
    fontSize: '0.75rem',
  },
  statusDone: { backgroundColor: 'rgba(44, 148, 102, 0.16)', color: '#7FD8AE' },
  statusDot: { width: '7px', height: '7px', borderRadius: '50%' },
  statusDotLive: {
    backgroundColor: 'var(--lim-ultra-pale)',
    animationName: blink,
    animationDuration: '1.2s',
    animationIterationCount: 'infinite',
    '@media (prefers-reduced-motion: reduce)': { animationName: 'none' },
  },
  statusDotDone: { backgroundColor: '#7FD8AE' },
  task: {
    display: 'flex',
    gap: '16px',
    paddingTop: '18px',
    paddingBottom: '18px',
    paddingLeft: '20px',
    paddingRight: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-ink-line)',
  },
  taskLabel: {
    flexShrink: 0,
    paddingTop: '3px',
    fontSize: '0.6875rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'var(--lim-on-ink-2)',
  },
  taskText: {
    margin: 0,
    fontFamily: 'var(--lim-display)',
    fontSize: 'clamp(1rem, 1.5vw, 1.1875rem)',
    lineHeight: 1.45,
    color: 'var(--lim-on-ink)',
  },
  body: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.25fr) minmax(0, 1fr)',
    minHeight: '400px',
    '@media (max-width: 1023px)': { gridTemplateColumns: 'minmax(0, 1fr)', minHeight: 0 },
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    margin: 0,
    paddingTop: '14px',
    paddingBottom: '14px',
    paddingLeft: '10px',
    paddingRight: '10px',
    listStyle: 'none',
  },
  row: {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: '26px 92px minmax(0, 1fr)',
    alignItems: 'center',
    gap: '10px',
    paddingTop: '9px',
    paddingBottom: '9px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '10px',
    overflow: 'hidden',
    fontSize: '0.8125rem',
    '@media (max-width: 539px)': { gridTemplateColumns: '26px minmax(0, 1fr)' },
  },
  rowDone: { backgroundColor: 'rgba(44, 148, 102, 0.12)' },
  icon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    borderRadius: '8px',
    backgroundColor: 'rgba(237, 232, 223, 0.06)',
    color: 'var(--lim-on-ink-2)',
  },
  iconVerify: { backgroundColor: 'rgba(163, 172, 255, 0.16)', color: 'var(--lim-ultra-pale)' },
  iconDone: { backgroundColor: 'rgba(44, 148, 102, 0.22)', color: '#7FD8AE' },
  rowLabel: { color: 'var(--lim-on-ink)', '@media (max-width: 539px)': { display: 'none' } },
  rowDetail: { color: 'var(--lim-on-ink-2)', overflowWrap: 'anywhere' },
  scan: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    backgroundImage: 'linear-gradient(90deg, transparent, rgba(163, 172, 255, 0.12), transparent)',
    animationName: scan,
    animationDuration: '1.3s',
    animationIterationCount: 'infinite',
    '@media (prefers-reduced-motion: reduce)': { animationName: 'none' },
  },
  diff: {
    display: 'flex',
    flexDirection: 'column',
    paddingTop: '18px',
    paddingBottom: '18px',
    paddingLeft: '20px',
    paddingRight: '20px',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--lim-ink-line)',
    backgroundColor: 'rgba(14, 16, 36, 0.45)',
    '@media (max-width: 1023px)': {
      borderLeftWidth: 0,
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'var(--lim-ink-line)',
    },
  },
  diffTitle: { fontSize: '0.75rem', color: 'var(--lim-on-ink-2)', marginBottom: '14px' },
  diffPre: {
    margin: 0,
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.78125rem',
    lineHeight: 1.75,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    color: 'var(--lim-on-ink-2)',
    minHeight: '14em',
  },
  diffLine: { display: 'block', paddingLeft: '8px', borderRadius: '4px' },
  diffAdd: { backgroundColor: 'rgba(44, 148, 102, 0.16)', color: '#A8EBCB' },
  diffDel: { backgroundColor: 'rgba(224, 82, 82, 0.14)', color: '#F2B1B1', textDecorationLine: 'line-through', textDecorationColor: 'rgba(242, 177, 177, 0.4)' },
  diffEmpty: { color: 'rgba(179, 181, 202, 0.6)' },
  stats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    margin: 0,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ink-line)',
    '@media (max-width: 639px)': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
  },
  stat: {
    paddingTop: '16px',
    paddingBottom: '18px',
    paddingLeft: '20px',
    paddingRight: '20px',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'var(--lim-ink-line)',
    ':last-child': { borderRightWidth: 0 },
  },
  statK: { fontSize: '0.6875rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--lim-on-ink-2)' },
  statV: {
    margin: 0,
    marginTop: '6px',
    fontFamily: 'var(--lim-display)',
    fontStretch: '108%',
    fontWeight: 540,
    fontSize: '1.375rem',
    letterSpacing: '-0.02em',
    fontVariantNumeric: 'tabular-nums',
    color: 'var(--lim-on-ink)',
  },
})

/* ── Code window ────────────────────────────────────────────────── */
export const code = stylex.create({
  window: {
    borderRadius: '20px',
    overflow: 'hidden',
    backgroundColor: '#080A18',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-ink-line)',
  },
  bar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '8px',
    paddingRight: '18px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--lim-ink-line)',
  },
  tabs: { display: 'flex', gap: '2px' },
  tab: {
    minHeight: '40px',
    paddingLeft: '14px',
    paddingRight: '14px',
    borderRadius: '10px',
    backgroundColor: 'transparent',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.8125rem',
    color: 'var(--lim-on-ink-2)',
    cursor: 'pointer',
    ':hover': { color: 'var(--lim-on-ink)' },
    ':focus-visible': { ...focusRing, outlineColor: 'var(--lim-ultra-pale)', outlineOffset: '-2px' },
    ':is([data-state="active"])': { backgroundColor: 'rgba(237, 232, 223, 0.08)', color: 'var(--lim-on-ink)' },
  },
  barIcon: { color: 'var(--lim-on-ink-2)' },
  content: { outline: 'none' },
  pre: {
    margin: 0,
    minHeight: '22.5em',
    paddingTop: '22px',
    paddingBottom: '22px',
    paddingLeft: '24px',
    paddingRight: '24px',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.84375rem',
    lineHeight: 1.7,
    color: '#D9DBEA',
    whiteSpace: 'pre',
    overflowX: 'auto',
    '@media (max-width: 539px)': { fontSize: '0.75rem' },
  },
  caret: {
    display: 'inline-block',
    width: '8px',
    height: '1.15em',
    marginLeft: '1px',
    verticalAlign: 'text-bottom',
    backgroundColor: 'var(--lim-ultra-pale)',
    animationName: blink,
    animationDuration: '1s',
    animationIterationCount: 'infinite',
  },
  output: {
    minHeight: '10.5em',
    paddingTop: '16px',
    paddingBottom: '20px',
    paddingLeft: '24px',
    paddingRight: '24px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-ink-line)',
    backgroundColor: 'rgba(36, 51, 224, 0.07)',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.78125rem',
    lineHeight: 1.8,
    color: 'var(--lim-on-ink-2)',
    whiteSpace: 'pre',
    overflowX: 'auto',
  },
  outputLabel: {
    display: 'block',
    marginBottom: '6px',
    fontSize: '0.6875rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: 'var(--lim-ultra-pale)',
  },
  outLine: {},
  outDone: { color: '#A8EBCB' },
  tStr: { color: '#B9C0FF' },
  tNum: { color: '#F2C48D' },
  tCom: { color: '#6E7190' },
  tKey: { color: '#8C97FF' },
})

/* ── Benchmarks ─────────────────────────────────────────────────── */
export const bench = stylex.create({
  wrap: {},
  legend: { display: 'flex', gap: '24px', marginBottom: '20px', fontSize: '0.875rem', color: 'var(--lim-text-2)' },
  key: { display: 'inline-flex', alignItems: 'center', gap: '10px' },
  swatch: { width: '14px', height: '14px', borderRadius: '3px' },
  swatchNow: { backgroundColor: 'var(--lim-ultra)' },
  swatchPrev: { backgroundColor: 'rgba(14, 16, 36, 0.22)' },
  list: { margin: 0, padding: 0, listStyle: 'none' },
  row: {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: 'minmax(180px, 0.42fr) minmax(0, 1fr)',
    alignItems: 'center',
    gap: '24px',
    paddingTop: '16px',
    paddingBottom: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--lim-line)',
    '@media (max-width: 639px)': { gridTemplateColumns: 'minmax(0, 1fr)', gap: '10px' },
  },
  label: { display: 'flex', flexDirection: 'column', gap: '2px' },
  name: { fontWeight: 560, fontSize: '1rem' },
  note: { fontSize: '0.875rem', color: 'var(--lim-text-3)' },
  bars: { display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 4.5em', alignItems: 'center', columnGap: '14px', rowGap: '6px' },
  track: { position: 'relative', height: '22px' },
  trackPrev: { height: '12px' },
  fill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    borderRadius: '3px',
    transformOrigin: 'left center',
  },
  fillNow: { backgroundColor: 'var(--lim-ultra)' },
  fillPrev: { backgroundColor: 'rgba(14, 16, 36, 0.16)' },
  value: {
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.875rem',
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'right',
    color: 'var(--lim-text)',
  },
  valuePrev: { fontSize: '0.75rem', color: 'var(--lim-text-3)' },
  sr: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  },
})

/* ── Chart ──────────────────────────────────────────────────────── */
export const chart = stylex.create({
  svg: { width: '100%', height: 'auto', overflow: 'visible' },
  grid: { stroke: 'rgba(14, 16, 36, 0.08)', strokeWidth: 1 },
  axis: { fontFamily: 'var(--lim-mono)', fontSize: '11px', fill: 'var(--lim-text-3)' },
  axisTitle: { fontFamily: 'var(--lim-mono)', fontSize: '11px', fill: 'var(--lim-text-3)', letterSpacing: '0.04em' },
  base: { fill: 'none', stroke: 'var(--lim-text-3)', strokeWidth: 2, strokeDasharray: '5 6', strokeLinecap: 'round' },
  guided: { fill: 'none', stroke: 'var(--lim-ultra)', strokeWidth: 3.5, strokeLinecap: 'round', strokeLinejoin: 'round' },
  dotBase: { fill: 'var(--lim-text-3)' },
  dotGuided: { fill: 'var(--lim-ultra)' },
  endLabel: { fontFamily: 'var(--lim-mono)', fontSize: '13px', fill: 'var(--lim-text-2)' },
  endGuided: { fill: 'var(--lim-ultra)', fontWeight: 600 },
})

/* ── Office clock ───────────────────────────────────────────────── */
export const clock = stylex.create({
  wrap: { display: 'flex', alignItems: 'center', gap: '14px' },
  face: { width: '48px', height: '48px', flexShrink: 0 },
  ring: { fill: 'var(--lim-bone)', stroke: 'var(--lim-line)', strokeWidth: 1 },
  tick: { stroke: 'var(--lim-text-3)', strokeWidth: 1.2, strokeLinecap: 'round' },
  hour: { stroke: 'var(--lim-text)', strokeWidth: 2.4, strokeLinecap: 'round' },
  minute: { stroke: 'var(--lim-ultra)', strokeWidth: 1.6, strokeLinecap: 'round' },
  pin: { fill: 'var(--lim-text)' },
  city: { fontWeight: 560, fontSize: '0.96875rem' },
  time: { fontFamily: 'var(--lim-mono)', fontSize: '0.8125rem', color: 'var(--lim-text-3)', fontVariantNumeric: 'tabular-nums' },
})

/* ── Product illustrations ──────────────────────────────────────── */
const loop = {
  animationIterationCount: 'infinite',
  '@media (prefers-reduced-motion: reduce)': { animationName: 'none' },
} as const

export const art = stylex.create({
  box: {
    position: 'relative',
    height: '188px',
    borderRadius: '12px',
    overflow: 'hidden',
    backgroundColor: 'var(--lim-bone)',
    backgroundImage:
      'radial-gradient(circle at 1px 1px, rgba(14, 16, 36, 0.09) 1px, transparent 0)',
    backgroundSize: '16px 16px',
  },
  center: { display: 'flex', alignItems: 'center', justifyContent: 'center' },
  chat: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    gap: '8px',
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '16px',
    paddingRight: '16px',
  },
  bubble: {
    maxWidth: '82%',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: '14px',
    fontSize: '0.78125rem',
    lineHeight: 1.4,
    animationName: bubbleIn,
    animationDuration: '7s',
    animationFillMode: 'both',
    ...loop,
  },
  bubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: 'var(--lim-ink)',
    color: 'var(--lim-on-ink)',
    borderBottomRightRadius: '4px',
  },
  bubbleBot: {
    alignSelf: 'flex-start',
    backgroundColor: 'var(--lim-paper)',
    color: 'var(--lim-text)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--lim-line)',
    borderBottomLeftRadius: '4px',
    animationDelay: '0.6s',
  },
  typing: { display: 'inline-flex', gap: '4px', animationDelay: '1.4s' },
  dot: {
    width: '5px',
    height: '5px',
    borderRadius: '50%',
    backgroundColor: 'var(--lim-ultra)',
    animationName: typingDot,
    animationDuration: '1.2s',
    ...loop,
  },
  dot2: { animationDelay: '0.15s' },
  dot3: { animationDelay: '0.3s' },
  svg: { position: 'absolute', inset: 0, width: '100%', height: '100%' },
  contour: { fill: 'none', stroke: 'rgba(14, 16, 36, 0.12)', strokeWidth: 1 },
  route: {
    fill: 'none',
    stroke: 'var(--lim-ultra)',
    strokeWidth: 2.5,
    strokeLinecap: 'round',
    strokeDasharray: '260',
    animationName: dash,
    animationDuration: '4.5s',
    animationTimingFunction: 'var(--lim-ease)',
    ...loop,
  },
  pin: { fill: 'var(--lim-paper)', stroke: 'var(--lim-ink)', strokeWidth: 2 },
  pinMid: { stroke: 'var(--lim-ultra)' },
  pinEnd: { fill: 'var(--lim-ultra)', stroke: 'var(--lim-ultra)' },
  breathHalo: {
    position: 'absolute',
    width: '128px',
    height: '128px',
    borderRadius: '50%',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(36, 51, 224, 0.4)',
    animationName: halo,
    animationDuration: '8s',
    animationTimingFunction: 'cubic-bezier(0.45, 0, 0.55, 1)',
    ...loop,
  },
  breathOrb: {
    width: '96px',
    height: '96px',
    borderRadius: '50%',
    backgroundImage: 'radial-gradient(circle at 35% 30%, #A3ACFF, #2433E0 62%, #1A25B0)',
    animationName: breathe,
    animationDuration: '8s',
    animationTimingFunction: 'cubic-bezier(0.45, 0, 0.55, 1)',
    ...loop,
  },
  breathLabel: {
    position: 'absolute',
    bottom: '14px',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.6875rem',
    letterSpacing: '0.08em',
    color: 'var(--lim-text-3)',
  },
  term: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: '10px',
    paddingLeft: '18px',
    paddingRight: '18px',
    backgroundColor: 'var(--lim-ink)',
    backgroundImage: 'none',
    fontFamily: 'var(--lim-mono)',
    fontSize: '0.75rem',
  },
  termLine: {
    color: 'var(--lim-on-ink)',
    whiteSpace: 'nowrap',
    animationName: termType,
    animationDuration: '6s',
    animationFillMode: 'both',
    ...loop,
  },
  termDim: { color: 'var(--lim-on-ink-2)', animationDelay: '0.8s' },
  termOk: { color: '#7FD8AE', animationDelay: '1.6s' },
  cursor: {
    display: 'inline-block',
    width: '7px',
    height: '1.1em',
    marginLeft: '6px',
    verticalAlign: 'text-bottom',
    backgroundColor: '#7FD8AE',
    animationName: blink,
    animationDuration: '1s',
    ...loop,
  },
  apiBrace: {
    fontFamily: 'var(--lim-mono)',
    fontSize: '4.5rem',
    lineHeight: 1,
    color: 'var(--lim-ink)',
    fontWeight: 300,
  },
  apiTrack: {
    position: 'relative',
    width: '160px',
    height: '2px',
    marginLeft: '6px',
    marginRight: '6px',
    backgroundColor: 'rgba(14, 16, 36, 0.12)',
  },
  apiPacket: {
    position: 'absolute',
    left: 0,
    top: '-4px',
    width: '10px',
    height: '10px',
    borderRadius: '3px',
    backgroundColor: 'var(--lim-ultra)',
    animationName: packet,
    animationDuration: '2.4s',
    animationTimingFunction: 'cubic-bezier(0.45, 0, 0.55, 1)',
    ...loop,
  },
  apiPacket2: { animationDelay: '0.8s' },
  apiPacket3: { animationDelay: '1.6s' },
})
