import * as stylex from '@stylexjs/stylex'

/**
 * Toy-world pieces that only the redesigned pages use: the clay globe host,
 * the index hero, luggage tags. Tokens are the `.trips` vars in index.css.
 */
const display = '"Bricolage Grotesque", "Archivo", system-ui, sans-serif'
const mono = '"Fragment Mono", ui-monospace, SFMono-Regular, Menlo, monospace'
const line = 'var(--trips-line)'
const shadow = 'var(--trips-shadow)'
const fill = 'var(--ta-fill)'
const fillInk = 'var(--trips-fill-ink)'
const focus = 'var(--trips-focus)'
const ink = 'var(--trips-ink)'
const ink2 = 'var(--trips-ink-secondary)'
const ink3 = 'var(--trips-ink-tertiary)'
const surface = 'var(--trips-surface)'
const canvas = 'var(--trips-canvas)'
const spring = 'cubic-bezier(0.34, 1.56, 0.64, 1)'

const MOBILE = '@media (max-width: 899.98px)'
const DESKTOP = '@media (min-width: 900px)'

export const globe = stylex.create({
  host: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: '16rem',
    isolation: 'isolate',
  },
  hostRegion: {
    minHeight: '14rem',
  },
  still: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    transitionProperty: 'opacity',
    transitionDuration: '500ms',
  },
  stillHidden: {
    opacity: 0,
  },
  live: {
    position: 'absolute',
    inset: 0,
    opacity: 0,
    transitionProperty: 'opacity',
    transitionDuration: '700ms',
  },
  liveShown: {
    opacity: 1,
  },
  label: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 2,
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
    maxWidth: '16rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    paddingBlock: '0.3rem',
    paddingInline: '0.75rem',
    borderRadius: '999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: surface,
    boxShadow: `0 3px 0 ${shadow}`,
    color: ink,
    fontFamily: display,
    fontWeight: 700,
    fontSize: '0.875rem',
    opacity: 0,
    transitionProperty: 'opacity',
    transitionDuration: '160ms',
  },
})

export const index = stylex.create({
  page: {
    marginInline: 'auto',
    maxWidth: '76rem',
    paddingInline: { default: '1rem', '@media (min-width: 640px)': '1.5rem' },
    paddingTop: '0.5rem',
  },
  hero: {
    display: 'grid',
    alignItems: 'center',
    gap: '1rem',
    [MOBILE]: {
      gridTemplateAreas: '"globe" "copy"',
    },
    [DESKTOP]: {
      gridTemplateAreas: '"copy globe"',
      gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1.15fr)',
      gap: '2rem',
      minHeight: '34rem',
    },
  },
  heroCopy: {
    gridArea: 'copy',
    minWidth: 0,
  },
  heroGlobe: {
    gridArea: 'globe',
    minWidth: 0,
    [MOBILE]: {
      height: 'min(21rem, 86vw)',
      marginInline: '-0.5rem',
    },
    [DESKTOP]: {
      height: '36rem',
      marginRight: '-2rem',
    },
  },
  heroStamp: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    paddingBlock: '0.25rem',
    paddingInline: '0.65rem',
    borderWidth: '2px',
    borderStyle: 'dashed',
    borderColor: line,
    borderRadius: '0.5rem',
    backgroundColor: fill,
    color: fillInk,
    fontFamily: mono,
    fontSize: '0.75rem',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    transform: 'rotate(-2.5deg)',
  },
  heroTitle: {
    marginTop: '0.75rem',
    fontFamily: display,
    fontSize: 'clamp(3.75rem, 11vw, 7.25rem)',
    lineHeight: 0.88,
    fontWeight: 800,
    letterSpacing: '-0.045em',
    fontStretch: '84%',
    color: ink,
  },
  heroLede: {
    marginTop: '1rem',
    maxWidth: '34ch',
    fontSize: '1.0625rem',
    lineHeight: 1.55,
    color: ink2,
  },
  heroActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.75rem',
    marginTop: '1.5rem',
  },
  search: {
    position: 'relative',
    marginTop: '1.5rem',
    maxWidth: '26rem',
  },
  searchIcon: {
    position: 'absolute',
    left: '1rem',
    top: '50%',
    width: '1.125rem',
    height: '1.125rem',
    transform: 'translateY(-50%)',
    color: ink2,
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    height: '3rem',
    paddingLeft: '2.75rem',
    paddingRight: '3rem',
    borderRadius: '999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: surface,
    boxShadow: `0 3px 0 ${shadow}`,
    color: ink,
    fontSize: '1rem',
    appearance: 'none',
    '::placeholder': { color: ink3 },
    '::-webkit-search-cancel-button': { display: 'none' },
    ':focus-visible': {
      outline: 'none',
      boxShadow: `0 3px 0 ${shadow}, 0 0 0 5px ${focus}`,
    },
  },
  searchClear: {
    position: 'absolute',
    right: '0.15rem',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'grid',
    placeItems: 'center',
    width: '2.75rem',
    height: '2.75rem',
    borderRadius: '999px',
    color: ink2,
    ':hover': { color: ink },
    ':focus-visible': { outline: 'none', boxShadow: `0 0 0 3px ${focus}` },
  },
  kbd: {
    position: 'absolute',
    right: '0.9rem',
    top: '50%',
    transform: 'translateY(-50%)',
    pointerEvents: 'none',
    paddingInline: '0.4rem',
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--trips-ink) 35%, transparent)',
    borderBottomWidth: '3px',
    borderRadius: '0.4rem',
    fontFamily: mono,
    fontSize: '0.75rem',
    color: ink2,
  },
  shortcutHint: {
    marginTop: '0.85rem',
    fontFamily: mono,
    fontSize: '0.75rem',
    color: ink3,
    '@media (hover: none)': { display: 'none' },
  },
  kbdInline: {
    display: 'inline-block',
    minWidth: '1.35rem',
    marginRight: '0.3rem',
    paddingInline: '0.3rem',
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: 'color-mix(in srgb, var(--trips-ink) 30%, transparent)',
    borderBottomWidth: '3px',
    borderRadius: '0.35rem',
    textAlign: 'center',
    fontFamily: mono,
    color: ink2,
  },
  listTop: {
    marginTop: '2rem',
  },
  buckets: {
    display: 'grid',
    gap: '2.75rem',
    marginTop: '1.5rem',
  },
  bucketTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.6rem',
    marginBottom: '1.1rem',
  },
  bucketCount: {
    display: 'inline-grid',
    placeItems: 'center',
    minWidth: '1.75rem',
    height: '1.75rem',
    paddingInline: '0.35rem',
    borderRadius: '999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: fill,
    color: fillInk,
    fontFamily: mono,
    fontSize: '0.75rem',
  },
  tagGrid: {
    display: 'grid',
    gap: '1.25rem',
    gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 20rem), 1fr))',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  tag: {
    position: 'relative',
    display: 'flex',
    minHeight: '9.75rem',
    height: '100%',
    borderRadius: '1.25rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: surface,
    boxShadow: `0 4px 0 ${shadow}`,
    transitionProperty: 'transform, box-shadow',
    transitionDuration: '260ms',
    transitionTimingFunction: spring,
    '@media (hover: hover)': {
      ':hover': {
        transform: 'translateY(-4px) rotate(-0.8deg)',
        boxShadow: `0 8px 0 ${shadow}`,
      },
    },
    ':active': {
      transform: 'translateY(3px)',
      boxShadow: `0 1px 0 ${shadow}`,
    },
    ':focus-within': {
      boxShadow: `0 4px 0 ${shadow}, 0 0 0 5px ${focus}`,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'box-shadow',
      transform: 'none',
    },
  },
  tagLink: {
    position: 'absolute',
    inset: 0,
    zIndex: 1,
    borderRadius: 'inherit',
    outline: 'none',
  },
  tagStub: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
    width: '5.25rem',
    flexShrink: 0,
    paddingBlock: '1rem',
    paddingInline: '0.4rem',
    borderTopLeftRadius: '1.1rem',
    borderBottomLeftRadius: '1.1rem',
    borderRightWidth: '2px',
    borderRightStyle: 'dashed',
    borderRightColor: line,
    backgroundColor: fill,
    color: fillInk,
  },
  tagEyelet: {
    position: 'relative',
    width: '1.15rem',
    height: '1.15rem',
    borderRadius: '999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: canvas,
    boxShadow: '0 0 0 4px color-mix(in srgb, var(--trips-surface) 75%, transparent)',
    // The string loop, tied through the eyelet and trailing off the top.
    '::after': {
      content: '""',
      position: 'absolute',
      left: '-0.15rem',
      bottom: '0.2rem',
      width: '1.4rem',
      height: '2.6rem',
      borderWidth: '2px',
      borderStyle: 'solid',
      borderColor: line,
      borderBottomColor: 'transparent',
      borderRightColor: 'transparent',
      borderRadius: '999px',
      transform: 'rotate(28deg)',
      transformOrigin: 'bottom center',
    },
  },
  tagCode: {
    fontFamily: display,
    fontWeight: 800,
    fontSize: '1.55rem',
    lineHeight: 1,
    letterSpacing: '0.01em',
    fontStretch: '80%',
    maxWidth: '100%',
    overflowWrap: 'anywhere',
    textAlign: 'center',
  },
  tagStubMeta: {
    fontFamily: mono,
    fontSize: '0.6875rem',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  tagBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.3rem',
    flex: '1',
    minWidth: 0,
    paddingBlock: '1rem',
    paddingLeft: '1.1rem',
    paddingRight: '3.25rem',
  },
  tagMark: {
    alignSelf: 'flex-start',
    paddingBlock: '0.1rem',
    paddingInline: '0.45rem',
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: 'var(--ta)',
    borderRadius: '0.375rem',
    color: 'var(--ta)',
    fontFamily: mono,
    fontSize: '0.75rem',
    transform: 'rotate(-2deg)',
  },
  tagTitle: {
    marginTop: '0.3rem',
    fontFamily: display,
    fontWeight: 750,
    fontSize: '1.45rem',
    lineHeight: 1.05,
    letterSpacing: '-0.02em',
    color: ink,
  },
  tagMeta: {
    fontSize: '0.875rem',
    lineHeight: 1.4,
    color: ink2,
  },
  tagStats: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem',
    marginTop: 'auto',
    paddingTop: '0.4rem',
    fontFamily: mono,
    fontSize: '0.75rem',
    color: ink3,
  },
  tagShared: {
    paddingInline: '0.4rem',
    borderWidth: '1.5px',
    borderStyle: 'dashed',
    borderColor: 'currentColor',
    borderRadius: '999px',
  },
  tagActions: {
    position: 'absolute',
    top: '0.5rem',
    right: '0.5rem',
    zIndex: 2,
  },
  tagSkeleton: {
    height: '9.75rem',
    borderRadius: '1.25rem',
  },
  emptyCard: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '1.5rem',
    maxWidth: '44rem',
    marginTop: '2rem',
    padding: '1.5rem',
    borderRadius: '1.5rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: surface,
    boxShadow: `0 5px 0 ${shadow}`,
  },
  suitcase: {
    width: '7rem',
    height: 'auto',
    flexShrink: 0,
  },
  emptyCopy: {
    marginTop: '0.5rem',
    maxWidth: '42ch',
    lineHeight: 1.5,
    color: ink2,
  },
  emptyActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.75rem',
    marginTop: '1.25rem',
  },
  noMatch: {
    display: 'grid',
    justifyItems: 'center',
    gap: '0.4rem',
    marginTop: '2rem',
    padding: '2rem',
    borderRadius: '1.5rem',
    borderWidth: '2px',
    borderStyle: 'dashed',
    borderColor: line,
    textAlign: 'center',
  },
  noMatchBtn: {
    marginTop: '0.75rem',
  },
  planNew: {
    justifySelf: 'start',
  },
})

export const overview = stylex.create({
  coverGrid: {
    display: 'grid',
    marginInline: 'auto',
    width: '100%',
    maxWidth: '72rem',
    [MOBILE]: {
      gridTemplateAreas: '"diorama" "copy"',
      gap: '0.5rem',
    },
    [DESKTOP]: {
      gridTemplateAreas: '"copy diorama"',
      gridTemplateColumns: 'minmax(0, 1.2fr) minmax(0, 1fr)',
      alignItems: 'center',
      gap: '2rem',
    },
  },
  coverCopy: {
    gridArea: 'copy',
    minWidth: 0,
  },
  coverDiorama: {
    gridArea: 'diorama',
    minWidth: 0,
    [MOBILE]: {
      height: '15rem',
      marginTop: '-1rem',
      marginInline: '-1rem',
    },
    [DESKTOP]: {
      height: '25rem',
      marginRight: '-1.5rem',
    },
  },
})

export const pack = stylex.create({
  headerGrid: {
    display: 'grid',
    alignItems: 'center',
    marginInline: 'auto',
    width: '100%',
    maxWidth: '56rem',
    gap: '1.5rem',
    '@media (min-width: 720px)': {
      gridTemplateColumns: 'minmax(0, 1.25fr) minmax(0, 1fr)',
      gap: '2.5rem',
    },
  },
  headerCopy: {
    minWidth: 0,
  },
  stamp: {
    display: 'inline-block',
    paddingBlock: '0.2rem',
    paddingInline: '0.6rem',
    borderWidth: '2px',
    borderStyle: 'dashed',
    borderColor: line,
    borderRadius: '0.5rem',
    fontFamily: mono,
    fontSize: '0.75rem',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    transform: 'rotate(-3deg)',
  },
  title: {
    marginTop: '0.75rem',
    fontFamily: display,
    fontWeight: 800,
    fontSize: 'clamp(2.75rem, 8vw, 4.75rem)',
    lineHeight: 0.92,
    letterSpacing: '-0.04em',
    fontStretch: '86%',
  },
  suitcase: {
    position: 'relative',
    justifySelf: 'center',
    width: 'min(100%, 19rem)',
    aspectRatio: '5 / 4',
    '@media (max-width: 719.98px)': {
      width: 'min(100%, 15rem)',
    },
  },
  handle: {
    position: 'absolute',
    top: 0,
    left: '50%',
    width: '32%',
    height: '18%',
    transform: 'translateX(-50%)',
    borderWidth: '5px',
    borderStyle: 'solid',
    borderColor: line,
    borderBottomWidth: 0,
    borderTopLeftRadius: '1.2rem',
    borderTopRightRadius: '1.2rem',
  },
  body: {
    position: 'absolute',
    insetInline: 0,
    top: '14%',
    bottom: '7%',
    borderRadius: '1.6rem',
    borderWidth: '3px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: 'var(--toy-peach)',
    backgroundImage: 'radial-gradient(120% 80% at 30% 15%, rgb(255 255 255 / 0.45), transparent 55%)',
    boxShadow: `0 6px 0 ${shadow}, inset 0 -10px 0 rgb(31 36 64 / 0.08)`,
  },
  strap: {
    position: 'absolute',
    top: '-3px',
    bottom: '-3px',
    width: '10%',
    borderInlineWidth: '2.5px',
    borderInlineStyle: 'solid',
    borderInlineColor: line,
    backgroundColor: 'var(--toy-sky)',
  },
  strapLeft: { left: '22%' },
  strapRight: { right: '22%' },
  bodyHint: {
    position: 'absolute',
    inset: '30% 12% auto',
    paddingBlock: '0.3rem',
    paddingInline: '0.6rem',
    borderRadius: '0.5rem',
    backgroundColor: 'rgb(255 253 246 / 0.85)',
    color: '#1f2440',
    fontFamily: mono,
    fontSize: '0.6875rem',
    textAlign: 'center',
  },
  sticker: {
    position: 'absolute',
    zIndex: 1,
    maxWidth: '46%',
    paddingBlock: '0.3rem',
    paddingInline: '0.6rem',
    borderRadius: '0.6rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: '#1f2440',
    boxShadow: '0 2px 0 #1f2440',
    color: '#1f2440',
    fontFamily: display,
    fontWeight: 800,
    fontSize: '0.9375rem',
    lineHeight: 1.1,
    overflowWrap: 'anywhere',
  },
  stickerRound: {
    borderRadius: '999px',
    paddingInline: '0.8rem',
  },
  wheel: {
    position: 'absolute',
    bottom: 0,
    width: '9%',
    aspectRatio: '1',
    borderRadius: '999px',
    backgroundColor: ink,
  },
  wheelLeft: { left: '14%' },
  wheelRight: { right: '14%' },
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 80,
    display: 'grid',
    placeItems: 'center',
    padding: '1rem',
    backgroundColor: 'color-mix(in srgb, var(--trips-canvas) 90%, transparent)',
    backdropFilter: 'blur(8px)',
  },
  overlayCard: {
    display: 'grid',
    justifyItems: 'center',
    gap: '0.6rem',
    width: 'min(30rem, 100%)',
    textAlign: 'center',
  },
  overlayGlobe: {
    width: 'min(24rem, 86vw)',
    height: 'min(24rem, 86vw)',
  },
  overlayTitle: {
    fontFamily: display,
    fontWeight: 800,
    fontSize: '2rem',
    letterSpacing: '-0.03em',
    lineHeight: 1,
    color: ink,
  },
  overlayLine: {
    fontSize: '1.0625rem',
    color: ink2,
  },
  overlayClock: {
    fontFamily: mono,
    fontSize: '0.75rem',
    fontVariantNumeric: 'tabular-nums',
    color: ink3,
  },
})

export const day = stylex.create({
  postcard: {
    position: 'relative',
    paddingBlock: '1.25rem',
    paddingInline: '1.1rem',
    borderRadius: '1.5rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: surface,
    boxShadow: `0 6px 0 ${shadow}`,
    '@media (min-width: 640px)': {
      paddingBlock: '1.75rem',
      paddingInline: '2.25rem',
    },
  },
  stamp: {
    position: 'relative',
    float: 'right',
    display: 'grid',
    justifyItems: 'center',
    gap: '0.15rem',
    width: '4.25rem',
    marginLeft: '0.75rem',
    marginBottom: '0.5rem',
    paddingBlock: '0.55rem',
    paddingInline: '0.3rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: fill,
    boxShadow: `0 3px 0 ${shadow}`,
    color: fillInk,
    outline: '2.5px dashed var(--trips-surface)',
    outlineOffset: '-7px',
    transform: 'rotate(5deg)',
    '@media (min-width: 640px)': {
      width: '5.5rem',
      marginRight: '-0.75rem',
    },
  },
  stampMonth: {
    fontFamily: mono,
    fontSize: '0.625rem',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  stampDay: {
    fontFamily: display,
    fontWeight: 800,
    fontSize: '2rem',
    lineHeight: 0.9,
    '@media (min-width: 640px)': { fontSize: '2.6rem' },
  },
  stampWeek: {
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: mono,
    fontSize: '0.5625rem',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  postmark: {
    position: 'absolute',
    left: '-2.6rem',
    bottom: '-0.9rem',
    width: '4.5rem',
    height: 'auto',
    color: 'color-mix(in srgb, var(--trips-ink) 45%, transparent)',
    transform: 'rotate(-14deg)',
    pointerEvents: 'none',
  },
  passes: {
    display: 'grid',
    gap: '1rem',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  pass: {
    display: 'grid',
    gridTemplateColumns: '3.25rem minmax(0, 1fr)',
    borderRadius: '1.25rem',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: surface,
    boxShadow: `0 4px 0 ${shadow}`,
    '@media (min-width: 640px)': {
      gridTemplateColumns: '4rem minmax(0, 1fr)',
    },
  },
  passStub: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    paddingBlock: '1rem',
    borderTopLeftRadius: '1.1rem',
    borderBottomLeftRadius: '1.1rem',
    borderRightWidth: '2px',
    borderRightStyle: 'dashed',
    borderRightColor: line,
    backgroundColor: fill,
    color: fillInk,
  },
  passType: {
    writingMode: 'vertical-rl',
    transform: 'rotate(180deg)',
    fontFamily: mono,
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  },
  passIcon: {
    width: '1.25rem',
    height: '1.25rem',
    flexShrink: 0,
  },
  passBody: {
    minWidth: 0,
    paddingBlock: '1.1rem',
    paddingInline: '1.1rem',
    '@media (min-width: 640px)': {
      paddingInline: '1.5rem',
    },
  },
  stop: {
    display: 'grid',
    gridTemplateColumns: '3.25rem 1.25rem minmax(0, 1fr)',
    columnGap: '0.6rem',
    borderRadius: 'var(--trips-radius)',
    '@media (min-width: 640px)': {
      gridTemplateColumns: '4rem 1.5rem minmax(0, 1fr)',
      columnGap: '0.75rem',
    },
  },
  stopRail: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
  },
  stopDot: {
    position: 'relative',
    zIndex: 1,
    flexShrink: 0,
    width: '1.05rem',
    height: '1.05rem',
    marginTop: '0.2rem',
    borderRadius: '999px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: line,
    backgroundColor: fill,
    backgroundImage: 'radial-gradient(circle at 32% 30%, rgb(255 255 255 / 0.85) 0 18%, transparent 24%)',
    boxShadow: `0 2px 0 ${shadow}`,
  },
  stopDotBooked: {
    backgroundColor: 'var(--toy-mint)',
  },
  stopRoute: {
    position: 'absolute',
    top: '1.5rem',
    bottom: '-1.2rem',
    left: '50%',
    width: '2px',
    transform: 'translateX(-50%)',
  },
})
