import * as stylex from '@stylexjs/stylex'
import { layout } from '@/styles/common.stylex'
import { easings, trips } from '@/styles/tokens.stylex'

/** Archivo Narrow display face — matches `.trips .font-display` in index.css. */
export const fontDisplay = {
  fontFamily: '"Archivo Narrow", "Arial Narrow", sans-serif',
  fontWeight: 600,
  letterSpacing: '-0.02em',
  fontStretch: 'condensed',
} as const

const tripsFocus = 'var(--trips-focus)'
const tripsAccentHover = 'var(--trips-accent-hover)'
const tripsBand = 'var(--trips-band)'
const tripsBandInk = 'var(--trips-band-ink)'
const ta = 'var(--ta)'
const taStrong = 'var(--ta-strong)'
const taSoft = 'var(--ta-soft)'
const taRing = 'var(--ta-ring)'

const focusRing = {
  ':focus-visible': {
    outline: 'none',
    boxShadow: `0 0 0 2px ${tripsFocus}`,
  },
} as const

const focusRingInset = {
  ':focus-visible': {
    outline: 'none',
    boxShadow: `inset 0 0 0 2px ${tripsFocus}`,
  },
} as const

const fieldBase = {
  borderRadius: trips.fieldRadius,
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: trips.border,
  backgroundColor: trips.rail,
  boxShadow: 'inset 0 1px 2px color-mix(in oklch, var(--trips-ink) 12%, transparent)',
} as const

const btnBase = {
  display: 'inline-flex',
  minWidth: '2.75rem',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '0.5rem',
  borderRadius: trips.radius,
  transitionProperty: 'color, background-color, border-color, opacity, transform',
  transitionDuration: '150ms',
  transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
} as const

const disabledState = {
  ':disabled': {
    cursor: 'not-allowed',
    opacity: 0.5,
  },
} as const

/** Shared Trips timetable styles — replaces Tailwind class strings from ui.ts. */
export const styles = stylex.create({
  focusRing,
  focusRingInset,

  coverBandPad: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '2rem',
    paddingBottom: '2rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      paddingTop: '2.5rem',
      paddingBottom: '2.5rem',
    },
    '@media (min-width: 1024px)': {
      paddingLeft: '2rem',
      paddingRight: '2rem',
      paddingTop: '3rem',
      paddingBottom: '3rem',
    },
  },
  coverDockPad: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
    '@media (min-width: 1024px)': {
      paddingLeft: '2rem',
      paddingRight: '2rem',
    },
  },
  snapRailSticky: {
    position: 'sticky',
    zIndex: 20,
    marginLeft: '-1rem',
    marginRight: '-1rem',
    marginBottom: '1.25rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: trips.border,
    backgroundColor: trips.canvas,
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    '@media (min-width: 640px)': {
      marginLeft: '-1.5rem',
      marginRight: '-1.5rem',
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },

  // ── Motion helpers (class-only) ────────────────────────────────────────
  spinner: {
    animationName: stylex.keyframes({
      to: { transform: 'rotate(360deg)' },
    }),
    animationDuration: '1s',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  hoverArrow: {
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: easings.outExpo,
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
      '@media (hover: hover)': {
        ':is(.group:hover &)': {
          transform: 'none',
        },
      },
    },
    '@media (hover: hover)': {
      ':is(.group:hover &)': {
        transform: 'translateX(0.125rem)',
      },
    },
  },
  hoverArrowBack: {
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: easings.outExpo,
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
      '@media (hover: hover)': {
        ':is(.group:hover &)': {
          transform: 'none',
        },
      },
    },
    '@media (hover: hover)': {
      ':is(.group:hover &)': {
        transform: 'translateX(-0.125rem)',
      },
    },
  },

  // ── Type roles ─────────────────────────────────────────────────────────
  typeHeroTime: {
    ...fontDisplay,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1,
    fontSize: '2.5rem',
    '@media (min-width: 640px)': {
      fontSize: '3.25rem',
    },
  },
  typeDisplay: {
    ...fontDisplay,
    lineHeight: 1,
    fontSize: '1.875rem',
    '@media (min-width: 640px)': {
      fontSize: '2.25rem',
    },
  },
  typePageTitle: {
    ...fontDisplay,
    fontSize: '1.5rem',
    color: trips.ink,
    '@media (min-width: 640px)': {
      fontSize: '1.75rem',
    },
  },
  typeSection: {
    ...fontDisplay,
    fontSize: '1.25rem',
    color: trips.ink,
  },
  typeBody: {
    fontSize: '1rem',
    lineHeight: 1.625,
  },
  typeMeta: {
    fontSize: '0.8125rem',
    fontWeight: 500,
  },
  typeLabel: {
    fontSize: '0.75rem',
    fontWeight: 500,
  },
  typeStamp: {
    fontSize: '0.6875rem',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  },

  // ── Ink ────────────────────────────────────────────────────────────────
  mutedInk: {
    color: trips.inkSecondary,
  },
  wrapAnywhere: {
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },

  // ── Layout ─────────────────────────────────────────────────────────────
  pageGutter: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '64rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },
  pageForm: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '42rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '1.5rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      paddingTop: '2rem',
    },
  },
  pageReading: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '48rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '1.5rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      paddingTop: '2rem',
    },
  },
  pageWide: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '72rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '1.5rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      paddingTop: '2rem',
    },
  },
  chromeHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 30,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: trips.border,
    backgroundColor: trips.canvas,
  },
  document: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '64rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingBottom: '4rem',
    paddingTop: 0,
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },
  propertyTable: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: trips.border,
    ':not(#\\#) > * + *': {
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: trips.border,
    },
  },
  propertyRow: {
    display: 'grid',
    gridTemplateColumns: '7.5rem minmax(0, 1fr)',
    alignItems: 'baseline',
    gap: '1rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    '@media (min-width: 640px)': {
      gridTemplateColumns: '9rem minmax(0, 1fr)',
    },
  },
  propertyRowDivider: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
  },
  dataTable: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
  },
  dataTh: {
    paddingBottom: '0.5rem',
    paddingRight: '0.75rem',
    fontSize: '12px',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  dataTd: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    paddingRight: '0.75rem',
    verticalAlign: 'top',
  },

  // ── Labels ───────────────────────────────────────────────────────────
  label: {
    display: 'block',
    fontSize: '0.75rem',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  eyebrow: {
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  fieldLabel: {
    display: 'block',
    fontSize: '0.75rem',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  metaLabel: {
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  hint: {
    marginTop: '0.375rem',
    fontSize: '0.75rem',
    fontWeight: 500,
    lineHeight: 1.625,
    color: trips.inkSecondary,
  },
  timeCell: {
    fontFamily: '"Archivo Narrow", "Arial Narrow", sans-serif',
    fontVariantNumeric: 'tabular-nums',
    fontSize: '0.75rem',
    fontWeight: 500,
    letterSpacing: '0.01em',
    color: trips.inkSecondary,
  },

  // ── Inputs ─────────────────────────────────────────────────────────────
  input: {
    ...fieldBase,
    width: '100%',
    minHeight: '2.75rem',
    paddingLeft: '0.875rem',
    paddingRight: '0.875rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.9375rem',
    color: trips.ink,
    textOverflow: 'ellipsis',
    transitionProperty: 'border-color, box-shadow',
    transitionDuration: '150ms',
    ':focus': {
      borderColor: trips.accent,
      outline: 'none',
    },
    ...focusRing,
    '::placeholder': {
      color: trips.inkTertiary,
    },
  },
  displayInput: {
    ...fontDisplay,
    width: '100%',
    minHeight: '2.75rem',
    backgroundColor: 'transparent',
    color: trips.ink,
    '::placeholder': {
      color: trips.inkTertiary,
    },
    ':focus': {
      outline: 'none',
    },
    ...focusRing,
  },
  compactInput: {
    ...fieldBase,
    minHeight: '2.75rem',
    paddingLeft: '0.625rem',
    paddingRight: '0.625rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    fontSize: '0.9375rem',
    color: trips.ink,
    textOverflow: 'ellipsis',
    '@media (min-width: 640px)': {
      minHeight: '2.25rem',
    },
    ':focus': {
      borderColor: trips.accent,
      outline: 'none',
    },
    ...focusRing,
    '::placeholder': {
      color: trips.inkTertiary,
    },
  },
  subtleInput: {
    borderRadius: trips.fieldRadius,
    minHeight: '2.75rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    fontSize: '0.9375rem',
    color: trips.ink,
    textOverflow: 'ellipsis',
    transitionProperty: 'border-color, background-color',
    transitionDuration: '150ms',
    '@media (min-width: 640px)': {
      minHeight: '2.25rem',
    },
    '@media (hover: hover)': {
      ':hover': {
        borderColor: trips.border,
      },
    },
    ':focus': {
      borderColor: trips.accent,
      backgroundColor: trips.rail,
      outline: 'none',
    },
    ...focusRing,
    '::placeholder': {
      color: trips.inkTertiary,
    },
  },
  select: {
    ...fieldBase,
    minHeight: '2.75rem',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.9375rem',
    color: trips.ink,
    ':focus': {
      borderColor: trips.accent,
      outline: 'none',
    },
    ...focusRing,
  },
  compactSelect: {
    ...fieldBase,
    minHeight: '2.75rem',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    color: trips.ink,
    '@media (min-width: 640px)': {
      minHeight: '2.25rem',
    },
    ':focus': {
      borderColor: trips.accent,
      outline: 'none',
    },
    ...focusRing,
  },
  checkbox: {
    height: '2.75rem',
    width: '2.75rem',
    flexShrink: 0,
    borderRadius: trips.radius,
    borderColor: trips.border,
    accentColor: trips.accent,
    ...focusRing,
  },
  fieldShell: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    ...fieldBase,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    transitionProperty: 'border-color, box-shadow',
    transitionDuration: '150ms',
    ':focus-within': {
      borderColor: trips.accent,
      boxShadow: `0 0 0 2px ${tripsFocus}`,
    },
  },
  bareInput: {
    width: '100%',
    minHeight: '2.75rem',
    backgroundColor: 'transparent',
    fontSize: '0.9375rem',
    color: trips.ink,
    textOverflow: 'ellipsis',
    outline: 'none',
    '::placeholder': {
      color: trips.inkTertiary,
    },
  },
  accentIcon: {
    color: trips.accent,
  },
  staticValue: {
    minHeight: '2.25rem',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    fontSize: '0.9375rem',
    color: trips.ink,
  },
  staticField: {
    marginTop: '0.25rem',
    display: 'block',
    paddingLeft: '0.125rem',
    paddingRight: '0.125rem',
    fontSize: '0.9375rem',
    color: trips.ink,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },

  // ── Surfaces ───────────────────────────────────────────────────────────
  softPanel: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
  },
  popover: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
    boxShadow: '0 10px 28px color-mix(in oklch, var(--trips-ink) 16%, transparent)',
  },
  scrim: {
    position: 'fixed',
    inset: 0,
    zIndex: 65,
    backgroundColor: trips.scrim,
    backdropFilter: 'blur(8px)',
    '@media (prefers-reduced-motion: reduce)': {
      backdropFilter: 'none',
    },
  },
  overlayScrim: {
    position: 'fixed',
    inset: 0,
    backgroundColor: trips.scrim,
    backdropFilter: 'blur(8px)',
    '@media (prefers-reduced-motion: reduce)': {
      backdropFilter: 'none',
    },
  },
  skeleton: {
    borderRadius: trips.radius,
    backgroundColor: trips.rail,
    animationName: stylex.keyframes({
      '0%, 100%': { opacity: 1 },
      '50%': { opacity: 0.5 },
    }),
    animationDuration: '2s',
    animationTimingFunction: 'cubic-bezier(0.4, 0, 0.6, 1)',
    animationIterationCount: 'infinite',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  scheduleRow: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
  },
  railBand: {
    borderRadius: trips.radius,
    backgroundColor: trips.rail,
  },
  toast: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    boxShadow: '0 10px 28px color-mix(in oklch, var(--trips-ink) 16%, transparent)',
  },
  menuItemActive: {
    backgroundColor: trips.rail,
    color: trips.ink,
  },
  alertError: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#fca5a5',
    backgroundColor: '#fef2f2',
    padding: '1rem',
    fontSize: '0.9375rem',
    color: '#7f1d1d',
    ':is(html.dark &)': {
      borderColor: 'rgba(127, 29, 29, 0.5)',
      backgroundColor: 'rgba(69, 10, 10, 0.4)',
      color: '#fee2e2',
    },
  },
  alertNotice: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(252, 211, 77, 0.8)',
    backgroundColor: '#fffbeb',
    padding: '1rem',
    fontSize: '0.9375rem',
    color: '#451a03',
    ':is(html.dark &)': {
      borderColor: 'rgba(120, 53, 15, 0.5)',
      backgroundColor: 'rgba(69, 26, 3, 0.4)',
      color: '#fef3c7',
    },
  },
  segmentTrack: {
    display: 'inline-flex',
    width: '100%',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.rail,
    padding: '0.25rem',
    '@media (min-width: 640px)': {
      width: 'auto',
    },
  },
  segmentOption: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    flex: '1 1 0%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: trips.radius,
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.9375rem',
    fontWeight: 500,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (min-width: 640px)': {
      flex: 'none',
    },
    ':has(:focus-visible)': {
      boxShadow: `0 0 0 2px ${tripsFocus}`,
    },
  },
  segmentOptionSelected: {
    backgroundColor: trips.surface,
    color: trips.ink,
  },
  segmentOptionIdle: {
    color: trips.inkSecondary,
    '@media (hover: hover)': {
      ':hover': {
        color: trips.ink,
      },
    },
  },
  stampChip: {
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.rail,
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
  },

  // ── Buttons ────────────────────────────────────────────────────────────
  bandBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    backgroundColor: tripsBandInk,
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 600,
    color: tripsBand,
    '@media (hover: hover)': {
      ':hover': {
        opacity: 0.9,
      },
    },
    ...focusRing,
    ...disabledState,
  },
  bandChip: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    minWidth: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'color-mix(in oklch, var(--trips-band-ink) 35%, transparent)',
    backgroundColor: 'transparent',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: tripsBandInk,
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: 'color-mix(in oklch, var(--trips-band-ink) 10%, transparent)',
      },
    },
    ...focusRing,
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.4,
    },
  },
  primaryBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    backgroundColor: trips.accent,
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: '#ffffff',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: tripsAccentHover,
      },
    },
    ...focusRing,
    ':focus-visible': {
      outline: 'none',
      boxShadow: `0 0 0 2px ${tripsFocus}, 0 0 0 4px ${trips.canvas}`,
    },
    ':is(html.dark &)': {
      color: trips.canvas,
    },
    ...disabledState,
  },
  secondaryBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: 'transparent',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.9375rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: trips.ink,
      },
    },
    ...focusRing,
    ...disabledState,
  },
  ghostBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    paddingLeft: '0.875rem',
    paddingRight: '0.875rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.9375rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: trips.ink,
      },
    },
    ...focusRing,
    ...disabledState,
  },
  overlayHover: {
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: 'color-mix(in oklch, var(--trips-ink) 5%, transparent)',
      },
    },
  },
  ghostOnTintBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    paddingLeft: '0.875rem',
    paddingRight: '0.875rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: '#44403c',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: 'color-mix(in oklch, var(--trips-ink) 5%, transparent)',
        color: '#0c0a09',
      },
    },
    ':is(html.dark &)': {
      color: '#d6d3d1',
      '@media (hover: hover)': {
        ':hover': {
          color: '#fafaf9',
        },
      },
    },
    ...focusRing,
    ...disabledState,
  },
  inkBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    backgroundColor: trips.ink,
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: trips.canvas,
    '@media (hover: hover)': {
      ':hover': {
        opacity: 0.9,
      },
    },
    ...focusRing,
    ':focus-visible': {
      outline: 'none',
      boxShadow: `0 0 0 2px ${tripsFocus}`,
    },
    ...disabledState,
  },
  successBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(5, 150, 105, 0.4)',
    backgroundColor: '#ecfdf5',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 600,
    color: '#064e3b',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: '#d1fae5',
      },
    },
    ':is(html.dark &)': {
      borderColor: 'rgba(16, 185, 129, 0.4)',
      backgroundColor: 'rgba(2, 44, 34, 0.4)',
      color: '#a7f3d0',
      '@media (hover: hover)': {
        ':hover': {
          backgroundColor: 'rgba(2, 44, 34, 0.7)',
        },
      },
    },
    ...focusRing,
    ...disabledState,
  },
  dangerBtn: {
    ...btnBase,
    minHeight: '2.75rem',
    backgroundColor: '#b91c1c',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 600,
    color: '#ffffff',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: '#991b1b',
      },
    },
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px #ef4444',
    },
    ...disabledState,
  },
  chipBtn: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    minWidth: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: 'transparent',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: trips.ink,
      },
    },
    ...focusRing,
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.4,
    },
  },
  accentChipBtn: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    minWidth: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: taRing,
    backgroundColor: taSoft,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: ta,
    transitionProperty: 'color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        color: taStrong,
      },
    },
    ...focusRing,
    ...disabledState,
  },
  quietBtn: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    minWidth: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: trips.ink,
      },
    },
    ...focusRing,
    ...disabledState,
  },
  dangerChipBtn: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    minWidth: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(252, 165, 165, 0.8)',
    backgroundColor: 'transparent',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: '#b91c1c',
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: '#fef2f2',
        color: '#991b1b',
      },
    },
    ':is(html.dark &)': {
      borderColor: 'rgba(127, 29, 29, 0.6)',
      color: '#fca5a5',
      '@media (hover: hover)': {
        ':hover': {
          backgroundColor: 'rgba(69, 10, 10, 0.4)',
          color: '#fecaca',
        },
      },
    },
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px #f87171',
    },
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.4,
    },
  },
  inlineLink: {
    display: 'inline-block',
    borderRadius: trips.radius,
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    marginTop: '-0.375rem',
    marginBottom: '-0.375rem',
    textDecorationLine: 'underline',
    textUnderlineOffset: '2px',
    ...focusRing,
  },
  iconBtn: {
    display: 'inline-flex',
    height: '2.75rem',
    width: '2.75rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: trips.radius,
    color: trips.inkSecondary,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: trips.ink,
      },
    },
    ...focusRing,
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.3,
    },
  },
  dangerIconBtn: {
    display: 'inline-flex',
    height: '2.75rem',
    width: '2.75rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: trips.radius,
    color: trips.inkSecondary,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: '#b91c1c',
      },
    },
    ':is(html.dark &)': {
      '@media (hover: hover)': {
        ':hover': {
          color: '#fca5a5',
        },
      },
    },
    ':focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 2px #f87171',
    },
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.3,
    },
  },

  // ── Accent theme tokens (from theme.ts ACCENT) ─────────────────────────
  accentText: { color: ta },
  accentTextStrong: { color: taStrong },
  accentTextHover: {
    '@media (hover: hover)': {
      ':is(.group:hover &)': {
        color: taStrong,
      },
    },
  },
  accentDot: { backgroundColor: ta },
  accentSoftBg: { backgroundColor: taSoft },
  accentBorder: { borderColor: taRing },
  accentHairline: { backgroundColor: taRing },
  accentRing: {
    boxShadow: `0 0 0 2px ${taRing}`,
  },
  anchorRing: {
    boxShadow: `0 0 0 2px ${taRing}`,
  },

  // ── Status chips ───────────────────────────────────────────────────────
  chipBase: {
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '0.6875rem',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  },
  chipDraft: {
    borderColor: trips.border,
    backgroundColor: trips.rail,
    color: trips.inkSecondary,
  },
  chipArchived: {
    borderColor: trips.border,
    backgroundColor: trips.rail,
    color: trips.inkTertiary,
  },
  chipActive: {
    borderColor: '#6ee7b7',
    backgroundColor: '#ecfdf5',
    color: '#064e3b',
    ':is(html.dark &)': {
      borderColor: 'rgba(6, 78, 59, 0.6)',
      backgroundColor: 'rgba(2, 44, 34, 0.4)',
      color: '#d1fae5',
    },
  },
  chipBooked: {
    borderColor: '#6ee7b7',
    backgroundColor: '#ecfdf5',
    color: '#064e3b',
    ':is(html.dark &)': {
      borderColor: 'rgba(6, 78, 59, 0.6)',
      backgroundColor: 'rgba(2, 44, 34, 0.4)',
      color: '#d1fae5',
    },
  },
  chipOptional: {
    borderColor: '#d6d3d1',
    backgroundColor: '#f5f5f4',
    color: '#44403c',
    ':is(html.dark &)': {
      borderColor: '#44403c',
      backgroundColor: 'rgba(28, 25, 23, 0.6)',
      color: '#d6d3d1',
    },
  },
  chipNeedsReview: {
    borderColor: '#fcd34d',
    backgroundColor: '#fffbeb',
    color: '#451a03',
    ':is(html.dark &)': {
      borderColor: 'rgba(120, 53, 15, 0.6)',
      backgroundColor: 'rgba(69, 26, 3, 0.4)',
      color: '#fef3c7',
    },
  },
  chipCompleted: {
    borderColor: '#d6d3d1',
    backgroundColor: '#f5f5f4',
    color: '#57534e',
    ':is(html.dark &)': {
      borderColor: '#292524',
      backgroundColor: 'rgba(28, 25, 23, 0.6)',
      color: '#a8a29e',
    },
  },
  statusDotBooked: {
    backgroundColor: '#059669',
    ':is(html.dark &)': { backgroundColor: '#34d399' },
  },
  statusDotOptional: {
    backgroundColor: '#a8a29e',
    ':is(html.dark &)': { backgroundColor: '#78716c' },
  },
  statusDotNeedsReview: {
    backgroundColor: '#d97706',
    ':is(html.dark &)': { backgroundColor: '#fbbf24' },
  },
  statusDotCompleted: {
    backgroundColor: '#a8a29e',
    ':is(html.dark &)': { backgroundColor: '#57534e' },
  },
  chipSuggestionAdd: {
    borderColor: '#6ee7b7',
    backgroundColor: '#ecfdf5',
    color: '#064e3b',
    ':is(html.dark &)': {
      borderColor: 'rgba(6, 78, 59, 0.6)',
      backgroundColor: 'rgba(2, 44, 34, 0.4)',
      color: '#d1fae5',
    },
  },
  chipSuggestionRemove: {
    borderColor: '#fca5a5',
    backgroundColor: '#fef2f2',
    color: '#7f1d1d',
    ':is(html.dark &)': {
      borderColor: 'rgba(127, 29, 29, 0.6)',
      backgroundColor: 'rgba(69, 10, 10, 0.4)',
      color: '#fee2e2',
    },
  },
  chipSuggestionNeutral: {
    borderColor: '#d6d3d1',
    backgroundColor: '#f5f5f4',
    color: '#44403c',
    ':is(html.dark &)': {
      borderColor: '#44403c',
      backgroundColor: 'rgba(28, 25, 23, 0.7)',
      color: '#d6d3d1',
    },
  },
  chipAi: {
    borderColor: trips.border,
    backgroundColor: trips.rail,
    color: trips.inkSecondary,
  },

  // ── Status marks ───────────────────────────────────────────────────────
  markOpen: {
    display: 'inline-block',
    height: '0.5rem',
    width: '0.5rem',
    flexShrink: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'currentColor',
    backgroundColor: 'transparent',
  },
  markRotatedWrap: {
    display: 'inline-flex',
    height: '0.625rem',
    width: '0.625rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markRotated: {
    display: 'block',
    height: '0.375rem',
    width: '0.375rem',
    transform: 'rotate(45deg)',
    backgroundColor: 'currentColor',
  },
  markMuted: {
    display: 'inline-block',
    height: '0.5rem',
    width: '0.5rem',
    flexShrink: 0,
    backgroundColor: 'currentColor',
    opacity: 0.45,
  },
  markFilled: {
    display: 'inline-block',
    height: '0.5rem',
    width: '0.5rem',
    flexShrink: 0,
    backgroundColor: 'currentColor',
  },
  markAi: {
    display: 'inline-block',
    height: '0.5rem',
    width: '0.5rem',
    flexShrink: 0,
    backgroundColor: ta,
  },

  // ── Accent swatches ────────────────────────────────────────────────────
  swatchRose: { backgroundColor: '#f43f5e' },
  swatchAmber: { backgroundColor: '#f59e0b' },
  swatchEmerald: { backgroundColor: '#10b981' },
  swatchSky: { backgroundColor: '#0ea5e9' },
  swatchViolet: { backgroundColor: '#8b5cf6' },

  // ── Callout tones ──────────────────────────────────────────────────────
  calloutInfo: {
    borderColor: '#e7e5e4',
    backgroundColor: 'rgba(245, 245, 244, 0.8)',
    ':is(html.dark &)': {
      borderColor: '#292524',
      backgroundColor: 'rgba(28, 25, 23, 0.4)',
    },
  },
  calloutWarn: {
    borderColor: '#fde68a',
    backgroundColor: 'rgba(255, 251, 235, 0.8)',
    ':is(html.dark &)': {
      borderColor: 'rgba(120, 53, 15, 0.5)',
      backgroundColor: 'rgba(69, 26, 3, 0.25)',
    },
  },
  calloutSuccess: {
    borderColor: '#a7f3d0',
    backgroundColor: 'rgba(236, 253, 245, 0.8)',
    ':is(html.dark &)': {
      borderColor: 'rgba(6, 78, 59, 0.5)',
      backgroundColor: 'rgba(2, 44, 34, 0.25)',
    },
  },
  calloutAlert: {
    borderColor: '#fda4af',
    backgroundColor: 'rgba(255, 241, 242, 0.8)',
    ':is(html.dark &)': {
      borderColor: 'rgba(136, 19, 55, 0.6)',
      backgroundColor: 'rgba(76, 5, 25, 0.4)',
    },
  },

  // ── Layout shell (TripsLayout) ─────────────────────────────────────────
  tripsRoot: {
    minHeight: '100dvh',
    color: trips.ink,
  },
  authLoading: {
    display: 'flex',
    minHeight: '70dvh',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '4rem',
    paddingBottom: '4rem',
    color: trips.inkSecondary,
  },
  authSignInShell: {
    display: 'flex',
    minHeight: '70dvh',
    alignItems: 'center',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingTop: '4rem',
    paddingBottom: '4rem',
    '@media (min-width: 640px)': {
      paddingLeft: '2.5rem',
      paddingRight: '2.5rem',
    },
  },
  authSignInInner: {
    width: '100%',
    maxWidth: '24rem',
  },
  authSignInCopy: {
    marginTop: '0.75rem',
    fontSize: '0.9375rem',
    lineHeight: 1.625,
    color: trips.inkSecondary,
  },
  authSignInBtn: {
    marginTop: '2rem',
  },
  skipLink: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
    ':focus': {
      position: 'absolute',
      left: '1rem',
      top: '1rem',
      zIndex: 50,
      display: 'inline-flex',
      minHeight: '2.75rem',
      alignItems: 'center',
      width: 'auto',
      height: 'auto',
      margin: 0,
      clip: 'auto',
      overflow: 'visible',
      whiteSpace: 'normal',
      borderRadius: trips.radius,
      backgroundColor: trips.accent,
      paddingLeft: '1rem',
      paddingRight: '1rem',
      fontSize: '0.875rem',
      lineHeight: '1.25rem',
      fontWeight: 500,
      color: '#ffffff',
    },
    ':is(html.dark &:focus)': {
      color: trips.canvas,
    },
  },
  chromeInner: {
    display: 'flex',
    height: 'var(--trips-chrome-h)',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: 'env(safe-area-inset-top, 0px)',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },
  breadcrumbNav: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '0.375rem',
    '@media (min-width: 640px)': {
      gap: '0.75rem',
    },
  },
  breadcrumbList: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '0.5rem',
  },
  shrink0: {
    flexShrink: 0,
  },
  breadcrumbCrumb: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    gap: '0.5rem',
    color: trips.inkSecondary,
  },
  breadcrumbSep: {
    color: trips.inkTertiary,
  },
  breadcrumbTitle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '0.8125rem',
    fontWeight: 500,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  chromeWordmark: {
    marginLeft: '-0.375rem',
    marginRight: '-0.375rem',
    display: 'inline-flex',
    minHeight: '2.75rem',
    alignItems: 'center',
    borderRadius: trips.radius,
    paddingLeft: '0.375rem',
    paddingRight: '0.375rem',
    ...fontDisplay,
    fontSize: '1.125rem',
    lineHeight: '1.75rem',
    color: trips.ink,
    transitionProperty: 'color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        color: trips.accent,
      },
    },
    ...focusRing,
  },
  chromeNewTrip: {
    display: 'none',
    minHeight: '2.75rem',
    alignItems: 'center',
    gap: '0.375rem',
    borderRadius: trips.radius,
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    '@media (min-width: 640px)': {
      display: 'inline-flex',
    },
    '@media (hover: hover)': {
      ':hover': {
        color: trips.ink,
      },
    },
    ...focusRing,
  },
  chromeActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    '@media (min-width: 640px)': {
      gap: '0.5rem',
    },
  },
  themeToggleWrap: {
    display: 'inline-flex',
  },
  themeToggle: {
    display: 'inline-flex',
    height: '2.75rem',
    width: '2.75rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
    color: trips.inkSecondary,
    transitionProperty: 'border-color, color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        borderColor: trips.accent,
        color: trips.accent,
      },
    },
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: tripsFocus,
      outlineOffset: '2px',
    },
  },
  mainChatPad: {
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: '7rem',
    outline: 'none',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: trips.accent,
      outlineOffset: '2px',
    },
  },
  mainDefault: {
    paddingLeft: 0,
    paddingRight: 0,
    paddingBottom: '2rem',
    outline: 'none',
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: trips.accent,
      outlineOffset: '2px',
    },
  },
  backLinkMobile: {
    '@media (min-width: 640px)': {
      display: 'none',
    },
  },

  // ── FlipTime ───────────────────────────────────────────────────────────
  flipRoot: {
    display: 'inline-flex',
    fontVariantNumeric: 'tabular-nums',
  },
  flipReduced: {
    fontVariantNumeric: 'tabular-nums',
  },

  // ── TripsIndex extras ──────────────────────────────────────────────────
  hairlineList: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: trips.border,
  },
  skeletonBar: {
    borderRadius: '0.125rem',
    backgroundColor: 'color-mix(in oklch, var(--trips-ink) 10%, transparent)',
    animationName: stylex.keyframes({
      '0%, 100%': { opacity: 1 },
      '50%': { opacity: 0.5 },
    }),
    animationDuration: '2s',
    animationTimingFunction: 'cubic-bezier(0.4, 0, 0.6, 1)',
    animationIterationCount: 'infinite',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  deleteConfirm: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    borderRadius: trips.radius,
    backgroundColor: '#fef2f2',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    '@media (min-width: 640px)': {
      flexWrap: 'nowrap',
    },
    ':is(html.dark &)': {
      backgroundColor: 'rgba(69, 10, 10, 0.3)',
    },
  },
  deleteConfirmText: {
    minWidth: 0,
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: '#7f1d1d',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': {
      color: '#fecaca',
    },
  },
  deleteActions: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.5rem',
  },
  timetableRow: {
    position: 'relative',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
    paddingTop: '1rem',
    paddingBottom: '1rem',
  },
  timetableOverlayLink: {
    position: 'absolute',
    inset: 0,
    zIndex: 1,
    ...focusRingInset,
  },
  timetableTitle: {
    ...fontDisplay,
    minWidth: 0,
    fontSize: '1.25rem',
    lineHeight: 1.25,
    color: '#1c1917',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': {
      color: '#f5f5f4',
    },
  },
  timetableMeta: {
    marginTop: '0.25rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: trips.inkSecondary,
  },
  timetableMark: {
    ...fontDisplay,
    fontSize: '1.125rem',
    lineHeight: 1.25,
    fontVariantNumeric: 'tabular-nums',
    color: trips.ink,
  },
  timetableStats: {
    marginTop: '0.25rem',
    fontSize: '13px',
    fontVariantNumeric: 'tabular-nums',
    color: trips.inkSecondary,
  },
  dangerIconHidden: {
    position: 'relative',
    zIndex: 10,
    '@media (hover: hover)': {
      ':is(.group:hover &)': {
        opacity: 1,
      },
    },
    '@media (min-width: 640px)': {
      opacity: 0,
      ':focus-visible': {
        opacity: 1,
      },
    },
  },

  // ── TripChat ───────────────────────────────────────────────────────────
  chatPanelShell: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 60,
    marginLeft: 'auto',
    marginRight: 'auto',
    display: 'flex',
    width: '100%',
    flexDirection: 'column',
    overflow: 'hidden',
    borderTopLeftRadius: trips.radius,
    borderTopRightRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
    '@media (min-width: 768px)': {
      left: 'auto',
      right: '1.5rem',
      borderRadius: trips.radius,
    },
  },
  chatPanelCompact: {
    height: 'min(86dvh, 40rem)',
    '@media (min-width: 768px)': {
      bottom: '1.5rem',
      height: 'min(600px, calc(100dvh - 3rem))',
      width: 'min(400px, calc(100vw - 2rem))',
    },
  },
  chatHeaderIconBtn: {
    display: 'flex',
    height: '2.75rem',
    width: '2.75rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: trips.radius,
    color: trips.inkSecondary,
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: trips.rail,
        color: trips.ink,
      },
    },
    ...focusRing,
  },
  chatComposer: {
    maxHeight: '12rem',
  },
  chatComposerExpanded: {
    minHeight: '1.75rem',
    flex: '1 1 0%',
    resize: 'none',
    backgroundColor: 'transparent',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '16px',
    lineHeight: '1.5rem',
    color: trips.ink,
    outline: 'none',
    maxHeight: '12rem',
    '@media (min-width: 640px)': {
      fontSize: '15px',
    },
    '::placeholder': {
      color: trips.inkTertiary,
    },
  },
  chatComposerCompact: {
    minHeight: '1.75rem',
    flex: '1 1 0%',
    resize: 'none',
    backgroundColor: 'transparent',
    paddingTop: '0.125rem',
    paddingBottom: '0.125rem',
    fontSize: '16px',
    lineHeight: '1.5rem',
    color: trips.ink,
    outline: 'none',
    maxHeight: '7rem',
    '@media (min-width: 640px)': {
      fontSize: '15px',
    },
    '::placeholder': {
      color: trips.inkTertiary,
    },
  },
  chatSendBtn: {
    position: 'relative',
    marginBottom: '1px',
    display: 'flex',
    height: '1.75rem',
    width: '1.75rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    backgroundColor: trips.accent,
    color: '#ffffff',
    transitionProperty: 'background-color, opacity',
    transitionDuration: '150ms',
    '::before': {
      content: '""',
      position: 'absolute',
      inset: '-0.5rem',
    },
    ':disabled': {
      cursor: 'not-allowed',
      opacity: 0.4,
    },
    ':is(html.dark &)': {
      color: '#0c0a09',
    },
    '@media (hover: hover)': {
      ':enabled:hover': {
        backgroundColor: tripsAccentHover,
      },
    },
    ...focusRing,
  },
  chatFab: {
    position: 'fixed',
    right: '1rem',
    zIndex: 40,
    display: 'flex',
    height: '3.5rem',
    width: '3.5rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    backgroundColor: trips.accent,
    color: '#ffffff',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
    outline: 'none',
    '@media (hover: hover)': {
      ':hover': {
        backgroundColor: tripsAccentHover,
      },
    },
    ':is(html.dark &)': {
      color: '#0c0a09',
    },
    ...focusRing,
  },
  chatOverlayExpanded: {
    zIndex: 55,
  },
  chatOverlayCompact: {
    zIndex: 55,
    '@media (min-width: 768px)': {
      pointerEvents: 'none',
      backgroundColor: 'transparent',
      backdropFilter: 'none',
    },
  },
  chatHeader: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.75rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: trips.border,
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
  },
  chatHeaderIcon: {
    display: 'flex',
    height: '2.25rem',
    width: '2.25rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: trips.radius,
    backgroundColor: taSoft,
    color: ta,
  },
  chatHeaderBody: {
    minWidth: 0,
    flex: '1 1 0%',
  },
  chatTitleTruncate: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chatSubtitleTruncate: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  chatHeaderActions: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
  },
  chatScroll: {
    minHeight: 0,
    flex: '1 1 0%',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '1rem',
    paddingBottom: '1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  chatEmpty: {
    display: 'flex',
    height: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    textAlign: 'center',
  },
  chatEmptyIcon: {
    display: 'flex',
    height: '3rem',
    width: '3rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: trips.radius,
    backgroundColor: taSoft,
    color: ta,
  },
  chatEmptyCopy: {
    maxWidth: '18rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: trips.inkSecondary,
  },
  chatUserRow: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  chatUserBubble: {
    maxWidth: '85%',
    borderRadius: trips.radius,
    backgroundColor: trips.accent,
    paddingLeft: '0.875rem',
    paddingRight: '0.875rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '15px',
    lineHeight: 1.625,
    color: '#ffffff',
    ':is(html.dark &)': {
      color: trips.canvas,
    },
  },
  chatSpacer: {
    pointerEvents: 'none',
    flexShrink: 0,
  },
  chatFooter: {
    flexShrink: 0,
  },
  chatSuggestions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingBottom: '0.5rem',
  },
  chatSuggestionBtn: {
    minHeight: '2.75rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.rail,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    textAlign: 'left',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: trips.inkSecondary,
    transitionProperty: 'border-color, background-color, color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        borderColor: taRing,
        backgroundColor: taSoft,
        color: taStrong,
      },
    },
    ...focusRing,
  },
  chatForm: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.75rem',
  },
  chatComposerShell: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '0.5rem',
    borderRadius: trips.fieldRadius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.rail,
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    boxShadow: 'inset 0 1px 2px color-mix(in oklch, var(--trips-ink) 12%, transparent)',
    ':focus-within': {
      borderColor: trips.accent,
      boxShadow: `0 0 0 2px ${tripsFocus}`,
    },
  },
  chatAssistantRow: {
    display: 'flex',
    justifyContent: 'flex-start',
  },
  chatAssistantBubble: {
    maxWidth: '88%',
    borderRadius: trips.radius,
    backgroundColor: trips.rail,
    paddingLeft: '0.875rem',
    paddingRight: '0.875rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
    color: trips.ink,
  },
  chatTypingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
  },
  chatTypingDot: {
    height: '0.375rem',
    width: '0.375rem',
    borderRadius: '9999px',
    backgroundColor: trips.inkTertiary,
    opacity: 0.7,
  },
  chatTypingDotMotion: {
    height: '0.375rem',
    width: '0.375rem',
    borderRadius: '9999px',
    backgroundColor: trips.inkTertiary,
  },
  iconLg: {
    height: '1.5rem',
    width: '1.5rem',
  },
  iconSend: {
    height: '0.875rem',
    width: '0.875rem',
  },
  conciergeSourceLink: {
    overflowWrap: 'anywhere',
    textDecorationLine: 'underline',
    textDecorationColor: taRing,
    textUnderlineOffset: '2px',
    textDecorationThickness: '1px',
    transitionProperty: 'color',
    transitionDuration: '150ms',
    '@media (hover: hover)': {
      ':hover': {
        color: taStrong,
      },
    },
    ':focus-visible': {
      outlineWidth: '2px',
      outlineStyle: 'solid',
      outlineColor: tripsFocus,
      outlineOffset: '2px',
    },
  },

  // ── Layout primitives (common.stylex re-exports) ───────────────────────
  srOnly: layout.srOnly,
  relative: layout.relative,
  absolute: layout.absolute,
  fixed: layout.fixed,
  inset0: layout.inset0,
  flex: layout.flex,
  flexCol: layout.flexCol,
  flexRow: layout.flexRow,
  flexWrap: { display: 'flex', flexWrap: 'wrap' },
  itemsCenter: layout.itemsCenter,
  itemsStart: layout.itemsStart,
  itemsBaseline: { alignItems: 'baseline' },
  justifyBetween: layout.justifyBetween,
  justifyEnd: layout.justifyEnd,
  mxAuto: layout.mxAuto,
  wFull: layout.wFull,
  block: { display: 'block' },
  inlineFlex: { display: 'inline-flex' },
  inlineBlock: { display: 'inline-block' },
  truncate: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  capitalize: { textTransform: 'capitalize' },
  whitespacePreLine: { whiteSpace: 'pre-line' },
  whitespaceNowrap: { whiteSpace: 'nowrap' },
  tabularNums: layout.tabularNums,
  fontMedium: layout.fontMedium,
  fontSemibold: layout.fontSemibold,
  fontNormal: layout.fontNormal,
  fontMonoTrips: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  textXs: layout.textXs,
  textSm: layout.textSm,
  textLg: layout.textLg,
  text2xl: { fontSize: '1.5rem', lineHeight: '2rem' },
  trackingTight: layout.trackingTight,
  uppercaseTrackingWide: {
    textTransform: 'uppercase',
    letterSpacing: '0.14em',
  },
  lineClamp2: {
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  rotate45: { transform: 'rotate(45deg)' },
  rotateNeg135: { transform: 'rotate(-135deg)' },
  rotate180: { transform: 'rotate(180deg)' },
  transitionTransform: {
    transitionProperty: 'transform',
    transitionDuration: '200ms',
    transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  motionReduceTransitionNone: {
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
  },
  inkPrimary: {
    color: '#1c1917',
    ':is(html.dark &)': { color: '#f5f5f4' },
  },
  inkSecondaryStone: {
    color: '#44403c',
    ':is(html.dark &)': { color: '#d6d3d1' },
  },
  inkMutedStone: {
    color: '#78716c',
    ':is(html.dark &)': { color: '#a8a29e' },
  },
  inkBand75: {
    color: 'color-mix(in oklch, var(--trips-band-ink) 75%, transparent)',
  },
  inkBand80: {
    color: 'color-mix(in oklch, var(--trips-band-ink) 80%, transparent)',
  },
  inkBandInk: { color: tripsBandInk },
  bgCanvas: { backgroundColor: trips.canvas },
  bgSurface: { backgroundColor: trips.surface },
  bgRail: { backgroundColor: trips.rail },
  bgScrim: { backgroundColor: trips.scrim },
  borderTrips: { borderColor: trips.border },
  borderDashedTrips: {
    borderWidth: '1px',
    borderStyle: 'dashed',
    borderColor: trips.border,
  },
  roundedTrips: { borderRadius: trips.radius },
  roundedField: { borderRadius: trips.fieldRadius },
  divideHairline: {
    '> * + *': {
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: trips.border,
    },
  },
  divideStone: {
    '> * + *': {
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'rgba(28, 25, 23, 0.12)',
      ':is(html.dark &)': {
        borderTopColor: 'rgba(41, 37, 36, 0.8)',
      },
    },
  },
  hairlineListDivided: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: trips.border,
    '> * + *': {
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: trips.border,
    },
  },
  sheetRule: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    paddingTop: '1.25rem',
  },
  mt1: { marginTop: '0.25rem' },
  mt1_5: { marginTop: '0.375rem' },
  mt2: { marginTop: '0.5rem' },
  mt3: { marginTop: '0.75rem' },
  mt4: { marginTop: '1rem' },
  mt5: { marginTop: '1.25rem' },
  mt6: { marginTop: '1.5rem' },
  mt8: { marginTop: '2rem' },
  mt10: { marginTop: '2.5rem' },
  mt12: { marginTop: '3rem' },
  mb3: { marginBottom: '0.75rem' },
  my3: { marginTop: '0.75rem', marginBottom: '0.75rem' },
  ml1_5: { marginLeft: '0.375rem' },
  mr1_5: { marginRight: '0.375rem' },
  negMx2: { marginLeft: '-0.5rem', marginRight: '-0.5rem' },
  negMy3: { marginTop: '-0.75rem', marginBottom: '-0.75rem' },
  negMb5: { marginBottom: '-1.25rem' },
  negMx5: { marginLeft: '-1.25rem', marginRight: '-1.25rem' },
  pt0_5: { paddingTop: '0.125rem' },
  py1: { paddingTop: '0.25rem', paddingBottom: '0.25rem' },
  py1_5: { paddingTop: '0.375rem', paddingBottom: '0.375rem' },
  py2: { paddingTop: '0.5rem', paddingBottom: '0.5rem' },
  py3: { paddingTop: '0.75rem', paddingBottom: '0.75rem' },
  py5: { paddingTop: '1.25rem', paddingBottom: '1.25rem' },
  py8: { paddingTop: '2rem', paddingBottom: '2rem' },
  px2: { paddingLeft: '0.5rem', paddingRight: '0.5rem' },
  px3: { paddingLeft: '0.75rem', paddingRight: '0.75rem' },
  px4: { paddingLeft: '1rem', paddingRight: '1rem' },
  px5: { paddingLeft: '1.25rem', paddingRight: '1.25rem' },
  p4: { padding: '1rem' },
  p5: { padding: '1.25rem' },
  gap1: { gap: '0.25rem' },
  gap1_5: { gap: '0.375rem' },
  gap2: { gap: '0.5rem' },
  gap3: { gap: '0.75rem' },
  gap4: { gap: '1rem' },
  gapX3: { columnGap: '0.75rem' },
  gapX4: { columnGap: '1rem' },
  gapY1: { rowGap: '0.25rem' },
  gapY2: { rowGap: '0.5rem' },
  spaceY3: { display: 'flex', flexDirection: 'column', gap: '0.75rem' },
  spaceY4: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  spaceY5: { display: 'flex', flexDirection: 'column', gap: '1.25rem' },
  spaceY2: { display: 'flex', flexDirection: 'column', gap: '0.5rem' },
  leadingSnug: { lineHeight: 1.375 },
  maxW2xl: { maxWidth: '42rem' },
  maxW3xl: { maxWidth: '48rem' },
  maxW5xl: { maxWidth: '64rem' },
  maxWCh58: { maxWidth: '58ch' },
  maxWCh60: { maxWidth: '60ch' },
  maxWCh42: { maxWidth: '42ch' },
  maxWCh46: { maxWidth: '46ch' },
  maxWCh28: { maxWidth: '28ch' },
  maxWFull: { maxWidth: '100%' },
  w40: { width: '10rem' },
  w56: { width: '14rem' },
  w24: { width: '6rem' },
  w44: {
    '@media (min-width: 640px)': { width: '11rem' },
  },
  h3: { height: '0.75rem' },
  h4: { height: '1rem' },
  h5: { height: '1.25rem' },
  h10: { height: '2.5rem' },
  h16: { height: '4rem' },
  h20: { height: '5rem' },
  h40: { height: '10rem' },
  w48: { width: '12rem' },
  w72: { width: '18rem' },
  w2_3: { width: '66.666667%' },
  w3_4: { width: '75%' },
  w1_2: { width: '50%' },
  w1_4: { width: '25%' },
  minH11: { minHeight: '2.75rem' },
  minH14: { minHeight: '3.5rem' },
  minHScreenCenter: {
    position: 'fixed',
    inset: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: trips.scrim,
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: tripsBandInk,
  },
  gridCols1: { display: 'grid', gridTemplateColumns: 'repeat(1, minmax(0, 1fr))' },
  gridCols2Sm: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: '1.25rem',
    '@media (min-width: 640px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  gridCols2SmGap4: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: '1rem',
    '@media (min-width: 640px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  gridColsDateRange: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: '1.25rem',
    '@media (min-width: 640px)': {
      gridTemplateColumns: '3fr 2fr',
    },
  },
  gridColsItem: {
    display: 'grid',
    gridTemplateColumns: '3.25rem minmax(0, 1fr)',
    gap: '0.75rem',
    borderRadius: trips.radius,
    '@media (min-width: 640px)': {
      gridTemplateColumns: '4rem minmax(0, 1fr)',
    },
  },
  gridColsPrefs: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: '1rem',
    '@media (min-width: 640px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  flexColSmRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
      alignItems: 'center',
    },
  },
  flexColSmRowBetween: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  flexWrapCenterGap2: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem',
  },
  flexWrapCenterGap3: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  flexWrapBaselineGap4: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    columnGap: '1rem',
    rowGap: '0.25rem',
  },
  flexStartGap2: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
  },
  flexCenterGap2: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  flexCenterGap4: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  flexBetweenGap4: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
  },
  flexBetweenMinH14: {
    display: 'flex',
    minHeight: '3.5rem',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
  },
  inlineFlexCenterGap2: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  inlineFlexCenterGap2MinH11: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    alignItems: 'center',
    gap: '0.5rem',
  },
  stickyFooter: {
    position: 'sticky',
    bottom: 0,
    zIndex: 20,
    marginTop: '2rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    backgroundColor: trips.canvas,
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '1rem',
    paddingBottom: '1rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },
  formPb16: { paddingBottom: '4rem' },
  placesFooter: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '48rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingBottom: '2.5rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },
  statusSelectShell: {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    marginTop: '-0.75rem',
    marginBottom: '-0.75rem',
    borderRadius: trips.radius,
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    paddingRight: '0.25rem',
    ':has(:focus-visible)': {
      boxShadow: `0 0 0 2px ${tripsFocus}`,
    },
  },
  statusSelectOverlay: {
    position: 'absolute',
    inset: 0,
    height: '100%',
    width: '100%',
    cursor: 'pointer',
    appearance: 'none',
    opacity: 0,
    ':disabled': {
      cursor: 'not-allowed',
    },
  },
  chevronMuted: {
    height: '0.75rem',
    width: '0.75rem',
    flexShrink: 0,
    color: '#78716c',
    ':is(html.dark &)': { color: '#a8a29e' },
  },
  iconPin: {
    marginTop: '0.125rem',
    height: '1rem',
    width: '1rem',
    flexShrink: 0,
    color: ta,
  },
  placeCard: {
    overflow: 'hidden',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
  },
  placeCardBody: {
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.625rem',
    paddingBottom: '0.625rem',
  },
  placeCardActions: {
    marginTop: '0.5rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.375rem',
  },
  placeLink: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    alignItems: 'center',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: '#1c1917',
    textDecorationLine: 'underline',
    textDecorationColor: '#d6d3d1',
    textUnderlineOffset: '2px',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#f5f5f4' },
    '@media (hover: hover)': {
      ':hover': { textDecorationColor: 'currentColor' },
    },
    ...focusRing,
  },
  coverBandMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: '0.75rem',
    rowGap: '0.5rem',
    color: 'color-mix(in oklch, var(--trips-band-ink) 80%, transparent)',
  },
  coverBandTitleInput: {
    minHeight: '2.75rem',
    width: '100%',
    backgroundColor: 'transparent',
    color: tripsBandInk,
    '::placeholder': {
      color: 'color-mix(in oklch, var(--trips-band-ink) 40%, transparent)',
    },
    ':focus': { outline: 'none' },
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  coverExtraTags: {
    marginTop: '1.25rem',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.375rem',
  },
  coverCtaRow: {
    marginTop: '1.5rem',
  },
  coverStampOnBand: {
    borderColor: 'color-mix(in oklch, var(--trips-band-ink) 25%, transparent)',
    backgroundColor: 'transparent',
    color: 'color-mix(in oklch, var(--trips-band-ink) 80%, transparent)',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  todayAside: {
    marginTop: '1.5rem',
    borderRadius: trips.radius,
  },
  todayAsideLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
  },
  accentDotSm: {
    display: 'inline-block',
    height: '0.375rem',
    width: '0.375rem',
    borderRadius: '9999px',
  },
  todayAsideTitle: {
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 600,
    color: '#1c1917',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#f5f5f4' },
  },
  emptyItinerary: {
    marginTop: '1rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'dashed',
    borderColor: trips.border,
    backgroundColor: trips.rail,
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '2rem',
    paddingBottom: '2rem',
    fontSize: '1rem',
    lineHeight: '1.5rem',
  },
  reservationListItem: {
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: '#292524',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#e7e5e4' },
  },
  settingsSection: {
    marginTop: '3rem',
    paddingBottom: '0.5rem',
  },
  reservationsSection: {
    marginTop: '3rem',
    paddingBottom: '1rem',
  },
  sectionMt10: { marginTop: '2.5rem' },
  sectionMt12: { marginTop: '3rem' },
  dayPageTitle: {
    fontSize: '1.5rem',
    lineHeight: '2rem',
    fontWeight: 600,
    letterSpacing: '-0.025em',
    color: '#1c1917',
    ':is(html.dark &)': { color: '#f5f5f4' },
  },
  dayNavLink: {
    display: 'inline-block',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    marginTop: '-0.375rem',
    marginBottom: '-0.375rem',
    color: '#44403c',
    transitionProperty: 'color',
    transitionDuration: '150ms',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#d6d3d1' },
    '@media (hover: hover)': {
      ':hover': { textDecorationLine: 'underline' },
    },
    ...focusRing,
  },
  dayNavSep: {
    color: '#d6d3d1',
    ':is(html.dark &)': { color: '#57534e' },
  },
  dayHeroTime: {
    ...fontDisplay,
    minWidth: 0,
    lineHeight: 1,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  dayDateLine: {
    marginTop: '0.75rem',
    ...fontDisplay,
    fontSize: '1.125rem',
    lineHeight: '1.75rem',
    fontVariantNumeric: 'tabular-nums',
  },
  dayNotes: {
    marginTop: '0.75rem',
    maxWidth: '60ch',
    whiteSpace: 'pre-line',
    fontSize: '0.875rem',
    lineHeight: '1.625',
    color: '#44403c',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#d6d3d1' },
  },
  calloutRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.75rem',
    borderRadius: trips.radius,
    borderWidth: '1px',
    borderStyle: 'solid',
    padding: '1rem',
    fontSize: '1rem',
    lineHeight: '1.5rem',
    color: trips.ink,
  },
  dayItemHeroTitle: {
    marginTop: '0.75rem',
    ...fontDisplay,
    fontSize: '1.25rem',
    lineHeight: 1.25,
    fontWeight: 600,
    letterSpacing: '-0.025em',
    color: trips.ink,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    '@media (min-width: 640px)': {
      fontSize: '1.5rem',
      lineHeight: '2rem',
    },
  },
  dayPagerRow: {
    marginTop: '2.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
  },
  dayPagerLink: {
    display: 'flex',
    minHeight: '3.5rem',
    alignItems: 'center',
    gap: '1rem',
    borderRadius: trips.radius,
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    marginLeft: '-0.5rem',
    marginRight: '-0.5rem',
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
  },
  dayPagerLinkEnd: {
    '@media (min-width: 640px)': {
      order: 2,
      justifyContent: 'flex-end',
      textAlign: 'right',
    },
  },
  dayPagerLinkStart: {
    '@media (min-width: 640px)': {
      order: 1,
    },
  },
  dayPagerLabel: {
    display: 'block',
    fontSize: '13px',
    lineHeight: '1.25rem',
  },
  dayPagerTitle: {
    fontSize: '1rem',
    lineHeight: '1.5rem',
    fontWeight: 600,
    color: trips.ink,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  dayPagerIcon: {
    height: '1rem',
    width: '1rem',
    flexShrink: 0,
    color: trips.inkTertiary,
  },
  itemTimeCol: {
    paddingTop: '0.125rem',
    textAlign: 'right',
  },
  itemTitleLink: {
    fontWeight: 500,
    color: '#1c1917',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#f5f5f4' },
  },
  itemNotesSm: {
    marginTop: '0.25rem',
    fontSize: '0.875rem',
    lineHeight: '1.625',
    color: '#44403c',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#d6d3d1' },
  },
  itemMapLink: {
    marginTop: '0.25rem',
    display: 'block',
    borderRadius: trips.radius,
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    marginBottom: '-0.375rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    textDecorationLine: 'underline',
    textDecorationColor: '#d6d3d1',
    textUnderlineOffset: '2px',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': {
      textDecorationColor: '#57534e',
    },
    '@media (hover: hover)': {
      ':hover': { color: '#1c1917' },
    },
    ...focusRing,
  },
  enhanceSplit: {
    position: 'relative',
    display: 'inline-flex',
  },
  enhanceFooter: {
    marginTop: '0.75rem',
    marginLeft: '-1.25rem',
    marginRight: '-1.25rem',
    marginBottom: '-1.25rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '0.5rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    paddingLeft: '1.25rem',
    paddingRight: '1.25rem',
    paddingTop: '0.75rem',
    paddingBottom: '0.75rem',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  ingestRoot: { marginTop: '0.5rem' },
  ingestForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
      alignItems: 'center',
    },
  },
  ingestOptions: {
    marginTop: '0.25rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: '0.75rem',
    rowGap: '0.25rem',
  },
  ingestSkipLabel: {
    display: 'inline-flex',
    minHeight: '2.75rem',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    color: '#57534e',
    ':is(html.dark &)': { color: '#a8a29e' },
  },
  compactInputMobile: {
    minWidth: 0,
    flex: '1 1 0%',
    fontSize: '16px',
    '@media (min-width: 640px)': {
      fontSize: '0.875rem',
      lineHeight: '1.25rem',
    },
  },
  chipBtnFullSmAuto: {
    width: '100%',
    '@media (min-width: 640px)': {
      width: 'auto',
    },
  },
  ingestJobList: { marginTop: '0.25rem' },
  ingestJobRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  ingestPlaceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
  },
  itemRowSection: {
    position: 'relative',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
  },
  itemRowSchedule: {
    position: 'relative',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
  },
  itemRowHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  sectionHeadingInput: {
    minHeight: '2.75rem',
    minWidth: 0,
    flex: '1 1 0%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    borderRadius: trips.fieldRadius,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    paddingLeft: '0.25rem',
    paddingRight: '0.25rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: trips.inkSecondary,
    transitionProperty: 'border-color',
    transitionDuration: '150ms',
    '::placeholder': { color: trips.inkTertiary },
    '@media (hover: hover)': {
      ':hover': { borderColor: trips.border },
    },
    ':focus': {
      borderColor: trips.accent,
      outline: 'none',
    },
    '@media (min-width: 640px)': {
      minHeight: 0,
      letterSpacing: '0.16em',
    },
  },
  amberStatus: {
    marginTop: '1rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: '#78350f',
    ':is(html.dark &)': { color: '#fde68a' },
  },
  createNameInput: {
    color: tripsBandInk,
    '::placeholder': {
      color: 'color-mix(in oklch, var(--trips-band-ink) 40%, transparent)',
    },
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  createTagChip: {
    color: trips.ink,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  createStickyBar: {
    display: 'flex',
    maxWidth: '42rem',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  createStatusNote: {
    width: '100%',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    color: '#57534e',
    '@media (min-width: 640px)': {
      width: 'auto',
    },
    ':is(html.dark &)': { color: '#a8a29e' },
  },
  textRightSm: {
    '@media (min-width: 640px)': {
      textAlign: 'right',
    },
  },
  order1Sm2: {
    order: 1,
    '@media (min-width: 640px)': { order: 2 },
  },
  order2Sm1: {
    order: 2,
    '@media (min-width: 640px)': { order: 1 },
  },
  cursorPointer: { cursor: 'pointer' },
  z1: { zIndex: 1 },
  z10: { zIndex: 10 },
  scrollMt32: {
    scrollMarginTop: '8rem',
    '@media (min-width: 1024px)': { scrollMarginTop: '6rem' },
  },
  dayCardBorder: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: trips.border,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: '1.5rem',
    paddingBottom: '1.5rem',
    transitionProperty: 'background-color',
    transitionDuration: '300ms',
  },
  panelMt5Pad5: {
    marginTop: '1.25rem',
    padding: '1.25rem',
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
  },
  panelMt6Pad5: {
    marginTop: '1.5rem',
    padding: '1.25rem',
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
  },
  panelTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '1rem',
    lineHeight: '1.5rem',
    fontWeight: 600,
    color: '#1c1917',
    ':is(html.dark &)': { color: '#f5f5f4' },
  },
  panelActionsRow: {
    marginTop: '0.75rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.75rem',
  },
  floatingSaveRoot: {
    pointerEvents: 'none',
    position: 'fixed',
    left: '50%',
    bottom: '1.5rem',
    zIndex: 50,
    display: 'flex',
    transform: 'translateX(-50%)',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.5rem',
  },
  floatingSavePill: {
    pointerEvents: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    borderRadius: '9999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: trips.border,
    backgroundColor: trips.surface,
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: trips.ink,
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
  },
  timezoneRoot: { position: 'relative' },
  timezoneCity: { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  timezoneCityName: { fontWeight: 500 },
  dateStripDay: {
    display: 'flex',
    flexShrink: 0,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '2.75rem',
    minHeight: '2.75rem',
    borderRadius: trips.radius,
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '150ms',
    ...focusRing,
  },
  dateRangeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    gap: '1rem',
    '@media (min-width: 640px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
  },
  extractedSection: { marginTop: '1.5rem' },
  extractedToolbar: {
    marginTop: '0.75rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    '@media (min-width: 640px)': {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  extractedCheckboxLabel: {
    display: 'flex',
    minHeight: '2.75rem',
    alignItems: 'center',
    gap: '0.5rem',
    '@media (min-width: 640px)': { minHeight: '2.25rem' },
  },
  extractedGroup: { marginTop: '0.375rem' },
  extractedSubgroup: { marginTop: '0.125rem' },
  extractedCityLabel: {
    fontSize: '11px',
    fontWeight: 500,
    color: '#57534e',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#a8a29e' },
  },
  extractedPager: {
    marginTop: '0.75rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
  },
  extractedPagerBtns: { display: 'flex', gap: '0.25rem' },
  extractedPlaceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    paddingTop: '0.375rem',
    paddingBottom: '0.375rem',
  },
  extractedPlaceLink: {
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: '#1c1917',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#f5f5f4' },
    '@media (hover: hover)': {
      ':hover': { textDecorationLine: 'underline' },
    },
  },
  linkSemiboldMt1: {
    marginTop: '0.25rem',
    fontWeight: 600,
  },
  skeletonMt8: { marginTop: '2rem' },
  skeletonMt6: { marginTop: '1.5rem' },
  skeletonSpaceY3: {
    marginTop: '2.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  tdNowrap: { whiteSpace: 'nowrap' },
  tdDisplayNums: {
    ...fontDisplay,
    fontVariantNumeric: 'tabular-nums',
  },
  tdTitle: {
    fontWeight: 500,
    color: '#1c1917',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': { color: '#f5f5f4' },
    ...focusRing,
  },
  coverBandInner: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '64rem',
  },
  coverActionsRow: {
    marginTop: '1.25rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem',
  },
  coverDescBand: {
    marginTop: '0.75rem',
    maxWidth: '58ch',
    fontSize: '0.9375rem',
    lineHeight: 1.625,
    color: 'color-mix(in oklch, var(--trips-band-ink) 75%, transparent)',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  coverDescBandRelaxed: {
    marginTop: '0.75rem',
    maxWidth: '58ch',
    fontSize: '0.9375rem',
    lineHeight: 1.625,
    color: 'color-mix(in oklch, var(--trips-band-ink) 75%, transparent)',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  bandChipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '0.5rem',
  },
  settingsLabel: {
    fontSize: '13px',
    fontWeight: 500,
  },
  motionPanel: {
    '@media (prefers-reduced-motion: reduce)': {
      transitionProperty: 'none',
    },
  },
  opacity60: { opacity: 0.6 },
  emojiGap: { marginRight: '0.375rem' },

  // ── Misc layout primitives ─────────────────────────────────────────────
  flex1: layout.flex1,
  minW0: layout.minW0,
  itineraryStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  iconSm: {
    height: '1rem',
    width: '1rem',
  },
  iconXs: {
    height: '0.875rem',
    width: '0.875rem',
  },
  iconMd: {
    height: '1.25rem',
    width: '1.25rem',
  },
  notFoundPage: {
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '72rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingTop: '4rem',
    paddingBottom: '4rem',
    '@media (min-width: 640px)': {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
    },
  },
  notFoundCode: {
    fontSize: '13px',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  notFoundTitle: {
    marginTop: '0.75rem',
    fontSize: '1.5rem',
    lineHeight: '2rem',
    fontWeight: 600,
    letterSpacing: '-0.025em',
    color: '#1c1917',
    ':is(html.dark &)': {
      color: '#f5f5f4',
    },
  },
  notFoundCopy: {
    marginTop: '0.75rem',
    maxWidth: '65ch',
    fontSize: '0.875rem',
    lineHeight: '1.625',
    color: trips.inkSecondary,
  },
  notFoundLink: {
    marginTop: '1.5rem',
  },

  sectionHeading: {
    paddingBottom: '0.75rem',
  },
  sectionSubtitle: {
    marginTop: '0.25rem',
    maxWidth: '56ch',
    fontSize: '0.9375rem',
    lineHeight: 1.625,
    color: trips.inkSecondary,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  propertyLabel: {
    fontSize: '13px',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  propertyValue: {
    fontSize: '0.875rem',
    lineHeight: '1.25rem',
    color: '#292524',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':is(html.dark &)': {
      color: '#e7e5e4',
    },
  },
  coverDockInner: {
    marginLeft: 'auto',
    marginRight: 'auto',
    display: 'flex',
    height: '100%',
    width: '100%',
    alignItems: 'center',
  },
  coverDockInnerWide: {
    maxWidth: '64rem',
  },
  coverDockInnerForm: {
    maxWidth: '42rem',
  },
  coverDockTitle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  tripClock: {
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.375rem',
    fontSize: '11px',
    fontWeight: 500,
    color: trips.inkSecondary,
  },
  tripClockBand: {
    color: 'color-mix(in oklch, var(--trips-band-ink) 75%, transparent)',
  },
  tripClockFlipBand: {
    ...fontDisplay,
    fontVariantNumeric: 'tabular-nums',
    color: tripsBandInk,
  },
  tripClockFlipSheet: {
    ...fontDisplay,
    fontVariantNumeric: 'tabular-nums',
    color: trips.ink,
  },
  tripClockZone: {
    ...fontDisplay,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
  },
  nextDepartureLink: {
    display: 'block',
    marginTop: '1.5rem',
    minHeight: '2.75rem',
    ...focusRing,
  },
  nextDepartureRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    columnGap: '1rem',
    rowGap: '0.25rem',
  },
  nextDepartureFallbackTitle: {
    ...fontDisplay,
    fontSize: '1.25rem',
    lineHeight: 1.25,
    fontWeight: 600,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  nextDepartureItemTitle: {
    minWidth: 0,
    maxWidth: '28ch',
    ...fontDisplay,
    fontSize: '1.25rem',
    lineHeight: 1.25,
    fontWeight: 600,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    '@media (min-width: 640px)': {
      fontSize: '1.5rem',
      lineHeight: '2rem',
    },
  },
  nextDepartureMeta: {
    marginTop: '0.5rem',
    fontSize: '0.8125rem',
    color: trips.inkSecondary,
  },
  nextDepartureMetaBand: {
    marginTop: '0.5rem',
    fontSize: '0.8125rem',
    color: 'color-mix(in oklch, var(--trips-band-ink) 70%, transparent)',
  },
})

/** Page width variants — use with sx(styles.pageForm | pageReading | pageWide). */
export type PageWidth = 'form' | 'reading' | 'wide'

export function pageStyle(width: PageWidth = 'wide') {
  switch (width) {
    case 'form':
      return styles.pageForm
    case 'reading':
      return styles.pageReading
    default:
      return styles.pageWide
  }
}

export function segmentOption(selected: boolean) {
  return selected
    ? [styles.segmentOption, styles.segmentOptionSelected]
    : [styles.segmentOption, styles.segmentOptionIdle]
}

export function suggestionChipStyle(kind: 'add' | 'remove' | 'neutral') {
  switch (kind) {
    case 'add':
      return styles.chipSuggestionAdd
    case 'remove':
      return styles.chipSuggestionRemove
    default:
      return styles.chipSuggestionNeutral
  }
}

export function calloutToneStyle(tone: 'info' | 'warn' | 'success' | 'alert') {
  switch (tone) {
    case 'info':
      return styles.calloutInfo
    case 'warn':
      return styles.calloutWarn
    case 'success':
      return styles.calloutSuccess
    case 'alert':
      return styles.calloutAlert
  }
}

export function accentSwatchStyle(accent: 'rose' | 'amber' | 'emerald' | 'sky' | 'violet') {
  switch (accent) {
    case 'rose':
      return styles.swatchRose
    case 'amber':
      return styles.swatchAmber
    case 'emerald':
      return styles.swatchEmerald
    case 'sky':
      return styles.swatchSky
    case 'violet':
      return styles.swatchViolet
  }
}

export { focusRing as focusRingStyle, focusRingInset as focusRingInsetStyle }
