name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Build frontend
        working-directory: frontend
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > .env
          bun install
          bun run build

      - name: Deploy backend
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            set -e
            rm -rf ~/anthonyl.im/
            git clone git@github.com:anthonylim24/anthonyl.im.git
            cp ~/.env ~/anthonyl.im/.env
            cd ~/anthonyl.im/
            curl -fsSL https://bun.sh/install | bash
            ~/.bun/bin/bun install

      - name: Upload frontend build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          source: "frontend/dist"
          target: "anthonyl.im/frontend"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            set -e
            ~/.bun/bin/bun add -g pm2
            ~/.bun/bin/pm2 restart anthonyl.im
            echo 'Deployment successful to Digital Ocean'
